### ISSUE TITLE
Doesn't work for 'off-cluster with kubernetes' case

### ISSUE THREAD

**Issue by Drugoy** [openshift/console#10175]
[Hardcodes](https://github.com/openshift/console/search?q=openshift-console-user-settings) like these</a> prevent from using this tool for 'off-cluster with kubernetes' case: opening web UI produces pages without any kube-resources.
Navigating between endpoints produces errors like these:
> Failed to dial backend: 'websocket: bad handshake' Status '403 Forbidden' URL: 'https://mykubeclusterhostport/api/v1/namespaces/openshift-console-user-settings/...

Surely I don't have a namespace of such name and neither did I query WebUI to show resources from that non-existent namespace.
And this error is even produced every time I hit a button to list namespaces.

**Comment by spadgett** [comment]
@Drugoy You should be able to start bridge with `-user-settings-location localstorage`. Does it work?

**Comment by spadgett** [comment]
We might wait for the `OPENSHIFT` flag to resolve before trying to use the user settings config maps, although setting the flag when starting bridge should prevent the errors.

cc @christianvogt @rohitkrai03

**Comment by Drugoy** [comment]
@spadgett This makes it not spawn errors in the log for my actions, but the WebUI still doesn't show any kube-resources (not even namespaces).

**Comment by spadgett** [comment]
> @spadgett This makes it not spawn errors in the log for my actions, but the WebUI still doesn't show any kube-resources (not even namespaces).

@Drugoy Hm, that's likely unrelated to user settings. Are there any other errors in the JS console? What k8s version?

**Comment by Drugoy** [comment]
@spadgett No, none.
v1.19.3

**Comment by spadgett** [comment]
The master branch of openshift/console expects k8s 1.22+. It could be that the console is using a newer API not in 1.19. It also could be simply a configuration problem. Any errors in the network tab of the browser developer tools?

The `release-4.6` branch is meant to work with k8s 1.19, or image `quay.io/openshift/origin-console:4.6`

**Comment by Drugoy** [comment]
Thanks, will try.
Is there a guide on how to run a local docker container of quay.io/openshift/origin-console:4.6 with access to an external k8s cluster?
Because I'm not sure if build script would produce a working result if I run it over after building from master.

**Comment by spadgett** [comment]
@Drugoy `git checkout release-4.6 && ./build.sh` should work AFAIK.
