### ISSUE TITLE
Make `app.openshift.io/runtime` an annotation

### ISSUE THREAD

**Issue by dalelotts** [openshift/console#10191]
Currently, the `app.openshift.io/runtime` label determines the runtime icon in topology view.  Since it must be a label, it is not easy (is it even possible?) to set the `app.openshift.io/runtime` label in a Tekton pipeline using kustomize (this is because `kustomize edit set label` modifies labels _and_ selectors. Having the runtime included in a service selector is suboptimal if not just a bad idea. 

Making `app.openshift.io/runtime` an annotation means I can use kustomize to set the annotation without impacting selectors. 

Of course, I could just add the label to the deployment yaml in the source code repository being built, but that's just one more thing to keep track of and keep in-sync. It seems reasonable to set the value in the pipeline (at least in my case) because the pipeline knows which runtime it is building. 👍 

I'm fairly new to k8s and OpenShift so I might be missing the reasoning, but to me, it doesn't seem like `app.openshift.io/runtime` does not make sense as a label. 🤷‍♂️

**Comment by spadgett** [comment]
cc @christianvogt @rohitkrai03
