### ISSUE TITLE
Add new drag and drop handle icon for reordering environment variables

### ISSUE THREAD

**Issue by jennyhaines** [openshift/console#102]
I'm working with Mary Shakshober (UXD Visual Design Intern) to get some drag and drop handle icons created and put into PatternFly for use in reordering environment variables, here: PR #88 

Looking to have the icons designed by 6/15, and put into PatternFly during PF's next sprint! Will update here when those icons are available to use.

**Comment by beanh66** [comment]
@jennyhaines Adding a screenshot of the environment variables page with the new drag and drop interaction in context. Let me know if you have any feedback. 
![drag-and-drop-styles](https://user-images.githubusercontent.com/18057044/42347816-0f86af12-8075-11e8-9f16-9c8d65ebec57.png)

**Comment by jennyhaines** [comment]
Yes- that looks good! Thanks @beanh66! FYI @rebeccaalpert , the icon is finished and a dev from the UXD team will add it into PatternFly soon!

**Comment by rebeccaalpert** [comment]
The icon is officially in Patternfly as of today: https://github.com/patternfly/patternfly/pull/1145/commits

I have a couple of higher-priority JIRA tickets I need to close out first, but I will tackle this once they're done.

**Comment by rebeccaalpert** [comment]
See https://github.com/openshift/console/pull/632.
