### ISSUE TITLE
Update download odo link in Command Line Tools page

### ISSUE THREAD

**Issue by rnapoles-rh** [openshift/console#10415]
The download odo link in Help > Command Line Tools of the web console points to mirror.openshift.com (https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/).
New releases are no longer pushed to mirror.openshift.com.

The link should point to our new CDN location at https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/latest

**IMPACTS end user** as the current link in the console is obsolete

**Comment by rnapoles-rh** [comment]
@spadgett  @rohitkrai03 any idea for when this is planned to be fixed?

**Comment by rnapoles-rh** [comment]
@spadgett @rohitkrai03 hi, any update on this one?

**Comment by rnapoles-rh** [comment]
@nimishamukherjee can you help us getting this one fixed? It is impacting end users as the current link is obsolete.

**Comment by rohitkrai03** [comment]
@rnapoles-rh We are tracking the issue with this bugzilla ticket - https://bugzilla.redhat.com/show_bug.cgi?id=2036937.

**Comment by spadgett** [comment]
Closing as this is now tracked in Bugzilla.
