### ISSUE TITLE
AFter OAUTH, base url going in infinite loop

### ISSUE THREAD

**Issue by Ankitcapco** [openshift/console#10575]
HI All,

I am using following way to deploy OKD, I am using Microsoft Authenticator and able to successfully login and in pod logs as well showing outh success. But after successfully login, it is going to BASE-URL and there it is going in an infinite loop. Is there any workaround for it? Please help,

- name: BRIDGE_USER_AUTH_OIDC_ISSUER_URL
          value: https://sts.windows.net/********************/
        - name: BRIDGE_USER_AUTH_OIDC_CLIENT_ID
          value: *******************************
        - name: BRIDGE_USER_AUTH_OIDC_CLIENT_SECRET
          value: *******************************
        - name: BRIDGE_USER_AUTH
          value: oidc
        - name: BRIDGE_BASE_ADDRESS
          value: "https://console.internal.mgmt.platformzero.build"
        - name: BRIDGE_K8S_MODE
          value: in-cluster
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
          value: https://kubernetes.default #master api
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
          value: "true" # no tls enabled
        - name: BRIDGE_K8S_AUTH
          value: bearer-token
        - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: console-token-##### console serviceaccount token
              key: token
![Screen Shot 2021-11-29 at 10 42 45 AM](https://user-images.githubusercontent.com/92543508/143898700-7d16304d-c1a5-44d5-a35e-5f364f297ad2.png)

**Comment by sca-** [comment]
same here
