### ISSUE TITLE
 Propagate the provider information in the UI

### ISSUE THREAD

**Issue by yangcao77** [openshift/console#10664]
Since https://github.com/openshift/console/pull/10394 has been merged, the registry index info and the devfile samples now contain the provider information. i.e.
https://github.com/devfile-samples/devfile-sample-java-springboot-basic/blob/34ef90bcdd9271854e3167b2307cafce12a56c73/devfile.yaml#L12
https://github.com/devfile/registry/blob/1266aaaf631f0a92a83c1f5154b776452df04b39/extraDevfileEntries.yaml#L10

ODC should show this information in UI.

**Comment by spadgett** [comment]
cc @rohitkrai03

**Comment by rohitkrai03** [comment]
/close 

https://github.com/openshift/console/pull/10682 fixed this issue.
