### ISSUE TITLE
Build log raw downloads a file

### ISSUE THREAD

**Issue by orangeji11** [openshift/console#10746]
HI All,

I am using ocp with versioni 4.7.3,when I used the build, I clicked on the Raw link of the log, and then download log-file,instead of opening a new web page, it looks like an Download action,is this a bug or design?

https://user-images.githubusercontent.com/39036074/147630517-3595cae0-db76-4164-a3c2-c3844cc092f6.mp4

**Comment by orangeji11** [comment]
It may be because of the failure of the build. I tried the log of successful build and there is no such problem :)

**Comment by spadgett** [comment]
It's meant to open a new window. What OS and browser are you using?

**Comment by spadgett** [comment]
cc @TheRealJon
