### ISSUE TITLE
Question: about OCP console, Why ``route `` can't be shown in resources page .

### ISSUE THREAD

**Issue by bjwyun** [openshift/console#10841]
here's the question I got when I change to resources page of the CR. 
in fact ,I have a ``route`` which is created by this CR with the same label and annotations about ``pod``. What I expect is the ``route`` can also show in this page. but it doesn't.
<img width="963" alt="image" src="https://user-images.githubusercontent.com/31024715/149489467-c8e6c6ed-1518-46ca-a712-42f85039364b.png">

and by checking the network. I found we haven't send the request to get ``route`` when we change to ``resources`` page.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/31024715/149489478-775335e6-2c3c-47c0-9880-50c427e2395d.png">

Can any one help on this question? thanks. and if it's possible, do we have some workaround to should ``route`` in this resources page. thanks.

**Comment by spadgett** [comment]
Is this the operand details under Installed Operators. I believe we're simply missing route from this list of default resources:

https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/k8s-resource.tsx#L41-L49

cc @TheRealJon
