### ISSUE TITLE
Container status should be sorter by order

### ISSUE THREAD

**Issue by spadgett** [openshift/console#109]
The container statuses on the pod page should be sorted in the order they're declared in the array, first init containers then regular containers.

cc @smarterclayton 
/kind bug
/area usability
/priority p2

**Comment by smarterclayton** [comment]
This was web-console, sorry.  But we should double check here:

Init containers -> Containers, both sorted by the order they appear in the pod definition.  We have tools and cli patterns that prioritize the first container, and we want sidecars to be later in the list.

**Comment by spadgett** [comment]
Yeah meant to open this in the other repository. Will move.

/close

**Comment by spadgett** [comment]
Moved to https://github.com/openshift/origin-web-console/issues/3015
