### ISSUE TITLE
statusDescriptors don't seem to work for cluster-wide resources

### ISSUE THREAD

**Issue by PiotrWodecki** [openshift/console#10901]
Whenever I try using [statusDescriptors](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#statusDescriptors-1) for a cluster-wide CR it doesn't seem to affect anything. I couldn't find any examples online of anyone doing this.
Is it possible, and if not, why?

**Comment by spadgett** [comment]
cc @TheRealJon

**Comment by PiotrWodecki** [comment]
Hi @spadgett, @TheRealJon
Could I get an answer to this question?
If not possible already maybe I would be able to implement this.
