### ISSUE TITLE
feat: Support running PipelineRuns with .spec.status "PipelineRunPending"

### ISSUE THREAD

**Issue by djzager** [openshift/console#11060]
When interacting with Pipelines/PipelineRuns in the developer perspective, it is not currently possible to move a PipelineRun with the status "PipelineRunPending" to the running state.

It would be appropriate for users to have the ability to run Pipelines that are currently in the pending state w/o creating an entirely new PipelineRun. Some screenshots are included below where I would expect to see a "Run" option.

![1642797250](https://user-images.githubusercontent.com/569754/154113722-09eb8249-48ab-407e-b58a-c15efc7d7d93.png)

![1642797275](https://user-images.githubusercontent.com/569754/154113356-b8e98f7d-fd38-451a-a141-579f8911e0a1.png)

cc @eriknelson @mturley

**Comment by spadgett** [comment]
cc @christianvogt @serenamarie125

**Comment by christianvogt** [comment]
cc @karthikjeeyar

**Comment by karthikjeeyar** [comment]
Yeah, we have a RFE for Resuming the pipelinerun here https://issues.redhat.com/browse/RFE-2423, will add this feature soon.

**Comment by djzager** [comment]
As best I understand, this is still a valid issue.
