### ISSUE TITLE
Operator details page is broken

### ISSUE THREAD

**Issue by eivantsov** [openshift/console#1113]
Steps to reproduce:

1. Run console from the latest Docker image against OKD 3.11
2. Create https://raw.githubusercontent.com/operator-framework/getting-started/master/memcachedoperator.0.0.1.csv.yaml
3. Go to installed operators and click on the operator name:

![image](https://user-images.githubusercontent.com/5337267/51428271-c93e6300-1bcf-11e9-84f6-187bf223ef60.png)

**Comment by spadgett** [comment]
> Run console from the latest Docker image against OKD 3.11

You shouldn't be running the latest console against a 3.11 cluster. Do you see this error in a 4.0 install?

**Comment by spadgett** [comment]
Closing as this is not a valid configuration. Console relies on new APIs in 4.0. Please reopen if you can reproduce on a 4.0 cluster.

/close
