### ISSUE TITLE
x-descriptor for map and boolean pointer (UI Markers)

### ISSUE THREAD

**Issue by Milind21** [openshift/console#11159]
Is there any x-descriptor to show the maps in the UI and boolean pointer as switch?
Existing text and other descriptor doesn't seem to work.
The ALM annotations have the map field but it is not getting rendered in the UI

**Comment by spadgett** [comment]
cc @tlwu2013 @TheRealJon

**Comment by Milind21** [comment]
Hi, Any update regarding the issue of x-descriptors.

**Comment by spadgett** [comment]
For the boolean switch, does this work for you?

https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#4-booleanswitch

I don't believe there is a way to show maps, so that would be a new enhancement.

**Comment by Milind21** [comment]
Boolean switch seems to work for bool variables. 
However, pointers to data types like bool and string don't seem to work in similar fashion. ex. boolean switch doesn't show the desired output for *bool.

**Comment by spadgett** [comment]
Console deals with the resource JSON, which doesn't have pointers. I'm assuming if the pointer is `nil` the JSON property is left out, and this breaks the switch? Or is it another problem?

**Comment by Milind21** [comment]
This behaviour is also seen in case of string pointers which are being properly populated. So I'm assuming, we have to pass values explicitly?
There is a map field - Labels which gets rendered in the UI by default. How is this done? 
Maybe we can leverage this to print other map structures? 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/29847417/164592426-48a49ce4-e9dd-4ec3-833f-662bae540bff.png)

**Comment by spadgett** [comment]
Hi, @Milind21. I'm a little confused because JSON and YAML don't have the concept of pointers. Are you using a Golang API?

**Comment by Milind21** [comment]
Yes, we are using golang and we had variables of type pointer which is now getting rendered. 
However, can you please open enhancement for map issue or let me know how to open that issue

**Comment by Veritasosrb** [comment]
HI, @spadgett, Can you please tell about the roadmap on when we might have support for rendering map on the UI.
