### ISSUE TITLE
Dark theme updates

### ISSUE THREAD

**Issue by mattnolting** [openshift/console#11153]
# Dark theme integration

Creating this epic to track color (border, background, font) updates for dark theme integration. Example color updates here: https://codepen.io/bobcatTaco/pen/NWwVYzq

## Border colors

- [ ] #ccc, #ddd, $pf-color-black-300, $color-row-filter-border, $color-grey-background-border => --pf-global--BorderColor--100 <a href="https://codepen.io/bobcatTaco/pen/NWwVYzq#ccc-ddd-black-300" target="_blank">CodePen example</a>
- [ ] #eee, #ededed, $table-border-color, $pf-color-black-200 => var(--pf-global--BorderColor—300)
- [ ] (For borders only) --pf-global--Color--400 => --pf-global--BorderColor--200
- [ ] $color-row-filter-border--active => var(--pf-global--primary-color--100)
- [ ] darken($color-row-filter-border--active, 25%) => var(--pf-global--primary-color--200)
- [ ] darken($color-row-filter-border, 40%) => var(--pf-global--BorderColor--200);
- [ ] #66afe9 => var(--pf-global--active-color--400)

## Font Colors

**Comment by spadgett** [comment]
@mattnolting Have these items since been completed?

cc @sg00dwin
