### ISSUE TITLE
Allow saving/editing custom PromQL queries in Monitoring > Metrics 

### ISSUE THREAD

**Issue by omajid** [openshift/console#11181]
I am using OpenShift 4.8 as a non-admin user.

In the developer view, I can see a list of pre-written metrics that are being collected.

I can also write and plot custom promql queries in the Monitoring > Metrics tab:

![image](https://user-images.githubusercontent.com/174451/158402631-44734ef9-954d-426b-a58b-56f2a8bf7c9d.png)

However, there's no way to save queries. Every time I want to see my applications' custom metric, I have to re-type the entire query.

Can you make it possible to save these queries and edit (or even delete/re-add) them once they have been saved?

**Comment by spadgett** [comment]
cc @alimobrem

**Comment by spadgett** [comment]
@kyoto FYI

**Comment by omajid** [comment]
*sigh*

**Comment by kyoto** [comment]
Thanks @omajid 

This request is covered by issue https://issues.redhat.com/browse/OU-12.

I suggest we close this here and track it in Jira.

/close
