### ISSUE TITLE
It is impossible to get container logs in the UI for init containers

### ISSUE THREAD

**Issue by garagatyi** [openshift/console#1119]
It is impossible to get container logs in the UI for init containers. 
So, when an application inside of init container fails UI shows only init error status. No logs are available, no events in the events view are present.
But it is possible to get logs using OC `oc logs <POD> -c <CONTAINER>`.
This makes an investigation of a problem with an application way harder. 
Please, add this feature.

**Comment by spadgett** [comment]
I agree this is important. What version are you using?

This should be fixed in the 3.11 admin console and 4.0 console by #122.

**Comment by ibuziuk** [comment]
AFAIK, we are using `v3.11.43` but init container logs are not available in pod logs

**Comment by spadgett** [comment]
Are you using the developer console or admin console in 3.11?

**Comment by ibuziuk** [comment]
could you clarify the difference (I thought those are synonyms for `OpenShift Web Console` ) ?

**Comment by spadgett** [comment]
There are two console in 3.11, a developer-focused console and an admin console. By default, if you installed with Ansible, you'll have both. If you're using `oc cluster up`, you'll only have the developer console. If you don't see any option for "Developer Console" and "Cluster Console" in a dropdown in the masthead, you probably don't have the admin console.

In 4.0, there will only be one console, which combines features of both and is developed in this repo.

Init container logs are available specifically in the 3.11 admin console and the 4.0 console.

**Comment by ibuziuk** [comment]
@spadgett I do think I have permissions to do so :(

**Comment by spadgett** [comment]
What error do you see?

**Comment by ibuziuk** [comment]
![image](https://user-images.githubusercontent.com/1461122/51546163-dd01f780-1e63-11e9-9499-5ae0bfd18c20.png)

**Comment by spadgett** [comment]
Are you logging in with the same ID as the other console? You might need to request access again.

Closing since init container logs have been added to the 4.0 console in #122

/close
