### ISSUE TITLE
fieldDependency descriptor only has AND condition option 

### ISSUE THREAD

**Issue by rahulsb** [openshift/console#11318]
As per the documentation : https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#20-fielddependency

I'm using two `fieldDependency` descriptor for my attribute . 
I do understand that , the dependent field ( which is of type `booleanSwitch`) will be enabled when the 2 dependency has the exact values as mentioned in the descriptor
In this usecase, the field `OperationOption` is a drop down to select one value. I need to enable the dependent field when any of the  `fieldDependency` specified in that is true. A kind of an OR operation instead of always AND.

I want to enable my dependent field when any of the specified fieldDependency is true vs all dependency true ( which is current behaviour ).
`xDescriptors={"urn:alm:descriptor:com.tectonic.ui:booleanSwitch","urn:alm:descriptor:com.tectonic.ui:fieldDependency:allApplications:false","urn:alm:descriptor:com.tectonic.ui:fieldDependency:OperationOption:backup"}`

**Comment by spadgett** [comment]
I don't believe this is possible today. @TheRealJon Do you know?

/remove-lifecycle stale
