### ISSUE TITLE
Can we show multiple fields in status column on the OCP console

### ISSUE THREAD

**Issue by Milind21** [openshift/console#11454]
How do we render multiple fields in the status column for a CR on OCP console. 
In case of an operator phase was being shown without adding any operator-sdk UI marker, however no other fields are being shown on the UI. 
Is there a proper method to show this?

**Comment by spadgett** [comment]
It's not currently possible unfortunately. Console will try to find the "best" value to show for the resource status and return the first it finds. Here is the logic:

https://github.com/openshift/console/blob/e0076f435bf8088577bd11c869abb3048b19f4dd/frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx#L174-L208

cc @TheRealJon
