### ISSUE TITLE
Bug 2094240: Fixing inconsistency of button description between notification and the kebab action in the MachineConfigPools tab. 

### ISSUE THREAD

**Issue by l1xiangyi** [openshift/console#11676]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2094240
The `Resume rollout` in the `[MachineConfigPools] > MachineConfigPool details` page is inconsistent with the `Resume updates` button appeared in the kebab action dropdown menu.
Before:
<img width="2031" alt="Screen Shot 2022-06-09 at 07 54 16" src="https://user-images.githubusercontent.com/51786539/172736409-7f59c274-088e-499a-b6ac-45188e536981.png">
After:
<img width="2031" alt="Screen Shot 2022-06-09 at 07 54 32" src="https://user-images.githubusercontent.com/51786539/172736436-e3dc44f7-b607-4e05-b304-e55a61b518f8.png">

Also as my mentor @yapei pointed out, the `WorkloadPausedAlert` is reused in the `Deployment` tab. So I used conditional rendering so that it shows `Resume updates` for **MCP** and `Resume rollouts` for other pages.

**Comment by l1xiangyi** [comment]
#11677

**Comment by spadgett** [comment]
Thank you for the PR. I'm closing the issue as this is also tracked in Bugzilla.

/close
