### ISSUE TITLE
 catalog-tile-pf-description is incorrect for Operator Hub items (Red Hat Quay and Red Hat Quay Bridge Operator)

### ISSUE THREAD

**Issue by pbmoses** [openshift/console#11729]
The description tiles for Red Hat Quay and Red Hat Quay Bridge Operator are incorrect.

Red Hat Quay description tile = "Opinionated deployment of Red Hat on Kubernetes" should read "...Red Hat Quay..."

Red Hat Quay Bridge Operator tile = "Enhance OCP using Red Hat Red Hat container Registry" should read "...Red Hat Quay container registry."

OCP version =  4.10.15

<img width="564" alt="Screen Shot 2022-06-18 at 11 27 12 PM" src="https://user-images.githubusercontent.com/24865328/174468835-d434b58d-631d-41ef-8efa-1774b26ccfc7.png">

**Comment by spadgett** [comment]
@pbmoses Thank you for letting us know.

@BillDett Where is the best place to report these issues to the Quay team?

**Comment by pbmoses** [comment]
It's actually in the Quay operator, I remember digging this out and getting sidetracked. Still sidetracked but not in the console, in the operator.
