### ISSUE TITLE
Editing the YAML file hover prompt causes the content to be uneditable

### ISSUE THREAD

**Issue by orangeji11** [openshift/console#11764]
In the version of openshift I have used, there has always been a problem that bothers me. When editing the content of the YAML file, the prompt content that appears always blocks the area to be edited, which makes me unable to edit the content normally. I can only use copy and paste or Use the arrow keys to move on one side. Is it possible to make the prompt content only appear on the left side, and a little suggestion does not intend to offend the designer.
![录屏_选择区域_20220627131431](https://user-images.githubusercontent.com/39036074/175866037-03aa3675-62da-4091-8ad0-10717bc914ad.gif)

**Comment by orangeji11** [comment]
@spadgett Thanks.

**Comment by orangeji11** [comment]
It should be mentioned that only when there is enough content, the prompt content will block the editing area. If the content is too small, it will not block the editing area. Refer to the figure below. The prompt content on the left and right sides of the editor line is the same.
![截图_选择区域_20220627134510](https://user-images.githubusercontent.com/39036074/175868281-ecc870cb-c890-4127-9444-dace86b5e1d1.jpg)

**Comment by spadgett** [comment]
This looks like a Monaco editor bug with the tooltip positioning. I did a few searches of their repo for similar issues and couldn't find anything. We could try updating the dependency and if that doesn't fix it reporting the issue upstream.

cc @jhadvig @JPinkney 
/kind bug
