### ISSUE TITLE
How to make OLM field conditional?

### ISSUE THREAD

**Issue by omhingmire** [openshift/console#11829]
I have one of the fields in my spec ex. FileSystem.  Markers for those looks like : 

```
         // +required
	// +kubebuilder:validation:Required
	// +kubebuilder:default:=Remote File System
	// +operator-sdk:csv:customresourcedefinitions:order=3,type=spec,displayName="File system",xDescriptors={"urn:alm:descriptor:com.tectonic.ui:select:Remote File System","urn:alm:descriptor:com.tectonic.ui:select:Local File System"}
	FileSystem string `json:"FileSystem,omitempty"`
```

I want to make this field visible on UI under some conditions. If that condition is true then we see the selection drop-down otherwise I want to make it hidden.  Is there a way to achieve this? I am using operator-sdk version v1.9.0

**Comment by spadgett** [comment]
cc @TheRealJon
