### ISSUE TITLE
How to consume getConsoleRequestHeaders?

### ISSUE THREAD

**Issue by wrd0** [openshift/console#11839]
I see it listed in the API docs but it's not being exported in the code for public use nor is it being used anywhere other than internal use cases, am I missing something?

https://github.com/openshift/console/blob/618cb2562170df662dc0a5ae01cc4fb8858b482b/frontend/packages/console-dynamic-plugin-sdk/docs/api.md#getconsolerequestheaders

Any help would be much appreciated thank you.

**Comment by spadgett** [comment]
I would not expect you to need to use this directly if you use the various kubernetes utilities in the API, which already add these headers. This might have been exposed unintentionally.

cc @christianvogt @vojtechszocs @florkbr

**Comment by wrd0** [comment]
Yeah the reason this is needed/useful is when your dynamic plugin codebase use Axios instead of fetch, one could just add this "headers: getConsoleRequestHeaders()" in your axios.create({}) global configuration and you wouldn't need to change your API calls to use fetch.

I found a workaround by wrapping consoleFetch responses to output an axios-like format, like an adapter, it works but feels like a hack.
