### ISSUE TITLE
No openshift x-descriptor for creating radio buttons

### ISSUE THREAD

**Issue by aman98** [openshift/console#12010]
I am trying to recreate this Openshift UI component below:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/20244919/187949216-667febed-a229-41d3-9894-77a1b60fe0ed.png">

But I cannot find the correct` x-descriptor ` or `spec-descriptor` to create radio button elements using `operator-sdk` API markers?

I referred to this document here: **https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md** but I was unable to find an answer. 

Thanks in advance!

**Comment by jerolimov** [comment]
Hello @aman98, a radio box is currently not supported, maybe a `select` (dropdown) can help in the meantime?

![image](https://user-images.githubusercontent.com/139310/197581730-681dc7c4-1b53-46b0-8863-4ec8c537f48a.png)

https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#17-select

/label component/olm
