### ISSUE TITLE
Inconsistent unit labels in the PVC creation form

### ISSUE THREAD

**Issue by andybraren** [openshift/console#1209]
When creating a Persistent Volume Claim, the unit dropdown next to the size field starts as `GiB`. Interacting with the dropdown changes the unit label from the expected `MiB/GiB/TiB` to the abbreviated `Mi/Gi/Ti` instead. Since abbreviated units are used elsewhere in the console, it seems like the elongated labels should be replaced.

![pvc-unit-change](https://user-images.githubusercontent.com/9122899/53191270-64649700-35d9-11e9-8a84-b09f9b505801.png)

**Comment by zherman0** [comment]
Opened PR1228 to fix this https://github.com/openshift/console/pull/1228
