### ISSUE TITLE
Cluster settings: dark theme has unreadable color for cluster versions

### ISSUE THREAD

**Issue by mdujava** [openshift/console#12176]
In dark theme, numbers over the nodes in graph on cluster settings page have black color on dark background, which is hard to read.

![image](https://user-images.githubusercontent.com/5232235/196173259-b06869b0-6567-46f0-afb3-58fb579f5e02.png)

Looks like this line is resetting the color:

https://github.com/openshift/console/blob/e26ca04af6de6e08fe4fa1bbd8286053f6ff8a6a/frontend/public/components/cluster-settings/_cluster-settings.scss#L145

Observed on OpenShift 4.11.6

**Comment by jerolimov** [comment]
Hello @mdujava, thanks for letting us know. I can not reproduce this issue (tested on 4.11.3, latest 4.11, and latest 4.12).

As you shared already a scss link, can you take a look into the dom and share a screenshot from the text `span` element and the computed color style?

Like this:

![image](https://user-images.githubusercontent.com/139310/197579746-12b55e07-cfed-4c25-83b1-c6c50bfb369f.png)

Thanks!

**Comment by mdujava** [comment]
Hi @jerolimov,

![image](https://user-images.githubusercontent.com/5232235/197588657-d5aec46b-db00-49e4-af03-3db7ca5365c6.png)

I am using FF 106.0.1 and in about:addons > Themes I use Dark theme.
![image](https://user-images.githubusercontent.com/5232235/197587505-4dba60af-edc1-435f-8b4c-79f373273f3e.png)

I Tried this on Chromium (just chenging color of browser to dark colors) but was not able to reproduce. 
![image](https://user-images.githubusercontent.com/5232235/197588206-218bd7ea-a4d0-4bcd-82aa-81f5006f6c48.png)
