### ISSUE TITLE
Support http_proxy env variable

### ISSUE THREAD

**Issue by patlachance** [openshift/console#1248]
Authentication fails if the openshift cluster's public endpoint is reachable only through an http proxy.

Error message on my environment:

2019/03/3 07:21:03 auth: unable to verify auth code with issuer: Post https://console.rh.hml.lab-nxtit.com:443/oauth/token:  net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

I tried configuring uppercase and lowercase environment variables http_proxy & https_proxy but it doesn't help. I looked at the cmd/bridge/main.go file and proxy isn't configured in the custom http.Transport.

**Comment by spadgett** [comment]
We're adding proxy support to the operator in https://github.com/openshift/console-operator/pull/254
