### ISSUE TITLE
Internal k8s proxy goes into broken state after high usage

### ISSUE THREAD

**Issue by djcass44** [openshift/console#12526]
Kubernetes version: `v1.24.8-eks-ffeb93d` (EKS on AWS), `v1.24.8+k3s1` (K3S on Bare metal)
OpenShift Console version: `4.13.0`, `4.12.0`

After extended usage, the console stops working. The Web UI shows a blank white screen or a "Bad Gateway" message and the server reports the following error:

```
http: proxy error: dial tcp 1.2.3.4:443: connect: cannot assign requested address
```

It shows this error over and over until a human restarts the deployment. The liveness probes to `/health` continue to succeed even though the pod is in a broken state.

The issue is present with version 4.13 and 4.12. I had used 4.12 without the issue for quite a while with no issues and suddenly it appeared when a newer version of the image was pulled.

I'll be testing older versions to see if there was an introduction point, however since it requires a decent amount of usage by human users that may take a while to confirm.

**Comment by huangkaoya** [comment]
Yes, we have encountered this issue as well. In fact, I think the bridge-based entry provided by OpenShift has poor performance.
