### ISSUE TITLE
Capacity Metrics in PVs and PVCs

### ISSUE THREAD

**Issue by AyushAmbastha** [openshift/console#1258]
Hi, 
I was trying to display the 'Available' space on the PV or PVC for which I need the amount of storage 'used'. Do I need to make an API call as that value isn't shown in the yaml file? 
How do I display this? @zherman0

**Comment by zherman0** [comment]
@AyushAmbastha - that is not currently a feature available from the API.  I believe we are developing a metrics page that does keep track of the space used but I don't fully recall.  Perhaps @spadgett can comment on this.

**Comment by spadgett** [comment]
@brancz do you know if pvc usage metrics are available in prometheus?

**Comment by brancz** [comment]
Unfortunately this is a bit fragmented in Kubernetes today. PVCs may have capacity and usage metrics, depending on the volume provider, and it seems that any CSI based volume doesn't have these at all. We can do this on a best effort basis but we'll very quickly hit cases where these metrics are not available.

We've already talked to sig storage about this, but as far as I know there have been no changes.

**Comment by cloudbehl** [comment]
FYI: The patch for exposing storage usage capacity is merged in k8s master. https://github.com/kubernetes/kubernetes/pull/76188
