### ISSUE TITLE
Incorrect position of edit icon near 'Default Pull Secret' in namespace dashboard

### ISSUE THREAD

**Issue by vrutkovs** [openshift/console#1260]
Firefox 66.0b12, didn't check if it happens in other browsers

4.0.0-0.7, console 24942e86dd5bef0b17c1e33bfcd386b450c49b19

1. Home -> Status
2. Switch to Dashboard
3. Scroll down to Details

![screenshot_2019-03-07 project status openshift container platform](https://user-images.githubusercontent.com/114501/53953290-3dc35780-40d3-11e9-95a2-ab3e7e0f1d82.png)

**Comment by sg00dwin** [comment]
I believe this pr https://github.com/openshift/console/pull/1251 will fix this issue.

**Comment by spadgett** [comment]
Fixed by #1251

/close

**Comment by vrutkovs** [comment]
Works perfectly now, thanks
