### ISSUE TITLE
Locales base path is not respected

### ISSUE THREAD

**Issue by davidpanic** [openshift/console#12671]
The console frontend does not respect the basePath when loading locales. I believe this is because of the following line:

https://github.com/openshift/console/blob/9ac23ec56263d23bf35fe1c71bf38b9220d944dc/frontend/public/i18n.js#L30

This results in 404 errors upon loading the UI:

![image](https://user-images.githubusercontent.com/13370323/226970830-6b18d786-9e7f-4da8-9d70-2e6c8ed6b716.png)

I have launched the console bridge with the argument `--base-path=/okd/`
This is not very urgent as it appears that the console is visually still fully functional.

**Comment by davidpanic** [comment]
/remove-lifecycle stale

Still an issue.

**Comment by davidpanic** [comment]
/remove-lifecycle stale

Still an issue.

**Comment by davidpanic** [comment]
/remove-lifecycle stale

Still an issue.

**Comment by davidpanic** [comment]
/remove-lifecycle stale

Still an issue.

**Comment by davidpanic** [comment]
/remove-lifecycle stale

Still an issue.

**Comment by logonoff** [comment]
good catch! i've opened a merge request #14046 to fix your issue--if merged, it may appear in a future release

cheers :smile:
