### ISSUE TITLE
[Feature] DeploymentConfig Back with resource limits form

### ISSUE THREAD

**Issue by Lasherbr** [openshift/console#1281]
Cluster Version: 4.0.0-0.7
Expected Behavior: The deployment config resouce limit edition should be done through a form like on 3.x. Directly on yaml its much more subject to errors.

**Comment by spadgett** [comment]
@christianvogt I know we've added a form for this when Importing from Git. Can you update resource limits for existing Deployment Configs?

**Comment by christianvogt** [comment]
@spadgett yes we have a form which can be used during import and when editing the imported application.

However this form is not available when simply editing a DC that was created through other means.

Something to consider @openshift/team-devconsole-ux

**Comment by beaumorley** [comment]
@serenamarie125 wondering if this is something we want to keep open. Example of forms that existing in 3.x that are no longer available. Which is what we hear from customers.
