### ISSUE TITLE
[Feature] Debug in Terminal option for pods in failed state

### ISSUE THREAD

**Issue by kevchu3** [openshift/console#1298]
The OpenShift 3.x web console previously had a Debug in Terminal option that spun up a separate Debug Container window with identical settings, changing the container's entrypoint to /bin/sh instead.  This option no longer appears in OpenShift 4.

**Comment by spadgett** [comment]
Thanks for the feedback. Note this is still possible using `oc debug`, although having it in the UI is nice.

**Comment by spadgett** [comment]
Just a quick note that we are still tracking this as a story, and it's on our backlog to implement.
