### ISSUE TITLE
docs: links are broken

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [openshift/console#13000]
# Bug

## Overview
https://www.npmjs.com/package/@openshift-console/dynamic-plugin-sdk
https://github.com/openshift/console/blob/0a320fe3c6589005726d21e26669d7aa94c7ba78/frontend/packages/console-dynamic-plugin-sdk/README.md?plain=1#L14-L18
<img width="770" alt="image" src="https://github.com/openshift/console/assets/20921177/bb3b7962-5438-4bb2-a714-1ef3e91934b6">
https://www.npmjs.com/package/@openshift-console/docs/console-extensions.md
<img width="549" alt="image" src="https://github.com/openshift/console/assets/20921177/8787757f-68c6-4ea6-ad9c-6d58b1fb5a93">

The links only work when used from Github

https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/README.md

## Fix

One way to fix it is to change links to use absolute URLs instead of relative.

**Comment by AryanSharma9917** [comment]
Hey @HarikrishnanBalagopal, do you mean to add `console-extension.md` as
https://github.com/openshift/console/blob/ffdd759f8f431a81be5f9b34a3290ef1b7e077ff/frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md

and `api.md` as
https://github.com/openshift/console/blob/ffdd759f8f431a81be5f9b34a3290ef1b7e077ff/frontend/packages/console-dynamic-plugin-sdk/docs/api.md
