### ISSUE TITLE
feat: add extension point for sidebar

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [openshift/console#13002]
# Feature Request

## Overview

While implementing an assistant in Openshift Console we ran into some limitations with the Dynamic Plugin Framework.
The features we needed were similar to Web Terminal/Cloud Shell so we decided to make it a Static Plugin instead. https://github.com/openshift/console/tree/master/frontend/packages/console-plugin-sdk
https://github.com/openshift/console/blob/0a320fe3c6589005726d21e26669d7aa94c7ba78/frontend/packages/webterminal-plugin/src/components/cloud-shell

```
Static plugins become part of the Console application during its webpack build. Their code is maintained as part of the frontend monorepo, built and released as an integral part of Console.
```
Obviously this isn't ideal and we would like to implement the same as a Dynamic Plugin in the future.

## Features Required

Please add some more extension points to the Dynamic Plugin Framework (or explain how the features below can be implemented with existing ones)
https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md

- Add an extension point for creating a custom sidebar. The sidebar should be openable from all the pages (overlay on top of everything, independent of the current page). Example: Need something similar to the Web Terminal/Cloud Shell (currently opens a drawer from the bottom) however this is done by integrating deeply with the console code as a static plugin https://github.com/openshift/console/blob/0a320fe3c6589005726d21e26669d7aa94c7ba78/frontend/packages/webterminal-plugin/src/components/cloud-shell/CloudShellDrawer.tsx
- Ability to know what page is currently being displayed and its contents.
    - Example 1: A YAML editor is on the current page, then the above sidebar needs access to the contents of the YAML editor and ability to edit the contents as well.
    - Example 2: If the Workloads > Pods tab is open then the sidebar needs to known the current pods that are being displayed.
- Ability to open the Web Terminal from the sidebar (by clicking a button) and put some command into the web terminal to be executed.

**Comment by TheRealJon** [comment]
Hi @HarikrishnanBalagopal! Thank you for your feature request. We appreciate your input. 

However, we have a different process for feature requests. We handle them through our Jira system, and to proceed, we kindly request that you contact our customer support team to open a Request for Enhancement (RFE).

You can reach our support team through our [customer portal](https://access.redhat.com/support/cases/new). They will guide you through the process and ensure your request is properly documented and reviewed. For more details on our RFE process, please see [this article](https://access.redhat.com/solutions/73513).

I am going to close this GitHub issue. If you have any questions or need assistance, please don't hesitate to reach out or comment again on this issue.
