### ISSUE TITLE
Typo in the OCP console menu

### ISSUE THREAD

**Issue by chetantiwary** [openshift/console#13054]
There is a typo in the OCP console menus. 
If you go to Workloads-> Deployments-> select deployment-> Edit Health Checks-> Edit Readiness Probe  - you will see for "Initial delay" it says "How long to wait after the Container starts before checking it's health."
"It's" is not the possessive of It, it should read "its health" .

correct sentence : **"How long to wait after the Container starts before checking _its health_"**

v4.12

**Comment by anilabhabaral** [comment]
I would like to take this. Please assign this to me.

**Comment by anilabhabaral** [comment]
@chetantiwary I have created this JIRA issue: https://issues.redhat.com/browse/CONSOLE-3737 to track the progress.

**Comment by TheRealJon** [comment]
Closing, as this is now tracked in the above Jira issue.
