### ISSUE TITLE
Swapped position of actionMenu and resource-icon

### ISSUE THREAD

**Issue by jhadvig** [openshift/console#135]
Often after creating a first instance of a specific resource(Service, Secret, Stateful Set, ... ) the position of the actionMenu and resource-icon is swapped. Even after the navigating to some other page and back to the resource List page the order is still swapped. Only after refreshing the page the order goes back to normal.
Swapped position:
![1](https://user-images.githubusercontent.com/1668218/41484492-56a10a34-70dd-11e8-83d8-86e90c36a3a9.png)

Normal position:
![2](https://user-images.githubusercontent.com/1668218/41484498-5f55bfb2-70dd-11e8-90e8-1bfdc257618e.png)

Also the size of the resource-icon is incorrect since it's bigger the the intended size.

**Comment by tlwu2013** [comment]
Thanks for picking this up. We also noticed this happened on the newly added "Routes" list view:
https://github.com/openshift/console/pull/126

**Comment by spadgett** [comment]
We could enable the console switcher on teamui since it's just an env var if we wanted.

I'd like to get a template working you can use with `oc cluster up` to test OpenShift resources

**Comment by spadgett** [comment]
We've noticed other problems with icon size too that goes away with a refresh. For instance:

![screen shot 2018-06-15 at 4 08 55 pm](https://user-images.githubusercontent.com/1167259/41487367-7ba44232-70b6-11e8-98cf-e20e25bcc183.png)
