### ISSUE TITLE
Sort naturally when possible in the metrics dashboard

### ISSUE THREAD

**Issue by fxierh** [openshift/console#13543]
It'd be great if we could sort naturally, i.e. sort strings that represent numbers in their numeric order, rather than lexicographical order, when possible. 

Currently this is not the case for the metrics dashboard:
![Example](https://github.com/openshift/console/assets/121010016/daaff461-2607-4d2f-86b0-5b45f91fbcde)

Additional info:
- Classic OpenShift 
- Version: 4.16.0

**Comment by spadgett** [comment]
/reopen
/remove-lifecycle rotten
/assign @jgbernalp 

We implemented something similar for other tables in #5322. This seems like a reasonable request.

**Comment by jgbernalp** [comment]
Created an issue to track it https://issues.redhat.com/browse/OU-481
