### ISSUE TITLE
ACM and MCE ConsolePlugins Failing

### ISSUE THREAD

**Issue by fawazsiddiqi** [openshift/console#13569]
Hello there, I am installing ACM (2.9.2) and MCE on an OpenShift 4.13 cluster, and when the installation is done, the console plugins for both seem to fail with the following error 

```
Failed to get a valid plugin manifest from /api/plugins/acm/
SyntaxError: The string did not match the expected pattern.
```

```
Failed to get a valid plugin manifest from /api/plugins/mce/
SyntaxError: The string did not match the expected pattern.
```

Any advice would be helpful 

Thanks! 

<img width="1252" alt="Screenshot 2024-02-02 at 2 25 03 AM" src="https://github.com/openshift/console/assets/39944853/b37aa7e8-13dd-4c8c-bf09-d2298303607c">

**Comment by fawazsiddiqi** [comment]
So I was just playing around with this, and after some discussions with my peers, I decided to try incognito mode on my browser. 

And to my surprise, the plugin reported healthy state, and I was able to access the ACM console. But if I refresh the tab, I lose access to the ACM console resulting in the same state as described in the issue.

**Comment by ckupe** [comment]
I have also noticed this issue on Openshift 4.14. All dynamic plugins get degraded errors. If I disable and enable them, they can sometimes temporarily work, but after a while they will degrade again.

**Comment by vupn38167** [comment]
Try to clear cache on ur browser, it should work

**Comment by fawazsiddiqi** [comment]
@vupn38167 it does, until I refresh the page and then it starts failing again.

**Comment by alexgdmx** [comment]
Same behavior 
<img width="1249" alt="Screenshot 2024-02-06 at 2 07 24 AM" src="https://github.com/openshift/console/assets/5082249/7ed8d31d-a241-40ef-b2a2-d65da8b8ecaf">

@vupn38167 Clear cache will not work, the regular navigation will change again to fail state. 

I suspect, you're calling the t function too early and are not waiting for the translations to be fully loaded.
`
vendors~main-chunk-fa66b5f55415df590be0.min.js:30874 react-i18next:: It seems you are still using the old wait option, you may migrate to the new useSuspense behaviour.
r @ vendors~main-chunk-fa66b5f55415df590be0.min.js:30874
`

**Comment by fawazsiddiqi** [comment]
@alexgdmx I think ODF never failed because it has a different level of integration with the console when compared to that of ACM and MCE

**Comment by fawazsiddiqi** [comment]
@spadgett Hey there! Hope you are doing well! Any insight on this issue at your end by any chance?


Thanks!

**Comment by KevinFCormier** [comment]
I think this should be addressed by https://issues.redhat.com/browse/OCPBUGS-28788

**Comment by geluyan** [comment]
Hitting the same issue with my own written Dynamic Plugin. When I disable cache, the plugin is ok after each page refresh. When I disable cache, it still works after the first page refresh but after the subsequent refreshes it is back into degraded mode.

OCP: 4.13.30

Didn't had the issue with OCP 4.13.12

**Comment by KevinFCormier** [comment]
Closing, as this repository is not used for issue tracking. Use https://issues.redhat.com, project ACM, component Console.

**Comment by fawazsiddiqi** [comment]
Closing as it seems to be resolved
