### ISSUE TITLE
Cannot create web-terminals as kubeadmin on OpenShift 4.15

### ISSUE THREAD

**Issue by AObuchow** [openshift/console#13696]
Prior to OCP 4.15, the OpenShift console expected the devworkspace's [`controller.devfile.io/creator` label](https://github.com/devfile/devworkspace-operator/blob/efe61286a3a7f4cf01b01b97ccb615bfa3cad61a/pkg/constants/metadata.go#L28-L29) to be set to an empty string when logged in to the cluster as kubeadmin due to https://github.com/openshift/origin/issues/24950. In essence, the kubeadmin user does not have a uid, and thus DevWorkspace-Operator sets the `controller.devfile.io/creator` label to an empty string when logged in as kubeadmin.

However, due to a recent [change](https://github.com/openshift/console/commit/e87dc6fc852d23e8fca211cd0d3862b07cefa79e) made to the OpenShift Console for 4.15, the OpenShift console is now expecting the `controller.devfile.io/creator` label to be set to kubeadmin's username, instead of its (empty string) uid, [resulting](https://github.com/openshift/console/blob/9d33deb84949ae36eb1a8fc8b89a5da859d3554f/pkg/terminal/proxy.go#L144-L147) in users not being able to access their web terminal instances when logged in as kubeadmin: "Error Loading OpenShift command line terminal: User is not a owner of the requested workspace".

Would it be possible to revert https://github.com/openshift/console/commit/e87dc6fc852d23e8fca211cd0d3862b07cefa79e? And how quickly (if at all) would this change land in OCP 4.15?

Here is the related [Web Terminal Operator bug](https://github.com/redhat-developer/web-terminal-operator/issues/162).

Thank you :)

**Comment by stlaz** [comment]
How come that you can interpret the same label sometimes as UID, sometimes as username? That appears as a clear design flaw.

It's not possible to revert https://github.com/openshift/console/commit/e87dc6fc852d23e8fca211cd0d3862b07cefa79e.

**Comment by stlaz** [comment]
https://github.com/openshift/console/commit/e87dc6fc852d23e8fca211cd0d3862b07cefa79e cannot be reverted. We'll need to see what else we can do.

**Comment by stlaz** [comment]
@sleshchenko which values do you set the `controller.devfile.io/creator` label to in a world where none of the users of the cluster have any UID, yet they are each different?

**Comment by ibuziuk** [comment]
@stlaz could you clarify why it can not be reverted and why it was implemented that way.
another topic is e2e tests - why https://github.com/openshift/console/pull/12922 has not been merged since mid 2023 that should have caught that problem earlier before the release cc: @musienko-maxim

**Comment by stlaz** [comment]
https://github.com/openshift/console/pull/13719#pullrequestreview-1976329813 has the clarification.
I don't know anything about any e2e tests, I'm not a member of the console team.

**Comment by AObuchow** [comment]
I've been working on resolving this issue on the [DevWorkspace Operator](https://github.com/devfile/devworkspace-operator/issues/1245#issuecomment-2080159160) side, and have made a few findings:
- Setting the `controller.devfile.io/creator` value to a [plain-text username](https://github.com/openshift/console/commit/e87dc6fc852d23e8fca211cd0d3862b07cefa79e) can result in an invalid Kubernetes label that does not comply with the [RFCs used](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names). This is problematic for the case of `kube:admin`, where the `:` is not accepted as a Kubernetes label value. 
    - Changes need to be made in how we store (on the DWO side) and retrieve (on the Console side) usernames in the `controller.devfile.io/creator`, perhaps through some agreed-upon encoding process.
-  The OpenShift Console's frontend is still [hard-coded ](https://github.com/openshift/console/blob/master/frontend/packages/webterminal-plugin/src/components/cloud-shell/useCloudShellWorkspace.ts#L62)to expect the `controller.devfile.io/creator` label to be an empty string `""` when kubeadmin creates a web terminal.
    - Changes will have to be made to the frontend in order to match the appropriate  `controller.devfile.io/creator` value when a username (instead of a UID) is used. 
    - For fixing the kubeadmin case alone, it'd be a matter of using the agreed-upon encoding process to use an encoded version of `kube:admin` as the label selector. 

If anyone has any input on my proposal, please share your thoughts.

**Comment by AObuchow** [comment]
This issue will be resolved once https://github.com/openshift/console/pull/14114 is merged.
