### ISSUE TITLE
Show suspend flag of CronJob

### ISSUE THREAD

**Issue by SpazzMarticus** [openshift/console#13811]
Currently both the list of CronJob resources and the detail page of a CronJob don't feature the `spec.suspend`-Flag. 

My "workaround" is to check the YAML-page of a CronJob, which is a bit tedious when it comes to a great number of CronJobs.

**Comment by Lucifergene** [comment]
Currently, we don't have a customized details page for cronjobs. We show a common format for the details page, therefore you don't see this special field.

Closing this for now. You can request for the feature later on.

/close
