### ISSUE TITLE
Consistent pattern of extremely slow downloads from quay.io causing test failures

### ISSUE THREAD

**Issue by ldimaggi** [openshift/console#1401]
Seeing this pattern consistently on running tests such as: [https://github.com/redhat-developer/devconsole-operator/pull/77] - when running tests locally on OS3 cluster and remotely on OS4 cluster. 

The problem sometimes results in tests timing out and sometimes in tests failing when deployments timeout - example: 
 
```
oc get pods
NAME READY STATUS RESTARTS AGE
catalog-operator-78bf9bfc46-zmmsq 1/1 Running 0 57m
my-catalog-slcb5 0/1 ImagePullBackOff 0 23m
olm-operator-86fc5b5c-snpzm 1/1 Running 0 57m
olm-operators-dvhpv 1/1 Running 0 1h
operatorhubio-catalog-k5f5d 1/1 Running 0 1h
packageserver-68ddbd56b7-kqtrh 1/1 Running 0 57m
packageserver-68ddbd56b7-lcfsh 1/1 Running 0 57m

oc logs my-catalog-slcb5
Error from server (BadRequest): container "registry-server" in pod "my-catalog-slcb5" is waiting to start: trying and failing to pull image
```

See:
https://jira.coreos.com/browse/ODC-470

**Comment by spadgett** [comment]
Sorry, I'm a little unclear what the issue is or how your CI is set up. It sounds like it's obsolete since the dev console no longer needs an operator. Is that correct, @ldimaggi ?

**Comment by ldimaggi** [comment]
This issue can be closed as obsolete - thanks!
