### ISSUE TITLE
Catalog sources and operators once imported are not sowing up reliably in UI

### ISSUE THREAD

**Issue by ldimaggi** [openshift/console#1402]
Seeing this pattern recently - and other people have mentioned the same:

In OS3, creating a new catalog source and subscription, either through the UI or the oc CLI, does not relably result in the created entities being reliably created and displayed in the console UI.

After creating and pushing the operator and its registry to quay.io, this command is run:

```
oc apply -f catsub.yaml 
catalogsource.operators.coreos.com/my-catalog created
subscription.operators.coreos.com/my-devconsole created
```

The subscription appears in the UI, but not the operator - see attached screenshots.

![Screenshot from 2019-04-08 15-44-41](https://user-images.githubusercontent.com/642621/55766816-590fe280-5a44-11e9-9a51-bc465356b6a5.png)
![Screenshot from 2019-04-08 15-32-59](https://user-images.githubusercontent.com/642621/55766817-590fe280-5a44-11e9-8fe5-b1d92e276880.png)

See: https://jira.coreos.com/browse/ODC-472

**Comment by spadgett** [comment]
Are there any network errors if you open browser developer tools?

Related to #1387

**Comment by spadgett** [comment]
cc @alecmerdler

**Comment by spadgett** [comment]
@ldimaggi Are you still seeing this issue? I know there were several Bugzilla bugs in this area that have since been fixed.

Do you see the CSV using the CLI? Are there any errors if you look at the Subscription or Install Plan?
