### ISSUE TITLE
Unmaintained image?

### ISSUE THREAD

**Issue by asaf400** [openshift/console#14088]
Hello, I've noticed that about 4 months ago, 
The public repository at: https://quay.io/repository/openshift/origin-console?tab=tags
Has stopped getting new builds published, for all tags, what is the reason for that?

Previously security vulnerabilities were fixed on daily basis, and the tags were mutable and overridden with new image hash

edit: reformat

**Comment by jsakil14** [comment]
I kind of lost access to web console , did you face this as well ? 

It just says I need to configure authentication to use web console
