### ISSUE TITLE
too many requests and consequent UI updates caused by watchAPIServices

### ISSUE THREAD

**Issue by suomiy** [openshift/console#1425]
WebSocket is started (`watchK8sList`) when watching APIServices (`watchAPIServices`) which on update dispatches the  `updateListFromWS` action which in turn calls the appropriate reducer.

Some APIService can change their resourceVersion very rapidly. The reducer has this check to prevent unnecessary updates:

```js
if (current.deleteIn(['metadata', 'resourceVersion']).equals(next.deleteIn(['metadata', 'resourceVersion']))) {
    // If the only thing that differs is resource version, don't fire an update.
    return list;
  }
```

Nevertheless `watchK8sList` also dispatches second `extraAction` `getResources`. There is no filtering applied to this second action (i.e. `resourceVersion` check). This can cause unnecessary invocation of   `getResources`. Which in turn can trigger other changes (e.g. featureReducer).

This fires unnecessary requests and can cause clogging the browser and possibly crash of the browser.

**Comment by spadgett** [comment]
Duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1697803

We're working on making this better, and we've added some throttling (with more changes coming).

It's a bug that APIServices are changing so often, however.  That problem is fixed by https://github.com/openshift/origin/pull/22425

**Comment by suomiy** [comment]
ok, thanks
