### ISSUE TITLE
Displayed time is not UTC+0 / cannot be set to UTC+0

### ISSUE THREAD

**Issue by Jiehong** [openshift/console#1436]
Hello,

Openshift seems to be displaying the date time in locale time zone, and there do not seem to have a way to display time as UTC+0 only (and maybe as ISO 3601 format, but that's another topic).

Indeed, having pods on different regions and tools all working in UTC+0, it's error prone to read date time in the console in the wrong time zone.

Note that the `oc` cli does not seem to suffer from this issue.

**Comment by spadgett** [comment]
You should be able to hover over the time to see the UTC timestamp.

**Comment by spadgett** [comment]
Example screenshot:

![Screen Shot 2019-04-16 at 1 24 46 PM](https://user-images.githubusercontent.com/1167259/56230807-08ebde00-604b-11e9-9361-f91480b7f2bc.png)

(Note this is the 4.x console.)

**Comment by spadgett** [comment]
It's unlikely we would change the default since most users want to see timestamps in their local time. Closing since UTC is available as a tooltip.

/close
