### ISSUE TITLE
It would be nice to have an ID on actions dropdown button on resource detail page

### ISSUE THREAD

**Issue by rhrazdil** [openshift/console#1492]
We could use having an ID on actions button on resource detail page for kubevirt-web-ui test automation.

As most buttons that open an dropdown already have an ID, it would improve our test consistency.

This is the html structure of the button in question:
![dropdown_element_structure](https://user-images.githubusercontent.com/32546791/56735323-6d9eeb00-6765-11e9-8f32-5b3e01ffc978.png)

Having an ID on the button element would allow us to access the button and the ul option list easily.

**Comment by spadgett** [comment]
Are these helpers in the view not sufficient?

https://github.com/openshift/console/blob/master/frontend/integration-tests/views/crud.view.ts#L116-L118

**Comment by rhrazdil** [comment]
These helper methods are of course sufficient to get to dropdown options. 
What I'm aiming for is a single consistent way how to manipulate with dropdowns across the UI.

**Comment by spadgett** [comment]
Action dropdowns or any dropdown? Many pages have more than one dropdown, so an ID wouldn't be unique.

**Comment by rhrazdil** [comment]
Any dropdown, as all dropdowns are implemented as <button> and <ul> sibling elements.
The button IDs would need to be unique of course

**Comment by christianvogt** [comment]
For testing we should look at adding `data-test-id` attributes to Dom nodes. They only need to be unique within a hierarchy of other `data-test-id`s. Better than using classes because classes are for styling and you may change styles without breaking tests. Html IDs must be globally unique so that is bad for creating standalone components.

**Comment by spadgett** [comment]
I'm reworking the actions in #1559 and adding data-test-ids

**Comment by spadgett** [comment]
#1559 added `data-test-id` and some updated helpers for actions.

/close
