### ISSUE TITLE
Copy Login Command shows invalid API url

### ISSUE THREAD

**Issue by siamaksade** [openshift/console#1561]
The oc login command under *? > Command Line Tools > _Copy Login Comman_* shows an internal URL which is not accessbile:

```
oc login --token=**** --server=https://api-int.NNNN.openshiftdemos.com:6443
```

The result is:
```
error: dial tcp: lookup api-int.NNNN.openshiftdemos.com on 10.0.2.3:53: no such host
```

The correct url is: `api.NNNN.openshiftdemos.com`

**Comment by spadgett** [comment]
Same as https://bugzilla.redhat.com/show_bug.cgi?id=1706689

This has since been fixed.

**Comment by tinakurian** [comment]
@spadgett has this been fixed in the UI as well? When creating a new openshift 4 cluster i still see the incorrect URL:

![image](https://user-images.githubusercontent.com/40298444/58108778-7050fc80-7bba-11e9-926a-ff35fc1a858c.png)

**Comment by spadgett** [comment]
Yes, what version do you have installed?

**Comment by spadgett** [comment]
```
$ oc get clusterversion version -o jsonpath='{.status.desired.version}'
```

**Comment by tinakurian** [comment]
> ```
> $ oc get clusterversion version -o jsonpath='{.status.desired.version}'
> ```

4.1.0-rc.1

**Comment by spadgett** [comment]
Yeah, `rc.1` doesn't contain the fix. I'd try a newer release candidate.
