### ISSUE TITLE
"Copy Login Command" for odo

### ISSUE THREAD

**Issue by kadel** [openshift/console#1572]
It would be great to have "Copy Login Command"  in `odo` section similarly to how it is done for `oc`.

<img width="599" alt="Screenshot 2019-05-15 at 14 31 35" src="https://user-images.githubusercontent.com/57206/57775824-34331d00-771e-11e9-9cbd-4b2550a2905f.png">

`odo` has the same login command as `oc`, so simply replacing command name (`oc --token ...` for `odo --token ...`) will work. 

It will be much more user-friendly if the user can just copy/paste the command.

**Comment by spadgett** [comment]
Currently, we're redirecting to the request token page from the OAuth server, although we plan to create one for console itself. We could add odo then.

@enj fyi
