### ISSUE TITLE
RFE: quick link back to current project view

### ISSUE THREAD

**Issue by jupierce** [openshift/console#1575]
It is often useful to dig down into resources of a given project X and then bounce back up to the full project view of X. Intuitively, I click on the project's name to do this, but that opens a drop down (which happens to be extremely long for me as cluster-reader and requires typing to filter). This can happen several times a minute so the context switch between the mouse and keyboard is costly.

Ideally, clicking the project name could take me back to the project view and clicking the chevron would lower the drop down. Alternatively, the current project should be place at the top of the otherwise alphabetically sorted list.

**Comment by spadgett** [comment]
The way you'd typically do this is to click "Status" again in the nav or use the browser back button. I think changing the dropdown behavior would be really confusing for users, and the chevron is a small click target. This would make the dropdown inconsistent with other dropdowns in the console, and clicking on the name vs chevron is a really subtle distinction. You can still get back in one click by clicking the nav item.

**Comment by jupierce** [comment]
Thanks @spadgett . "Status" does seem to do what I want, so this can be closed if desired. For my 2 cent contribution to usability: My intuition with the UI was that, since I was already looking at something like the status of a Pod, clicking "Status" again would not navigate away.
If the "Status" nav item was called "Project Status", I would have certainly tried it while looking around for a one-click solution.

**Comment by spadgett** [comment]
FWIW, we plan to restructure this menu some. I'm not sure if it would make this specific problem better or worse, though :)

cc @cshinn

**Comment by spadgett** [comment]
See https://github.com/openshift/openshift-origin-design/pull/167

**Comment by spadgett** [comment]
We've added breadcrumbs to the details pages in #1725. Project status is now a 
"Workloads" tab on the project details page.

/close
