### ISSUE TITLE
Sorting of CRD table is inconsistent

### ISSUE THREAD

**Issue by rhuss** [openshift/console#1605]
In version 4.1.0-rc.5 when listing the CRDs via "Administration - Custom Resource Definitions", one gets the following initial listing:

![grafik](https://user-images.githubusercontent.com/99080/58237833-5ba16f80-7d46-11e9-8906-12a19a646b60.png)

I.e. the table is sorted with the first column (NAME), ignoring case ("adapter" vs. "Aletermanager").

When now explicitly sorting after the name by pressing on the NAME column header, the column gets sorted, but with CRDs starting with upper-case letters first, while the CRDs with lower case letter come last:

![grafik](https://user-images.githubusercontent.com/99080/58238016-b89d2580-7d46-11e9-9808-3948a357a2f3.png)

I suggest that sorting via column header should also do a case insensitive sort. 

Whether the case of the "NAME" should be always starting with an upper-case is another question, because afaik the case for using any Kubernetes resources' kind doesn't matter at all (so the name could be always printed starting with an uppercase)

**Comment by spadgett** [comment]
The difference is that we're sorting on different fields. By default, we sort on `metadata.name`. When you click on the name column, we're actually sorting on `spec.names.kind`.

**Comment by spadgett** [comment]
#1606 updates the default sort to use `spec.names.kind`, same as the name column. I'd like to think more about whether to change to the default to case insensitive since that potentially affects all tables. For most fields in k8s, it's not an issue.

**Comment by rhuss** [comment]
Thanks ! Makes totally sense to use the same initial and column sorting (to avoid suprises like this). 

Tbh, I would be a bit suprised that I would find the lowercase names after the upercase names as typically names/kinds are used in a case insensitive fashion (every tool kike oc or kubectl doesn't care about the case). I was also suprised that istio uses lower case names for the CRDs, never has seen this before.
