### ISSUE TITLE
Launch console using docker image and disabled auth

### ISSUE THREAD

**Issue by cmoulliard** [openshift/console#1619]
## Question

Is it possible to launch the console using the docker image where we disable the auth, where we could specify the port to be used ?

```
kubectl run --image=quay.io/openshift/origin-console ocp4-console ....
```

**Comment by spadgett** [comment]
Yes, it's possible. All options can be specified as command-line flags or env variables. Is this native k8s or OpenShift?

You should look at the following files (for k8s or OpenShift respectively) as starting points:

https://github.com/openshift/console/blob/master/contrib/environment.sh
https://github.com/openshift/console/blob/master/contrib/oc-environment.sh

Use `--base-address` or `BRDIGE_BASE_ADDRESS` to change the port (for example, `http://0.0.0.0:8080`)

**Comment by spadgett** [comment]
Closing since this is possible today through command-line flags or env vars. Let us know if you need more help.

/close
