### ISSUE TITLE
Pod Log Links Extension

### ISSUE THREAD

**Issue by outcoldman** [openshift/console#1678]
In OpenShift 3.11 we could customize the Web Console with external scripts, one example is the script for creating links for external logging solution (example from the OpenShift docs https://docs.openshift.com/container-platform/3.11/install_config/web_console_customization.html#extension-option-for-external-logging-solutions), but with the OpenShift 4.1 I cannot find this option in the configuration https://github.com/openshift/console/blob/75d7f4ae9e0af0c9a42dc40b3a825a5739ebd141/cmd/bridge/config.go

Is it intentional? Or just a missing feature in 4.1? Any workarounds?

**Comment by spadgett** [comment]
We are looking at adding declarative, CRD based extensions in a future release. Some of the initial resources are in https://github.com/openshift/api/pull/318. For branding, we are adding it to the console config: https://github.com/openshift/api/pull/304. These changes didn't make 4.1, however.

Are there particular extension points you are looking for?

cc @alimobrem

**Comment by outcoldman** [comment]
@spadgett I would love to see exactly the same capability as in the example in my first comment, ability to add links to external logging/metrics solution. We used this extension capability to allow our customers easily access logs in Splunk https://blog.openshift.com/monitoring-openshift-health-and-application/

**Comment by DanyC97** [comment]
@spadgett i suspect this https://github.com/openshift/console-operator/pull/220 is needed too in addition to the PRs mentioned?

**Comment by spadgett** [comment]
For the links extension, you'd also need https://github.com/openshift/console-operator/pull/229 and #160. It doesn't yet have log links, but we should look at adding that back.

For custom logos, you'll need https://github.com/openshift/console-operator/pull/220.

**Comment by spadgett** [comment]
/assign @benjaminapetersen @rhamilto 

We should look at adding back external logging links. I was thinking we could make the URL a template, so we could inject pod name / namespace / uid using lodash templates:

https://lodash.com/docs/4.17.11#template

That way you can still use declarative CRDs to add the link. Something like

```yaml
location: 'PodLog'
text: 'View Archive'
template: https://example.com/logs?name=${name}&namespace=${namespace}
```

**Comment by benjaminapetersen** [comment]
In theory we could add `PodLog` as a location on the `ConsoleLink`, with an optional `HrefTemplate` prop, to use instead of `Href`.

**Comment by spadgett** [comment]
Right, it would be good to reuse the same CRD

**Comment by outcoldman** [comment]
Just an important note, I believe there are some customers, who use ELK + Splunk as well as log destinations, so they might want to have links to both solutions

**Comment by benjaminapetersen** [comment]
That would be fine, with the in-progress CRD based solution (if we add the `HrefTemplate` option), both could be added as 2 instances of a ConsoleLink CRD.

**Comment by spadgett** [comment]
cc @jcantrill

**Comment by jcantrill** [comment]
One point I would add that is likely to cause users to open bugs because in 3.11 we made efforts to link a user to a query based on their pod and namespace.  There was additional logic for that link based on if they were ops logs or if you were an ops user.  I don't see how this solution will allow that and best we can offer is to link users to the application and user's will need to understand how to use the log visualization ui

**Comment by spadgett** [comment]
Yeah, I was thinking about this since I made my initial proposal. Would it work if we also provided some kind of ns filter to choose what namespaces a particular pod log link includes?

We might have to make this a separate CRD if it diverges too much from `ConsoleLink`

**Comment by benjaminapetersen** [comment]
Yeah, that old link was a bit gnarly.

**Comment by rhamilto** [comment]
> Yeah, I was thinking about this since I made my initial proposal. Would it work if we also provided some kind of ns filter to choose what namespaces a particular pod log link includes?

Somthing like  `namespaceFilter: ^openshift-`?

@jcantrill, will a solution like this cover your use case?

> We might have to make this a separate CRD if it diverges too much from `ConsoleLink`

After discussing this in person with @spadgett and @benjaminapetersen, it will be a separate CRD.

**Comment by jeffspahr** [comment]
Linking an RFE from the old origin-web-console:
https://github.com/openshift/origin-web-console/issues/3092

Sam's notes here would meet our needs:
https://github.com/openshift/console/issues/1678#issuecomment-500412623
