### ISSUE TITLE
Convert detail lists to PF4 tables

### ISSUE THREAD

**Issue by priley86** [openshift/console#1986]
Just an initial issue to start gathering notes around PF4 Detail table conversion.

Noted detail views so far (carryover from #1465):
- [ ] Cluster Settings (cluster-settings.tsx)
- [ ] k8s-resource.tsx
- [ ] oauth.tsx
- [ ] webhooks.tsx
- [ ] container.tsx
- [ ] chargeback.tsx
- [ ] ingress.jsx
- [ ] pod.tsx
- [ ] package-manifest.tsx
- [ ] container-table.tsx
- [ ] endpoints.tsx
- [ ] routes.tsx
- [ ] volumes-table.tsx

Sample conversion started (sorting t.b.d./some design still t.b.d.):
https://github.com/priley86/web-ui/commit/5514f3fd770101aaf2c7ac436dcecb7a47145aaa

**Comment by spadgett** [comment]
#1891 converts the volumes table

**Comment by spadgett** [comment]
also image-stream.tsx here: https://github.com/openshift/console/blob/master/frontend/public/components/image-stream.tsx#L184-L201
