### ISSUE TITLE
Unable to provision an OpenShift template from UI, when the CustomResource object in the OpenShift template has  "spec.template" as a property defined

### ISSUE THREAD

**Issue by sharafcmr** [openshift/console#2136]
Unable to provision an OpenShift template from UI, when the CustomResource object in the OpenShift template has  "spec.template" as a property defined

**Describe the bug**
Provisioning a cluster from OpenShift console is not proceeding after you click "create" button when you have "template" property(eg: Kafkaconnects2i.spec.template.pod.labels) defined in Kafkamirrormaker, Kafkaconnect or Kafkaconnects2i OpenShift templates. Provisioning works fine via oc process command.

**To Reproduce**

Create a Kafkaconnect/kafkamirrormaker/kafkaconnects2i template with custom pod/deployment/statefulset option which has template parameter configured in the CR object to add a label

Refer https://github.com/strimzi/strimzi-kafka-operator/issues/1831 for an example template

Provision a kafkaconnects2i instance using above created template from UI. After clicking create button in the template provisioning window, it wont proceed to the creation of custom resource. Even after clicking "create" button multiple times, the provisioning window will still remain in the same stage.
See error
**Expected behavior**
It was expected to create a kafkaconnects2i custom resource and start a kafka connect pod

**Environment** 

Strimzi version: 0.11.1-AMQ Streams 1.1.1
Kubernetes cluster: OpenShift 3.11
Infrastructure: GCP
Additional context

Provisioning succeeds when i use oc process command using the same template

**Comment by spadgett** [comment]
@sharafcmr 3.11 console bugs should probably be reported at openshift/origin-web-console.

So you click the button and nothing happens? Can you open the JavaScript developer console for your browser and see if there are any runtime errors?

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools

/kind bug

**Comment by sharafcmr** [comment]
Here is the error which i received in the console
```
Error: e.spec is undefined
h@https://ocp-master.example.com/console/scripts/scripts.js:3761:1
b@https://ocp-master.example.com/console/scripts/scripts.js:3772:9
S@https://ocp-master.example.com/console/scripts/scripts.js:3793:69
R/<@https://ocp-master.example.com/console/scripts/scripts.js:3852:9
n@https://ocp-master.example.com/console/scripts/vendor.js:26954:66
Io@https://ocp-master.example.com/console/scripts/vendor.js:28653:24
R@https://ocp-master.example.com/console/scripts/scripts.js:3851:20
getLatestQuotaAlerts/<@https://ocp-master.example.com/console/scripts/scripts.js:3903:14
s@https://ocp-master.example.com/console/scripts/vendor.js:5977:18
l/<@https://ocp-master.example.com/console/scripts/vendor.js:5985:1
$eval@https://ocp-master.example.com/console/scripts/vendor.js:6283:12
$digest@https://ocp-master.example.com/console/scripts/vendor.js:6239:18
$apply@https://ocp-master.example.com/console/scripts/vendor.js:6309:3
p/<@https://ocp-master.example.com/console/scripts/vendor.js:5302:104
w@https://ocp-master.example.com/console/scripts/vendor.js:5366:36
Dt/</x.onload@https://ocp-master.example.com/console/scripts/vendor.js:5377:65
vendor.js:5659:7
    o https://ocp-master.example.com/console/scripts/vendor.js:5659
    get https://ocp-master.example.com/console/scripts/vendor.js:5105
    s https://ocp-master.example.com/console/scripts/vendor.js:5979
    l https://ocp-master.example.com/console/scripts/vendor.js:5985
    $eval https://ocp-master.example.com/console/scripts/vendor.js:6283
    $digest https://ocp-master.example.com/console/scripts/vendor.js:6239
    $apply https://ocp-master.example.com/console/scripts/vendor.js:6309
    p https://ocp-master.example.com/console/scripts/vendor.js:5302
    w https://ocp-master.example.com/console/scripts/vendor.js:5366
    onload https://ocp-master.example.com/console/scripts/vendor.js:5377
```

**Comment by spadgett** [comment]
@sharafcmr I see the problem. We're incorrectly assuming a resource with `spec.template` is a k8s workload and trying to check if you have quota. We access `spec.template.spec` without a null check.

**Comment by spadgett** [comment]
Fix in https://github.com/openshift/origin-web-console/pull/3140

Bugzilla bug: https://bugzilla.redhat.com/show_bug.cgi?id=1733806

**Comment by spadgett** [comment]
Note this is only a problem in 3.x, not in 4.x
