### ISSUE TITLE
Fix NooBaa capacity card logic

### ISSUE THREAD

**Issue by aruniiird** [openshift/console#2145]
According the [NooBaa doc](https://docs.google.com/document/d/15lugKm-ljNIJiDRfKBhnHWNwdqrF04dPw5cgDZ93-UA/edit#heading=h.jxj6d3pghiuz),  we should be collecting top N (where N=6 here) items excluding the 'Others' label and then append the 'Others' label at the end.

**Comment by spadgett** [comment]
Fixed by #2146

/close
