### ISSUE TITLE
Resource dropdown text overlaps with caret.

### ISSUE THREAD

**Issue by jcaianirh** [openshift/console#220]
In the Environment Page or the Create Role Binding page, the resource dropdown text can overlap the caret symbol. 

![resourcecaret](https://user-images.githubusercontent.com/35978579/42539259-9b2c6678-8468-11e8-8ec4-0db99c8cef0d.png)

**Comment by spadgett** [comment]
cc @sg00dwin @rhamilto

**Comment by sg00dwin** [comment]
note that Role binding form has same issue. 
<img width="533" alt="screen shot 2018-07-24 at 10 44 17 am" src="https://user-images.githubusercontent.com/1874151/43146335-08f5b53a-8f2f-11e8-869d-29f092fd1c03.png">

**Comment by jcaianirh** [comment]
@sg00dwin role binding is in the description of the issue.
