### ISSUE TITLE
Use only a single version of lodash

### ISSUE THREAD

**Issue by redallen** [openshift/console#2381]
Even with `yarn` hoisting, we have 4 versions of lodash/lodash-es that could likely be reduced down to one newer CJS `lodash`. The larger lodashes are in `@patternfly/react-charts` (where Victory uses the entirety of `lodash`), `kubevirt-web-ui-components`, `patternfly-react`, and `@console/*`.

There are some [tools](https://survivejs.com/webpack/optimizing/build-analysis/#duplication-analysis) to help narrow down these lodash versions. Once investigated it shouldn't be much trouble to test.

**Comment by spadgett** [comment]
cc @alecmerdler @vojtechszocs @dgutride

**Comment by redallen** [comment]
On the patternfly side we've pinned lodash to `"lodash": "^4.17.19",`. It looks like Openshift still has mixed versions of lodash and lodash-es: 
![image](https://user-images.githubusercontent.com/47335686/93475973-40f1f300-f8c7-11ea-9bf4-8dfce97efcdc.png)
