### ISSUE TITLE
openshift-console ignores no_proxy list and cant connect to the kubernetes endpoint

### ISSUE THREAD

**Issue by Rikbruggink** [openshift/console#2435]
openshift console 4.2 ignores no_proxy list .

# release info

console                                      sha256:0cf9ed306abffac465ede431976394a378cc374c01c2f0c8280c06637049a264
  console-operator                              sha256:b1a6553595d696ba86d764bb93c0c8c5a077cf626642f3a1f763d5312c5ab4b3

**Comment by spadgett** [comment]
This is tracked by https://bugzilla.redhat.com/show_bug.cgi?id=1743455

/close
