### ISSUE TITLE
High CPU consumption

### ISSUE THREAD

**Issue by e-minguez** [openshift/console#2489]
I've observed high cpu consumption when leaving the tab opened in the background in this scenario:

- OCP4 deployed
- CNV deployed
- OCS deployed but only persistent storage available (no object storage)

I believe is because there are a lot of queries in the background (triggering the dev-console in firefox shows a bunch of them) that doesn't give results back.

**Comment by spadgett** [comment]
What page are you on? Home -> Dashboard?

cc @rawagner

**Comment by spadgett** [comment]
This could be related to https://github.com/openshift/console/pull/2804/commits/d639a006f56f847148f59655100816c26c11cf0c

@e-minguez can you tell us exactly which page and tab you were on?
