### ISSUE TITLE
StorageCluster CR needs to be fixed for OCS installer for Bare-metal Deployments.

### ISSUE THREAD

**Issue by anmolsachan** [openshift/console#2549]
Current CR for StorageCLuster differs from https://github.com/openshift/ocs-operator/blob/1b5961f06f4ad0d03227312f0d7b2ccb8e7ec1f9/deploy/crds/ocs_v1alpha1_storagecluster_cr.yaml#L8 . It needs to fixed.

**Comment by spadgett** [comment]
Fixed by #2548

/close
