### ISSUE TITLE
Allow grouping field in CR view

### ISSUE THREAD

**Issue by ctron** [openshift/console#2619]
Using the `specDescriptors` in a CSV, it is possible to contribute details to the overview screen of a CR.

However, adding multiple fields there clutters the view, and doesn't provide much help to the user. I think it would be good to be able to "group" fields, and also visually align them. Maybe even split them off using something like tabs.

**Comment by spadgett** [comment]
cc @alecmerdler 
/kind feature

**Comment by alecmerdler** [comment]
We've added a [`fieldGroup` capability](https://github.com/openshift/console/blob/master/frontend/public/components/operator-lifecycle-manager/descriptors/types.ts#L22) which is currently used to [group related fields in the "Create Operand" form](https://github.com/openshift/console/blob/master/frontend/public/components/operator-lifecycle-manager/create-operand.tsx#L437). Implementing this in the details view should be possible.

**Comment by spadgett** [comment]
We've added some level of grouping in #6103 and #6178. @ctron Is this what you were thinking of?

cc @TheRealJon @tlwu2013 
/remove-lifecycle stale

**Comment by spadgett** [comment]
This is available in 4.6.

/close
