### ISSUE TITLE
Provide a "boolean" status descriptor

### ISSUE THREAD

**Issue by ctron** [openshift/console#2620]
Currently showing a boolean value in a status descriptor (defined in a CSV) you can only use "text". Whereas in the "spec" section, you have a "boolean switch" and a "checkbox" available.

I think it would make sense to add a boolean status indicator for the status as well.

**Comment by ctron** [comment]
It also looks like the "text" type doesn't work with a boolean. It only shows "None". I guess this is due to the fact that the value is of type boolean, and not string.

**Comment by spadgett** [comment]
cc @alecmerdler 

/kind feature

**Comment by spadgett** [comment]
cc @TheRealJon @tlwu2013
