### ISSUE TITLE
Appreciable Delay for Logs to Start Streaming via 4.2 Web Console for Pipelines

### ISSUE THREAD

**Issue by danielhelfand** [openshift/console#2636]
#2499 Introduced improvements for viewing the logs of an OpenShift Pipelines pipeline run. In using this new feature, I have noticed an appreciable delay of several minutes for logs to actually start appearing via the **Logs** section of the **Pipelines** tab.

I am using the 4.2 Web Console as part of an OpenShift workshop found [here](https://github.com/openshift-labs/lab-tekton-pipelines). The tutorial shows users how to create a pipeline and use it to deploy an application to OpenShift. 

The pipeline used is simple (i.e. a build task and a deploy task). Resources used are outlined below:
* [Pipeline](https://github.com/openshift-labs/lab-tekton-pipelines/blob/master/code/exercise/deploy-pipeline.yaml)
* [Build Task](https://github.com/openshift-labs/lab-tekton-pipelines/blob/master/code/tektontasks/s2i-nodejs-task.yaml)
* [Deploy Task](https://github.com/openshift-labs/lab-tekton-pipelines/blob/master/code/tektontasks/openshift-client-task.yaml)

Photos showing difference of how far along logs are via the Tekton CLI versus the web console are shown below:

**OpenShift Web Console**

![image](https://user-images.githubusercontent.com/34258252/64497554-e322d800-d27c-11e9-8d38-15e2cf374107.png)

**Tekton CLI Logs**

![image](https://user-images.githubusercontent.com/34258252/64497562-f59d1180-d27c-11e9-8216-8a21cbf9bd1f.png)

The web console does eventually start streaming in logs as expected that is in sync with the Tekton CLI, but it takes up until roughly the end of the first task (i.e. Build). 

Please let me know if there's any other information you would like from me. Thanks!

**Comment by spadgett** [comment]
cc @christianvogt

**Comment by christianvogt** [comment]
cc @abhinandan13jan

**Comment by abhinandan13jan** [comment]
----------------------------------------------------------------------------------------------
@christianvogt  @spadgett The delay is introduced at the `ResourceLog` component level on admin side. Any delay introduced could be most likely from the `wsFactory` utility functions or the response from server. The `ResourceLog` component is used by the Pipeline/Tekton Logs to render the referred view alike `PodLog` component. It takes exactly the same time as the `PodLogs` to load the `TektonLogs` out by using the related Pod for a running Pipeline. 
![Screencast from 09-09-2019 09_16_44 PM](https://user-images.githubusercontent.com/24852534/64547053-73c6ea00-d349-11e9-97f6-8828cd9d5e7d.gif)
![Screencast from 09-09-2019 09_17_53 PM](https://user-images.githubusercontent.com/24852534/64547055-745f8080-d349-11e9-9f47-1bcfd3501c31.gif)
![Screencast from 09-09-2019 09_18_25 PM](https://user-images.githubusercontent.com/24852534/64547054-73c6ea00-d349-11e9-8415-49c4be8f592d.gif)
------------------------------------------------------------------------------------------------
P.S: It loads almost instantly for failed Pipelines (which is not in execution anymore) and is the ideal case for the user to check the related Logs. 
![Screencast from 09-09-2019 09_19_47 PM](https://user-images.githubusercontent.com/24852534/64547056-745f8080-d349-11e9-85d4-62f1ec520537.gif)

**Comment by abhinandan13jan** [comment]
the actual elapsed time for each task
![Screenshot from 2019-09-09 21-43-54](https://user-images.githubusercontent.com/24852534/64547809-0ddb6200-d34b-11e9-8b79-06852a545970.png)

**Comment by christianvogt** [comment]
We have done some improvements to the web logs since this issue was first opened.
I just tested the tkn cli against the dev-console and both streamed the logs at the same time.
