### ISSUE TITLE
Error on UI showing an over hundred percentage on VMs vs Pods tab

### ISSUE THREAD

**Issue by jparrill** [openshift/console#2738]
Hi there,

We've been testing to disconnect a `/dev/vda` from one of the masters, this `vda` was part of the Ceph cluster created by OCS deployment. The facts are like this:

00:00:20 - Disconnect VDA from master-1
00:01:12 - openshift-storage health is degraded in UI
00:01:31 - Rebuilding in Progress 0.0%
00:01:59 - Disk device /dev/dm-0 not responding, on host master-1.
00:02:09 - rook-ceph-osd-0-6bc6687657-wlb96 pod on CrashLoopBackOff
00:04:22 - Still 0% on Rebuilding in Progress on UI

```
HEALTH_WARN 1 osds down; 1 host (1 osds) down; Degraded data redundancy: 448/1344 objects degraded (33.333%), 14 pgs degraded, 32 pgs undersized; too few PGs per OSD (21 < min 30)
```

00:06:19 - VMs on that node still accesibles and is using Ceph cluster
00:11:14 - Message on `ceph -w` command
```
2019-09-17 11:11:27.345668 mon.a [INF] Marking osd.0 out (has been down for 602 seconds)
2019-09-17 11:11:27.346001 mon.a [INF] Health check cleared: OSD_DOWN (was: 1 osds down)
2019-09-17 11:11:27.346071 mon.a [INF] Health check cleared: OSD_HOST_DOWN (was: 1 host (1 osds) down)
2019-09-17 11:11:28.403599 mon.a [INF] Health check cleared: TOO_FEW_PGS (was: too few PGs per OSD (21 < min 30))
```
00:12:21 - On the UI
```
Disk device /dev/dm-0 not accessible on host master-1.
Storage cluster is in warning state for more than 10m.
```

00:13:27 - Error on UI showing a bad percentage (used 1230%)

![2019-09-17_13-14](https://user-images.githubusercontent.com/1569950/65048133-f102e800-d963-11e9-8e34-a23662c14fb4.png)

As you could see the error happens when 1 disk of ceph could not be reached and the cluster is in bad shape.

**Comment by spadgett** [comment]
cc @rawagner

**Comment by rawagner** [comment]
@cloudbehl please take a look

**Comment by afreen23** [comment]
This chart is no longer supported. Its dropped after 4.2 release.
Hence closing this issue.

/close
