### ISSUE TITLE
Running install_knative_serving_mocks.sh in shell window with default profile results in unreadable text

### ISSUE THREAD

**Issue by ldimaggi** [openshift/console#2820]
Steps to recreate:

Running the script - frontend/packages/knative-plugin/yamls/knative-serving/install_knative_serving_mocks.sh - in a shell window with a white background and black text results in output that is unreadable:

![cannot_see_text](https://user-images.githubusercontent.com/642621/65512745-d66ec880-dea7-11e9-978f-22dfe19ab9fa.png)

**Comment by christianvogt** [comment]
cc @invincibleJai

**Comment by invincibleJai** [comment]
`install_knative_serving_mocks.sh` is no more needed post-release of 0.1.2 Openshift serverless operators and `install_knative_serving_mocks.sh` has been removed. 

https://github.com/openshift/console/tree/master/frontend/packages/knative-plugin

Can we close this?
