### ISSUE TITLE
Customizing Monitoring External links on interface

### ISSUE THREAD

**Issue by eitchugo** [openshift/console#2825]
Hi there,

Is there any way to customize the external links in the navigation menu under item "Monitoring"? I didn't find any option in the ConsoleConfig resource, and by looking at the code, I think it's generated by querying the routes under the 'openshift-monitoring' project (I'm not certain about it, please correct me if I'm wrong).

Use case here is that I have a custom domain for prometheus/alertmanager/grafana and had to create alternate routes to them, instead of using the default (cluster-monitoring does not allow changing app domains).

Currently using 3.11.

What I'm thinking is something like the web-console customization, i.e. `consolePublicURL`, `loggingPublicURL` values in the ConfigMap.

**Comment by spadgett** [comment]
It's not currently possible unfortunately.

We do let you contribute to the application launcher menu in 4.2 using a `ConsoleLink` CRD, but this won't replace what's in the left nav.

**Comment by liqlin2015** [comment]
@spadgett Do you know if there is plan to support such case in a CRD?

I see the OCP 3.11 doc step https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/configuring_clusters/install-config-web-console-customization#web-console-project-left-navigation. Can this be applied to OCP 4.2 too to get the same result?

**Comment by spadgett** [comment]
> @spadgett Do you know if there is plan to support such case in a CRD?
> 
> I see the OCP 3.11 doc step https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/configuring_clusters/install-config-web-console-customization#web-console-project-left-navigation. Can this be applied to OCP 4.2 too to get the same result?

We don't have any plans in the near-term to make the left nav customizable via a CRD. Currently, the links in the masthead, user menu, help menu, and project dashboards are customizable. The steps from the 3.11 doc won't work for 4.x.

Note that in recent releases, we've implemented native experiences for metrics and dashboards, so these are no longer link out to Prometheus/Grafana. They link to internal console pages.

We are looking at a pinning mechanism that would let individual users add items to their own nav.
