### ISSUE TITLE
Ability to Specify Service Account for Pipeline Run via Pipelines View

### ISSUE THREAD

**Issue by danielhelfand** [openshift/console#2955]
Currently, the start pipeline option allows an end user to specify pipeline resources, but it doesn't allow a user to specify a service account for the pipeline run as shown below:

![image](https://user-images.githubusercontent.com/34258252/66599747-fb369180-eb71-11e9-8b3d-1d9168c20ac1.png)

This option exists with the Tekton CLI (`tkn`), but does not appear to exist via the web console.  It would be helpful to include a service account option as part of the start wizard in the photo above. This would allow the user to add a service account for a pipeline run.

**Comment by christianvogt** [comment]
The decision was made to exclude the service account from the UI and wait for tekton to provide a default: https://github.com/tektoncd/pipeline/pull/1227

cc @serenamarie125  @siamaksade

**Comment by danielhelfand** [comment]
@christianvogt Thanks for the clarification. Will this be available for OpenShift 4.2 then, or is there a way we are recommending users set up pipelines to avoid a scenario where a user triggers a pipeline through the UI without somehow specifying a service account?

**Comment by siamaksade** [comment]
@danielhelfand it will be available on OCP 4.2. It's already merged upstream and will be available in OpenShift Pipelines 0.8.

**Comment by danielhelfand** [comment]
Thanks @siamaksade. My misunderstanding. Unless there is some use case for using a different service account with pipelines besides the default, I think this can be closed.
