### ISSUE TITLE
Dashboard Top Consumers card should point to in-console monitoring page

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/console#3036]
Since we now have the Metrics/Monitoring page in the console, the "view more" link on the Top Consumers card should probably point to that page (with the appropriate query applied) rather than linking out to Prometheus. 

cc @cshinn 

![Screen Shot 2019-10-21 at 4 16 30 PM](https://user-images.githubusercontent.com/8974593/67239865-33fe2280-f41e-11e9-85b9-39be26f7f492.png)

**Comment by cshinn** [comment]
This is actually the case for every graph in the console. Ideally they'd open the same link on the "Monitoring > Metrics" page. In this case, we'd also want to remove the time range from the query as well so that we can display the graph and show more information.

**Comment by kyoto** [comment]
FYI @rawagner

**Comment by spadgett** [comment]
Fixed by #3132
