### ISSUE TITLE
Instances of Clusterwide CRDs are not displayed properly in InstalledOperators

### ISSUE THREAD

**Issue by nikhil-thomas** [openshift/console#3040]
## Bug Report

**What did you do?**
Installed `openshift-pipelines-operator` which provides a clusterwide CRD
the went to 
`Installed Operator` > `OpenShift Pipelines Operator` 
click on `OpenShift Pipelines Config` tab

wait until an instance with name `cluster` appears
(openshift-pipelines-operator controller creates an instance of its clusterwide CRD automatically)

**What did you expect to see?**
UI where I could list the clusterwide CRD instances

**What did you see instead? Under which circumstances?**
`undefined`, `404`

![olm-clusterwide-1](https://user-images.githubusercontent.com/3650655/67274254-b00b6f80-f4dd-11e9-9abe-0e00e490a7b9.png)
![olm-clusterwide-2](https://user-images.githubusercontent.com/3650655/67274255-b0a40600-f4dd-11e9-878e-deb74c251db8.png)
![olm-clusterwide-3](https://user-images.githubusercontent.com/3650655/67274257-b0a40600-f4dd-11e9-982e-d13791d79a4e.png)

**Comment by spadgett** [comment]
Fixed by #3477

/close
