### ISSUE TITLE
Can only see a couple pod rows when there are a lot of labels

### ISSUE THREAD

**Issue by spadgett** [openshift/console#338]
@openshift/team-ux-review @robszumski @rhamilto @sg00dwin @alecmerdler 

We've talked about this before, but can we consider removing labels as a row in the pod list? Here is an example from a real cluster where I can only see two rows in a fairly large browser window.

Would a column like "Owner" be better here anyway?

![screen shot 2018-07-24 at 5 45 13 pm](https://user-images.githubusercontent.com/1167259/43409152-26b69f3c-93f1-11e8-921e-e591918b655d.png)

**Comment by beanh66** [comment]
@spadgett I thought based on the previous requests regarding labels, we may want to keep these columns and keep the Edit Labels action available too.  I know we talked about doing that and went back and forth on it a bit. Wondering if we can keep labels as a column on all summary pages for consistency, but when there are more then 3 maybe having them fade out and only showing the rest on detail views, or use a show more/ show less link so they don't take up so much vertical space.

**Comment by serenamarie125** [comment]
@spadgett is this another item we could get feedback on at DevCon?  both around use cases & possible alternatives

I'm curious as to what the use case is here ... are they looking at the labels of a specific resource and possibly navigating to it?  Or do they want to see all labels of all resources at the same time to compare?

Assuming the former, I think there are a number of design alternatives, in addition to what @jhadvig mentioned
- include an icon when labels exist, clicking on the icon could provide an infotip showing the labels ( thus these could still be clicked )
- include a column showing the number of labels, clicking on the icon could provide an infotip showing the labels ( thus these could still be clicked )

**Comment by sg00dwin** [comment]
Another option is to make them visible within a expanded row state. We currently do that on the Nodes list view, although it's either all rows expanded or all collapsed.

In column format the label text is usually truncated so much that they are unreadable.  And being able to sort by label doesn't seem to be of much value.

<img width="365" alt="screen shot 2018-08-02 at 3 48 26 pm" src="https://user-images.githubusercontent.com/1874151/43607645-cb433362-966c-11e8-9b61-a265e11f2f91.png">

**Comment by robszumski** [comment]
I had a design a long time ago that moved all labels into an expanded row state, with them flowing across the full row since they tend to be both long and numerous in practice. Food for thought.

![6 2__dc__manage-cluster-registry___expanded 2x](https://user-images.githubusercontent.com/755540/43670150-b61dd948-973d-11e8-9f85-1a0614a368b5.png)

**Comment by beanh66** [comment]
@robszumski @spadgett @openshift/team-ux-review Brainstorming on a few more ideas that would collapse some of the longer label rows but still maintain the column format. Thoughts on any of these below? 
![expand-1](https://user-images.githubusercontent.com/18057044/43921933-3902b0a2-9beb-11e8-8f40-30f4beb1cf92.png)
![expant-2](https://user-images.githubusercontent.com/18057044/43921936-3930f66a-9beb-11e8-923e-43be74cbc13b.png)
![expand-3](https://user-images.githubusercontent.com/18057044/43921934-391706c4-9beb-11e8-81ae-5cc028b54327.png)
![expand-4](https://user-images.githubusercontent.com/18057044/43921935-392255ec-9beb-11e8-8220-e0fcbef451a3.png)

**Comment by robszumski** [comment]
I like the "3 more..." most but as the trend to programmatically generate these increases, I lean towards removing them all together and only show on the detail page + the search page, where you can actually do a label query.

**Comment by sspeiche** [comment]
Like like options 4 and 3. One other thing is if we had a way to not show "advanced" items by default, like there is the compact and expanded forms. If we had the concept of "primary" or inversely "extra" labels, we could treat them with the right priority.

**Comment by serenamarie125** [comment]
If we had a compact view, I'd suggest that the tag column just show the number of labels with an associated infotip (similar to option 4).  Then we could have an expanded view which showed all the labels.

**Comment by beanh66** [comment]
@spadgett @sspeiche @robszumski Thanks for the input thus far! Final question in my mind is do you think it's important to allow users to filter by label on the resource summary pages (Deployments, Pods, Stateful Sets, etc.)? 

My thought is either, (1) we need to allow filter by label, so we should show labels to some extent (maybe with the "more" link) or (2) we do not need to allow filter by label, so we drop the column on all detail pages. 

Maybe there is a (3) where SOME specific summary pages require filtering by label, in which case we show the column just for those resource types. Thoughts?

**Comment by sspeiche** [comment]
@beanh66 filter by labels in this context is useful not doubt, though I'd need to better understand what is lost. App labels would be a primary label to filter on. 

@spadgett I'd be interested your ranked list of things you'd see users needing before labels are shown.

I'm in favor of keeping things slim for now and gradually add things one we are down to a single code base.

**Comment by spadgett** [comment]
I have a WIP PR #1536 that adds memory and CPU usage to the pod list. Thoughts? To me, this is way more useful than labels.

Incidentally, working on this helped me catch a real memory link prior to 4.1. Having the memory usage just there in the list makes it easy to notice problems you'd otherwise have to go looking for.

If we still need labels, could we add compact/expand option like for nodes?

![localhost_9000_k8s_all-namespaces_pods_orderBy=desc sortBy=Memory](https://user-images.githubusercontent.com/1167259/57531172-de6a0980-7306-11e9-92c5-08cb9472a6bb.png)

**Comment by beanh66** [comment]
This change looks good to me @spadgett. I also created [this issue](https://github.com/patternfly/patternfly-next/issues/1861) in PatternFly to try and get the "expand all" behavior added to PF tables in the future. For example: 

![expand-table](https://user-images.githubusercontent.com/18057044/58442737-351f6380-80bb-11e9-9073-0b93efbcb0b4.png)

**Comment by spadgett** [comment]
Closing since the pods list no longer shows labels.

/close
