### ISSUE TITLE
Pod metrics should report cores or millicores, not shares

### ISSUE THREAD

**Issue by smarterclayton** [openshift/console#342]
Shares is not a thing.  We should either report cores (unit-less) or millicores (most people think in terms of fractions of a core though, so 0.01 cores reads better than 10m in most cases).

**Comment by spadgett** [comment]
#1080 fixes this for the namespace page. We still need to look at it for the pod page.

cc @sjenning

**Comment by spadgett** [comment]
@sjenning updated #1080 to handle the pods page, too 👍
