### ISSUE TITLE
Add workloads from Administrator perspective

### ISSUE THREAD

**Issue by jchraibi** [openshift/console#3782]
Hi,
It would be great to be able to add workloads from the Administrator perspective, without needing to switch to Developer perspective. 
It is already possible by accessing it through: https://console_url/add/ns/project_name, but it would be good to have a button in the UI to do it.
Thanks!

**Comment by spadgett** [comment]
/kind feature

cc @serenamarie125 @beanh66 @christianvogt

**Comment by serenamarie125** [comment]
Good point @jchraibi.  When a project is empty we provide a way to access the Add page shown below:
![AccessingAdd](https://user-images.githubusercontent.com/12504403/73994281-fec10600-4922-11ea-988e-723e5ac62d88.gif)

We should consider an additional solution

FYI @sspeiche

**Comment by beanh66** [comment]
@jchraibi thanks for pointing that out. @serenamarie125 We could use the + Add icon in the masthead for this. Currently it's only for import YAML but we've talked about adding the other options there as well. @alimobrem
