### ISSUE TITLE
Operand's version at .Status.Version instead of .Spec.Version

### ISSUE THREAD

**Issue by jpkrohling** [openshift/console#3967]
Some Operators, such as the Jaeger Operator, manage the version of their operands. As such, there's no `Version` field under the `Spec` node, but there is one under `Status` instead.

The console's UI should fallback to `.Status.Version` in case `.Spec.Version` is empty.

https://github.com/openshift/console/blob/0150aba43092ae28e7585de5119895352e34bce1/frontend/packages/operator-lifecycle-manager/src/components/operand.tsx#L151-L156

![image](https://user-images.githubusercontent.com/13387/72425879-ebd66e00-3788-11ea-9656-6d53e02b9f39.png)

**Comment by spadgett** [comment]
cc @tlwu2013

**Comment by Jamstah** [comment]
Could we use a `StatusDescriptor` to specify which field to include? The version we'd like in the table is in Yet Another Location - `status.versions.reconciled`.

**Comment by spadgett** [comment]
We're actually removing this field from the table in #5310 because most operands don't have it. Let us know if you have concerns.
