### ISSUE TITLE
Build creation can fail if image stream doesn't exist

### ISSUE THREAD

**Issue by beanh66** [openshift/console#403]
The builds created from the build config create page examples can fail because the examples reference image streams that may not exist. 

I think we came to a consensus on the design solution so that users get successful builds using the example build configs. @bmignano can you post here? FYI @rhamilto @spadgett

**Comment by bmignano** [comment]
![combined](https://user-images.githubusercontent.com/40238481/44117134-6744db72-9fe0-11e8-8576-7d965e423815.png)

Here's a screenshot of the design. When users go to the "Create Build Config" page, they will be prompted to create both an image stream and a build config. The image stream creation will be in the same yaml editor as the build config. The sections to create each object will be called out and separated using comments. The create image stream section will appear at the top of the yaml editor regardless of which template a user selects.

**Comment by spadgett** [comment]
Suggest adding a comment explaining why you want an image stream. Something like:

```yaml
# Create an image stream for your builds. Built images can be pushed to an image stream tag for this image stream.
# Later you can set up deployment triggers that rollout updates automatically when builds complete.
```

**Comment by spadgett** [comment]
Note to be valid YAML you need `---` before each resource. (Our YAML editor doesn't currently support multiple documents, though.)
