### ISSUE TITLE
[Feature] resourceRequirements to support storage request

### ISSUE THREAD

**Issue by a1exeyz** [openshift/console#4139]
urn:alm:descriptor:com.tectonic.ui:resourceRequirements should support storage request format too, you should be able to disable items you don't want to see (cpu/mem/etc):

      resources:
        requests:
          storage: "5Gi"

**Comment by spadgett** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1794844

**Comment by benjaminapetersen** [comment]
Closing this out since we have a bugzilla to track.
