### ISSUE TITLE
404 when installing an operator with manual approval strategy

### ISSUE THREAD

**Issue by ppitonak** [openshift/console#4224]
1. open OpenShift web console
2. navigate to Operators -> Operator Hub -> search for "container sec"
3. click install 
4. choose **Manual** approval strategy
5. click on `container-security-operator` subscription
6. click on `1 requires approval`

Expected
* I end up on URL https://console-openshift-console.apps.example.com/k8s/ns/openshift-operators/operators.coreos.com~v1alpha1~InstallPlan/install-6jptg
* I approve the subscription and am able to start using the operator

Actual:
* I end up on URL https://console-openshift-console.apps.example.com/k8s/ns/openshift-operators/installplans/install-6jptg which only shows `404: Page Not Found`

Environment:
* OCP 4.3.1

![odc_install_plan2](https://user-images.githubusercontent.com/445100/73933349-8d5e6480-48dc-11ea-834b-9e3fb99d6e2c.gif)

**Comment by spadgett** [comment]
This will be fixed by #4170

/assign
/kind bug

**Comment by spadgett** [comment]
#4170 has merged.

/close
