### ISSUE TITLE
Service Catalog -> Service Classes: inconsistent titles

### ISSUE THREAD

**Issue by dtaylor113** [openshift/console#430]
Nav Menu is "Service Catalog -> Service Classes"
List Page has "Cluster Service Classes"
Details Page has "Service Class Overview"

Should we remove "Cluster ..." from List Page, or add "Cluster ..." to Details page?

**Comment by spadgett** [comment]
We want to add namespaced service classes to that page like we do for the role bindings page. We can address the naming at that time.

**Comment by spadgett** [comment]
Addressed by #948
