### ISSUE TITLE
CRW console integration fails if there is .git extension in git repo

### ISSUE THREAD

**Issue by jchraibi** [openshift/console#4322]
Hi,

When CodeReady Workspaces is deployed, the integration in the console (Edit source button) fails if there is a ".git" extension in the repo URL -> CRW is unable to locate the devfile.yaml in the root or clone the git repo. 
--------
The workaround
- It works if we ommit the ".git" in the repo URL.
For example: https://github.com/sclorg/nodejs-ex.git fails whereas https://github.com/sclorg/nodejs-ex works (with a devfile.yaml) in the root.
- it also works of you remove the .git from the annotation "app.openshift.io/vcs-uri" on the deployment or deploymentConfig

**Comment by sunix** [comment]
In my opinion, it has to be fixed in CRW: CRW should be more robust and accept git URI that finish with `.git`

**Comment by christianvogt** [comment]
@jchraibi could you please provide more information about the error you encountered.

I tested this on OpenShift 4.3.2 with CRW operator v 2.0.0.
I created a new project using the dev-catalog and used the sample URL. I was able to load a workspace using the the URL with `.git` suffix.

You may want to raise your issue with https://github.com/eclipse/che if you can still reproduce this.

**Comment by jchraibi** [comment]
Hi Christian,
Did you put a devfile in the git repo root ? The problem I encountered is
that when there is a .git extension, CRW does create a new workspace but is
unable to load the devfile.
So yes, it is probably better to raise the issue in che side.

Jaâfar CHRAÏBI
Principal Technical Marketing Manager - Cloud Platforms
Tél: + 33.7.76.88.95.16

*Learn more about OpenShift: http://learn.openshift.com
<http://learn.openshift.com>*
*A curious mind?* http://blog.openshift.com
*Are you a developer?* http://developers.redhat.com

*Red Hat France *
*RED HAT | TRIED. TESTED. TRUSTED*
Immeuble Défense Plaza
23-25 rue Delarivière Lefoullon
92800 Puteaux


<%2B%2033%206%2089%2084%2077%2061>

**Comment by christianvogt** [comment]
/close
Confirmed that indeed with `.git` extension, the devfile is loaded as the default instead of what's in the project.
Closing issue as it's an upstream bug and @jchraibi said he would get it logged upstream.
