### ISSUE TITLE
Frontend Development: can't find UI

### ISSUE THREAD

**Issue by HeroMeiKong** [openshift/console#4329]
I run 'yarn dev', then, I find 'Project is running at http://localhost:8080/', but I can't see UI, it was directory, please tell me how to see the UI ?

**Comment by markmont** [comment]
I started working with OpenShift Console today and had the same question.

It looks like `yarn run dev` only watches for changes and rebuilds the webpack, the web application itself is still served through `bridge`.  The following worked for me:

```
# (log in using the `oc login` command, and then...)
source ./contrib/oc-environment.sh
./bin/bridge

# in a different terminal, run
yarn run dev
```

Then go to https://localhost:9000/ in your web browser.

Now when you make a change to a file under the `frontend` directory, the change will be detected and after everything has been rebuilt the UI in your web browser will automatically reload.  This may take between a few seconds to a minute to happen depending on the speed of your computer, container, or virtual machine.

**Comment by spadgett** [comment]
Thanks @markmont 👍 

You do need to run the bridge binary separately. Console requires the backend to proxy requests to the API server. Let us know if you still have questions.
