### ISSUE TITLE
No pipeline section in Import from git

### ISSUE THREAD

**Issue by ppitonak** [openshift/console#4405]
1. login as non-admin to **OpenShift 4.4**
2. open developer perspective
3. Add -> From Git -> scroll down

expected:
* there is a `Pipelines` section and I can add a pipeline to my project
![odc_pipeline_template2](https://user-images.githubusercontent.com/445100/75032998-27f89f00-54aa-11ea-9d79-4edb43955d97.png)

actual: 
* `Pipelines` section is completely missing
* works fine when I login as kubeadmin
![odc_pipeline_template1](https://user-images.githubusercontent.com/445100/75033009-2dee8000-54aa-11ea-8af1-5ccb04432842.png)

**Comment by spadgett** [comment]
@ppitonak can you verify this user can list pipelines in the `openshift` namespace? There are a few access checks we make before we show the section:

https://github.com/spadgett/console/blob/5e7196eda0e2aa2d888877a5de3fd9e500c9da42/frontend/packages/dev-console/src/components/import/pipeline/PipelineSection.tsx#L20-L39

/cc @christianvogt
