### ISSUE TITLE
Kabanero CR instance in OCP 4.3 console shows apiVersion v1alpha1 instead of v1alpha2

### ISSUE THREAD

**Issue by tam512** [openshift/console#4444]
- Using OCP 4.3, install Kabanero 0.6.0, then create a Kabanero CR instance using the default yaml (_oc apply -n kabanero -f https://raw.githubusercontent.com/kabanero-io/kabanero-operator/0.6.0-rc.5/config/samples/default.yaml_).  
- When viewing the kabanero instance using command line _`oc get kabanero -n kabanero -o yaml`_, it shows **`apiVersion: kabanero.io/v1alpha2`**, but when viewing the kabanero instance in OCP 4.3 console (_navigate to Administration > Custom Resource Definition > Kabanero > Instances > kabanero > YAML_), it shows as **`apiVersion: kabanero.io/v1alpha1`**

![Screen Shot 2020-02-24 at 11 21 56 AM](https://user-images.githubusercontent.com/22480038/75175421-e9f0ba80-56f7-11ea-9d1d-1ffe09839298.png)

**Comment by kaczyns** [comment]
It's worth noting here - the `kabaneros.kabanero.io` CRD has both a v1alpha1 and v1alpha2 version configured.  Both versions are served, but only the v1alpha2 version is stored.

**Comment by spadgett** [comment]
This is related to https://bugzilla.redhat.com/show_bug.cgi?id=1822437

We're working on updating the CRD page to prefer the most recent API version (ordering by stable > beta > alpha, then version). Note that you can also get to the resource from Home -> Search or Home -> Explore to use the more recent API version.

/kind bug
/assign @jcaianirh

**Comment by marikaj123** [comment]
@spadgett - This is considered severe error from our product perspective when the fix would be available?

**Comment by spadgett** [comment]
> @spadgett - This is considered a severe error from our product perspective 

Understood.

> Would the fix be available in OCP 4.4?

We plan to address this in a 4.4.z release. I'd subscribe to the Bugzilla for the latest updates.

**Comment by kaczyns** [comment]
It looks like this was fixed in 4.4.x, according to the bugzilla.  I think this is OK to close, does anyone else agree?

**Comment by spadgett** [comment]
This should be fixed by https://bugzilla.redhat.com/show_bug.cgi?id=1822437 in 4.4.z. If it's not, please feel free to reopen.

/remove-lifecycle stale
/close
