### ISSUE TITLE
RFE: a terminal/shell window on the openshift web console for doing 'oc' commands

### ISSUE THREAD

**Issue by erikerlandson** [openshift/console#4618]
Not all environments have easy access to a shell. Being able to pull up a terminal window for the purpose of running 'oc' commands against the cluster api could be very handy. A nice feature would be to have it pre-logged in to whatever login you used to access the console, so 'oc login' isn't required.

**Comment by spadgett** [comment]
Enhancement proposal: https://github.com/openshift/enhancements/pull/182

**Comment by spadgett** [comment]
Note that this was recently added to OpenShift console through the web terminal operator: https://www.openshift.com/blog/a-deeper-look-at-the-web-terminal-operator-1

/remove-lifecycle rotten

**Comment by erikerlandson** [comment]
@spadgett thanks - I have seen that operator in the catalog but didn't realize it addresses this use case
