### ISSUE TITLE
Session state is stored in a persistent cookie

### ISSUE THREAD

**Issue by Jamstah** [openshift/console#4628]
When the openshift session cookie is created, a maxage is set that matches the length of time the cookie is valid.

Because this is set, the browser stores the cookie in a persistent way, and the user does not have to reauthenticate if they close the browser and reopen it.

As there is no option for "remember me" or "This is a public computer", I feel that a better approach may be to use a session cookie, and force the user to reauthenticate instead.

Lines where the cookie is set depending on auth mechanism:
https://github.com/openshift/console/blob/15b34bbbc0c9a5c2e902080b15d65639e2158f88/pkg/auth/auth_oidc.go#L76
https://github.com/openshift/console/blob/6cd67604a71b706fcaf2d2fed08f261deb00a08a/pkg/auth/auth_openshift.go#L145

Depending on the need for a persistent cookie, another option may be to add a config parameter to the configuration CR and allow the admin to decide how session state is stored. This is probably overkill though.
https://docs.openshift.com/container-platform/4.3/web_console/configuring-web-console.html#web-console-configuration_configuring-web-console

Happy to submit a PR, but thought it was more polite to raise an issue to make sure there is agreement on how sessions should be handled first.

**Comment by kbelow** [comment]
I am able to utilize the web console after selecting log out 
environment: ibmcloud, openshift 4.7.12 cluster, openshift 4.6.28 cluster

**Comment by RSAlderman** [comment]
Is there any update on this vulnerability:
- has it been triaged?
- has a CVE been assigned?

**Comment by RSAlderman** [comment]
FYI a bugzilla issue https://bugzilla.redhat.com/show_bug.cgi?id=1977484 has also been raised for this

**Comment by RSAlderman** [comment]
Response from [bugzilla issue](https://bugzilla.redhat.com/show_bug.cgi?id=1977484#c2) is that this is working as designed:

> Samuel Padgett 2021-07-06 13:29:15 UTC
> 
> Hi, this is working as intended. The user's token is only good for a specific time limit that can be configured through the OAuth configuration. You can set this to a smaller value like 30 minutes or 1 hour. Console will also honor an inactivity timeout that you can set through the OAuth configuration. These settings give you some control over the user's session. In particular, inactivity timeout seems like it addresses your concern and is in some ways better because it does not require the user to close the browser window.
> 
> https://docs.openshift.com/container-platform/4.7/authentication/configuring-oauth-clients.html#oauth-token-inactivity-timeout_configuring-oauth-clients
> 
> Note that users can log out on a public computer, which will remove the token (or better yet use private browsing mode). This is consistent with virtually all web apps.
> 
>
