### ISSUE TITLE
RFE: selector descriptor should work with Kubernetes Custom Resource as well

### ISSUE THREAD

**Issue by prafull11** [openshift/console#4720]
Currently, there is no way to describe the Kubernetes Custom Resource using descriptor. User should be able to use the the selector field for kubernetes Custom Resources as well. 

For example, I can select the secrets using the following descriptor:
`'urn:alm:descriptor:com.tectonic.ui:selector:core:v1:Secret'`

Same way I should be able to select the custom resource Target as:
'urn:alm:descriptor:com.tectonic.ui:selector:custom.io:v1alpha1:Target'

**Comment by prafull11** [comment]
@yzhao583 Can you please comment. Is this possible to this in near future?

**Comment by tlwu2013** [comment]
Hi @prafull11 ,

Want to reply here as well in addition to the separate email thread.
This one is the same as the previous RFE for “_a descriptor to specify k8s resource including CR instance with GVK_" info.

This one is targeting OCP 4.6 release in our backlog too.

**Comment by spadgett** [comment]
This was added in #5641 and will be available in 4.6.

/close
