### ISSUE TITLE
Any plan to support localization?

### ISSUE THREAD

**Issue by gyliu513** [openshift/console#4813]
Like supporting Chinese, Japanese language etc.

**Comment by sundeep-co-in** [comment]
Have tried to approach `i18n` of OpenShift Console. 
For initial feasibility, looked at 3 frameworks: `react-intl`, `react-i18next` and `lingui`

**react-intl**

most popular and feature rich react i18n framework. stable. famous. heavier. big community. messages can be extracted using babel. formatting APIs. `BSD-3-Clause` license. *wip*: https://github.com/sundeep-co-in/console/pull/7

**react-i18next**

powerful and easy to integrate framework, which provides various components/backends to create a pluggable `i18n` infrastructure. well documented and active community. may be lots of plugins to handle; we can write one as per our need too. `MIT` license. *wip*: https://github.com/sundeep-co-in/console/pull/6

**lingui**

lower memory footprints, handy cli to extract/compile translations, ICU MessageFormat. may require some custom hook. getting popular in community. `MIT` license. *wip*: https://github.com/sundeep-co-in/console/pull/5

Todo items:
- [ ] Lazy loading/delivery of translations
- [ ] Identification and marking of strings for `l10n`
- [ ] Date, Currency, etc. formatting
- [ ] Scripts to integrate `l10n` in builds, `CI` pipeline

<hr/>
<h4>I guess, a lot of discussions required. A few early ones:</h4>

1. how we want to translate mix of messages/context displaying on the Console? do we want to keep `namespace` and `id` for messages; `context` could also be an option? which format we're comfortable with: `PO/JS` or `PO/JS` or `JSON`? should we split or keep single translation file?
```
Half of the answer could be: by enabling an i18n framework for Console, 
UI messages could be localized. (in the first place)
PO files are more famous in translation platforms/tools/utilities.
```
2. how should we ensure/track translation of messages coming from external apps or API?

3. (*less important*) should we have language switcher in `nav.header` along with `languagedetector`?

4. what should be the scope of first viable localized Console release? which i18n framework to move ahead with? do I need to write some proposal?

Just in case, starting of this effort calls for a proposal, 
kindly guide: how can I? and main points to include?


thanks @gyliu513, and
hi @kyoto @spadgett seeking inputs ..

**Comment by spadgett** [comment]
Hi, thanks @sundeep-anand. This is helpful and matches what we've been looking at as well. We're currently evaluating it with the Patternfly team and did some investigation in https://github.com/patternfly/patternfly-react/issues/3952.

**Comment by jschuler** [comment]
Hey @sundeep-anand , I like what you've done here, I took a look at react-intl and react-18next as well and they're both really good. I liked how easy it was to create namespaces/separate files that can be loaded on-demand with i18next. Also they have a cool parser that understands Typescript which makes it simple to parse openshift frontend code for usages of translations. My sample PR is here https://github.com/jschuler/console/pull/1

**Comment by sundeep-anand** [comment]
hi @jschuler @spadgett  - welcome!
it's great to see all investigations done. somehow I too have a feeling of moving ahead with `i18next` for the kind of `i18 infra` we may look forward. I really like your work @jschuler and shall try testing `PR` (_as we progress_) as well as contributing where-ever I can.

**Comment by bjleiji** [comment]
Hello @spadgett @sundeep-anand @jschuler , my colleague @xuruili and myself are interested with this project.  We are from IBM globalization team. Not sure can we join this project?  and  I have a following questions:
1. Per above discussion, in my understanding , team will use i18next framework, right?  Is any volunteer from developer team to extract the messages on UI to PII(Program Integrated Information) files(EN files) which will be used for translation?
2. Only OKD openshift or both OKD and enterprise openshift will do the localization?
3. Not sure do you have any process or proposal for openshift localization? Like translation process, who will do the translation: translator(human) or machine learning?
4  Not sure is any volunteer on globalization/localization now?

**Comment by spadgett** [comment]
The localization enhancement proposal is https://github.com/openshift/enhancements/pull/466. The initial PR for localization is #6194.

**Comment by spadgett** [comment]
Closing this issue. Please follow the above PRs for updates. Thanks!

**Comment by spadgett** [comment]
The initial PR #6194 that adds the i18next framework and some localizations has merged. We have follow on PRs for localizing different sections of the UI.
