### ISSUE TITLE
RFE: save components locations in topology view

### ISSUE THREAD

**Issue by jchraibi** [openshift/console#4816]
The topology view is useful only if we can nicely arrange the components layouts in groups for an app, like front, middle and backend, AND be able to recall that when switching back to the topology view. Otherwise, when opening the topology everything gets shuffled again and it get less readable.

**Comment by sspeiche** [comment]
We allow you to arrange things into app grouping and name them using Kubernetes app label guidelines.

Moving nodes in the graph around and saving the locations, is tracked in a Jira issue (will update when I locate it)
