### ISSUE TITLE
Helm installation request times out 

### ISSUE THREAD

**Issue by akashshinde** [openshift/console#4821]
Helm install api request times out when installation takes more than 20 secs. 

To handle such issues we might need to introduce async request.

**Comment by pedjak** [comment]
The timeout is set on the requester side, not at the endpoint side.

**Comment by christianvogt** [comment]
There is a client side timeout here:
https://github.com/openshift/console/blob/4ce7272c4ae06b197ce89f48d07e90795c85c9d5/frontend/public/co-fetch.js#L99

It's been in place for a long time but I do not agree with having this timeout.
Will look into having it removed.

**Comment by spadgett** [comment]
Fixed by #5023

/close
