### ISSUE TITLE
Volumes table disappears while scrolling on initial load of the page.

### ISSUE THREAD

**Issue by ddonahue007** [openshift/console#4872]
**Experienced this on:**
  *  Chrome: Version 80.0.3987.149 (Official Build) (64-bit)
  *  Firefox: 68.6.0esr (64-bit)

I have include a link to a short clip that demonstrates the behavior I am experiencing.

https://drive.google.com/open?id=1GsHGQ5UwjQZQ2Da4g7YD3eKtS6aLRigm

**Comment by ddonahue007** [comment]
Closing, opened Bug in Bugzilla

https://bugzilla.redhat.com/show_bug.cgi?id=1819752

**Comment by spadgett** [comment]
Fixed in 4.5 by #4880
