### ISSUE TITLE
RFE : HELM - Federated Repository Support

### ISSUE THREAD

**Issue by morstad** [openshift/console#4898]
Request ability to federate 1-n helm repository(s) into Developer catalog for customers who use helm charts from multiple locations (internal / external) and / or  providers.  Customer choice to pick and chose which helm repositories to include - from defined or custom list.   This would also enable partners to curate catalogs for inclusion base RH helm catalog (similar to how there are multiple operator providers - Red Hat, Certified, Community, & Marketplace).   

FYI - @sbose78

**Comment by sbose78** [comment]
Thanks Nancy, will triage it for our 4.6 planning. @siamaksade

**Comment by morstad** [comment]
Function is in 4.6 - verified via nightly builds.
