### ISSUE TITLE
Clusterwide CRD is not showing on the UI properly on openshift 4.4 pre builds

### ISSUE THREAD

**Issue by prafull11** [openshift/console#4966]
I am installing my CRDs in cluster mode but I am not able to see the objects created by it in UI.

`test@prafull:~/samples$ kubectl get nodes
NAME                                                       STATUS   ROLES    AGE     VERSION
ocp-te-d5nm2-m-0.c.amazing-chalice-243510.internal         Ready    master   5d18h   v1.17.1
ocp-te-d5nm2-m-1.c.amazing-chalice-243510.internal         Ready    master   5d18h   v1.17.1
ocp-te-d5nm2-m-2.c.amazing-chalice-243510.internal         Ready    master   5d18h   v1.17.1
ocp-te-d5nm2-w-a-z8jgc.c.amazing-chalice-243510.internal   Ready    worker   5d18h   v1.17.1
ocp-te-d5nm2-w-b-jdznn.c.amazing-chalice-243510.internal   Ready    worker   5d18h   v1.17.1
ocp-te-d5nm2-w-c-ppd7m.c.amazing-chalice-243510.internal   Ready    worker   5d18h   v1.17.1

test@prafull:~/samples$ kubectl get targets.triliovault.trilio.io 
NAME            TYPE   VENDOR   STATUS
sample-target   NFS    Other    Available
`

But when I go to UI I get error **404 Not found** . This is related to the [https://github.com/openshift/console/issues/3040](url) but it is not fixed yet.

![Screenshot from 2020-04-08 13-56-21](https://user-images.githubusercontent.com/56869150/78762073-0b082480-79a1-11ea-8648-3c49bb952c7a.png)

**Comment by prafull11** [comment]
I have verified that this issue happens on the 4.3 as well.

**Comment by spadgett** [comment]
Hi @prafull11, are you able to provide steps to reproduce? It worked OK for me using the CNV operator as reported in https://bugzilla.redhat.com/show_bug.cgi?id=1757526, so we might need the specific CSV/CRDs you're testing.

**Comment by prafull11** [comment]
Okay, issue was in our CSV. With latest changes it is working fine. Closing this issue. Thanks for your support.
