### ISSUE TITLE
alternative to ui:label spec descriptor to use

### ISSUE THREAD

**Issue by prafull11** [openshift/console#4970]
I want to take labels as an input in my CR spec for selecting some resources. Earlier there was descriptor which is deprecated now
`- urn:alm:descriptor:com.tectonic.ui:label`

Can anyone please let me know alternative descriptor to select the labels? Thanks

**Comment by tlwu2013** [comment]
Hi @prafull11 ,

Want to reply here as well in addition to the separate email thread.

This one is about the need to have "a descriptor that allows me to specify labels for identifying a set of objects via a selector".
We are also working on planning the selector descriptor for OCP 4.6 release.

In your case, are you looking more for a simple map of `{key,value}` pairs (`matchLabels`)?
Or you would also care about using `matchExpressions` with `{key,operator,value} `for the selector too?
