### ISSUE TITLE
Upgrade available, but awaiting approval has misleading Status value of "Upgrading"

### ISSUE THREAD

**Issue by lizsurette** [openshift/console#5063]
I have an operator that has an upgrade available, but since it has a manual approval strategy, it needs to be approved before the upgrade kicks off. Technically, it's not upgrading, but the Status says it is. I think we should update this text to be more accurate if possible. Maybe something like "Upgrade awaiting approval"? 

What do you think @itsptk ?

<img width="1680" alt="Upgrade Needs Approval" src="https://user-images.githubusercontent.com/208455/79377938-78c8c900-7f2a-11ea-8023-291121ec4ed7.png">

**Comment by itsptk** [comment]
Agreed! @tlwu2013 and I had talked about this issue recently and think we will try and fix this as a bug in 4.5. I created https://issues.redhat.com/browse/PD-458 to capture it. Tony, was there a dev issue or bug tracking this yet?

**Comment by tlwu2013** [comment]
Yes, just created a new [console bug](https://issues.redhat.com/browse/OLM-1696) to track this (also attached the old OLM bug on this new bug for synced up the background).

**Comment by lizsurette** [comment]
> Yes, just created a new [console bug](https://issues.redhat.com/browse/OLM-1696) to track this (also attached the old OLM bug on this new bug for synced up the background).

Awesome, thanks @tlwu2013 and @itsptk !

**Comment by benjaminapetersen** [comment]
Closing this out as there is a Jira, but migrating the Jira to Bugzilla (nice string eh?):
https://bugzilla.redhat.com/show_bug.cgi?id=1826481
