### ISSUE TITLE
Inconsistent capitalization of "YAML" throughout console

### ISSUE THREAD

**Issue by cshinn** [openshift/console#510]
On details pages:
<img width="158" alt="screen shot 2018-09-07 at 4 15 57 pm" src="https://user-images.githubusercontent.com/3300756/45241962-54bbf500-b2bc-11e8-9878-98b4d6cf7281.png">

In secrets dropdown:
![screen shot 2018-09-07 at 3 02 52 pm](https://user-images.githubusercontent.com/3300756/45241970-5eddf380-b2bc-11e8-9048-afeb55440509.png)

In Application console actions dropdown:
<img width="182" alt="screen shot 2018-09-07 at 4 41 14 pm" src="https://user-images.githubusercontent.com/3300756/45242126-e461a380-b2bc-11e8-9d79-0b530d3949aa.png">

In template suggestions on creation pages:
<img width="202" alt="screen shot 2018-09-07 at 4 15 45 pm" src="https://user-images.githubusercontent.com/3300756/45241981-67cec500-b2bc-11e8-9651-691312e0ed8f.png">

So far this last one is the only use of "yaml" that I've found, but there may be others hidden in the console. Was there a specific reason for this styling, or is this an error?

**Comment by robszumski** [comment]
I think it's probably just an oversight.

Related, should it be yml or yaml? /s
