### ISSUE TITLE
Developer catalog GUI : Customization of menu

### ISSUE THREAD

**Issue by yeplaa** [openshift/console#5171]
Hello,

On OCP 4.3, i wish to customize the Developer GUI. 
Indeed bellow my needs : 

- In the "+Add"-> "From Catalog" menu, i wish add a category (like Databases menu for example) 
- I wish that the categories that are displayed on the left hand side (Languages, Databases, Middleware ...) allow to add new subcategories in this current categories (For example, I wish add Elasticsearch, Redis, Cassandra subcategories in the Current Databases category) 
- I need to be able to customize the developer catalog with new categories and modify the existing items/add new items. 

Bellow the screenshot of Menu from Developer Catalog : .  
![Developer_Catalog](https://user-images.githubusercontent.com/1431047/80111976-d8555300-8580-11ea-946b-054160762062.png)

Theses item/categories seems to be explicitly listed and not dynamically managed :  https://github.com/openshift/console/blob/8dd63348653fe43e355464489827e4b7ed619724/frontend/public/components/catalog/catalog-items.tsx#L97 

Do you see a solution to my problem? Have you any idea? 

Thanks for your help & have a good day
Loïc

**Comment by sspeiche** [comment]
Internal tracking RFE https://issues.redhat.com/browse/ODC-3671

**Comment by yeplaa** [comment]
Thanks @sspeiche for your reply. Have you any information on the treatment of the problem?

**Comment by spadgett** [comment]
Implemented in 4.7 by #7196. See also https://github.com/openshift/enhancements/pull/508

/close
