### ISSUE TITLE
HELM - Console displays 'Install Helm Chart' screen w/o values.yaml when index.yaml points to invalid tgz path

### ISSUE THREAD

**Issue by morstad** [openshift/console#5190]
When installing helm chart from OCP developer catalog if the helm repo index.yaml points to invalid location the install screen is displayed without values (tgz can't be found) and no error message.   

![image](https://user-images.githubusercontent.com/24810680/80316296-a2071600-87c2-11ea-90cf-6d5589fbc198.png)

@pedjak

**Comment by pedjak** [comment]
/assign @rohitkrai03 

can you take a look?

**Comment by rohitkrai03** [comment]
@pedjak I'll take a look.

**Comment by rohitkrai03** [comment]
@morstad Do you mean we need to show some kind of error message if we don't have the values.yaml for the editor or are you facing this issue for specific chart that shouldn't happen?

**Comment by morstad** [comment]
@rohitkrai03 The issue was the helm index was updated with invalid URL for the helm chart tgz.  
 This has been fixed, but an error chart indicating tgz not found vs displaying as if could install would be preferred.

**Comment by rohitkrai03** [comment]
Okay, I'll bring this up with our UX team to come up with an alert or something so that users are aware of it.

**Comment by morstad** [comment]
@rohitkrai03 What was result of discussion with UX team?   In this scenario the index is pointing to incorrect location for tgz - there is no helm chart at all to render thus empty screen.

**Comment by rohitkrai03** [comment]
We have a bug to address this and UX came up with a generic alert message to show when the chart is unreachable.

**Comment by morstad** [comment]
When will this be delivered?

**Comment by rohitkrai03** [comment]
https://github.com/openshift/console/pull/6572 Fixes the issue.
