### ISSUE TITLE
Data lost between CR YAML and Form switch

### ISSUE THREAD

**Issue by gyliu513** [openshift/console#5225]
When I create a Kong CR from OCP UI as follows with YAML

![image](https://user-images.githubusercontent.com/4461983/80556469-390fe000-8a06-11ea-83a9-b3e53836a2e2.png)

Then I click `Edit Form` and change name to `demo`

![image](https://user-images.githubusercontent.com/4461983/80556491-504ecd80-8a06-11ea-97f0-5a0237541cd1.png)

Then click `Edit YAML` and switch back to YAML

![image](https://user-images.githubusercontent.com/4461983/80556548-7aa08b00-8a06-11ea-9489-53a717186880.png)

I found the name was not changed. Why not keep the YAML and Form consistent?

**Comment by spadgett** [comment]
@gyliu513 What OpenShift version is this? We only added syncing in 4.4 (#3894).

**Comment by gyliu513** [comment]
I was using OCP 4.3. @spadgett

**Comment by spadgett** [comment]
> I was using OCP 4.3. @spadgett

Thanks, closing as this is addressed by #3894 in 4.4.

/close
