### ISSUE TITLE
auth: link OAuth2 state parameter with user agent

### ISSUE THREAD

**Issue by ericchiang** [openshift/console#53]
(NOTE: we have someone internally who's been assigned this)

Currently we generate a "state" redirect parameter because some providers reject requests without them. However we don't actually link the state parameter to the user's session, leaving us vulnerable to certain cross-site request forgery attacks.

https://github.com/openshift/console/blob/9c80cb314e89a36f92464d163d499806cf03ad79/auth/auth.go#L232-L238

https://tools.ietf.org/html/rfc6749#section-4.1.1

Cookie the user with something that can link back to the "state" parameter we pass, per the recommendations in RFC 6819.

https://tools.ietf.org/html/rfc6819#section-5.3.5

> 5.3.5.  Link the "state" Parameter to User Agent Session
>
>   The "state" parameter is used to link client requests and prevent
   CSRF attacks, for example, attacks against the redirect URI.  An
   attacker could inject their own authorization "code" or access token,
   which can result in the client using an access token associated with
   the attacker's protected resources rather than the victim's (e.g.,
   save the victim's bank account information to a protected resource
   controlled by the attacker).
>
>   The client should utilize the "state" request parameter to send the
   authorization server a value that binds the request to the user
   agent's authenticated state (e.g., a hash of the session cookie used
   to authenticate the user agent) when making an authorization request.
   Once authorization has been obtained from the end user, the
   authorization server redirects the end-user's user agent back to the
   client with the required binding value contained in the "state"
   parameter.
>
>   The binding value enables the client to verify the validity of the
   request by matching the binding value to the user agent's

**Comment by ericchiang** [comment]
cc @Sean-Q-Sun

**Comment by Sean-Q-Sun** [comment]
/close
Addressed by #60
