### ISSUE TITLE
specDescriptors and console UI do not support complex structs

### ISSUE THREAD

**Issue by aharbis** [openshift/console#5347]
We are building our operator using Go, and the Operator SDK. Using `specDescriptors` I've been unable to determine how to properly build out structure in the Console UI **Edit Form** view.

For example, I have some struct in my spec like this:

```go
type UserSpec struct {

        // Name of the user
        // +kubebuilder:validation:MinLength=1
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors=true
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.displayName="Name"
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.x-descriptors="urn:alm:descriptor:com.tectonic.ui:text,urn:alm:descriptor:com.tectonic.ui:fieldGroup:User"
        Name string `json:"name"`

        // Secret for user's credentials
        // +kubebuilder:validation:MinLength=1
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors=true
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.displayName="Password secret"
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.x-descriptors="urn:alm:descriptor:io.kubernetes:Secret,urn:alm:descriptor:com.tectonic.ui:fieldGroup:User"
        PasswordSecret string `json:"passwordSecret"`

        // User access level
        // +kubebuilder:validation:Enum:=group-defined;privileged
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors=true
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.displayName="Access level"
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.x-descriptors="urn:alm:descriptor:com.tectonic.ui:select:group-defined,urn:alm:descriptor:com.tectonic.ui:select:privileged,urn:alm:descriptor:com.tectonic.ui:fieldGroup:User"
        AccessLevel string `json:"accessLevel"`

        // User group
        // +kubebuilder:validation:Optional
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors=true
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.displayName="User group"
        // +operator-sdk:gen-csv:customresourcedefinitions.specDescriptors.x-descriptors="urn:alm:descriptor:com.tectonic.ui:text,urn:alm:descriptor:com.tectonic.ui:fieldGroup:User"
        Group string `json:"group,omitempty"`
}
```

I have manually added each field in the struct to the following `fieldGroup`:

```
urn:alm:descriptor:com.tectonic.ui:fieldGroup:User
```

and this allows them to show up together in the creation view, but in the "Display" view they are not grouped, nor recognized as part of the same structure. They all appear at the top-level.

Additionally, each field of the struct appears at the top-level with its value, but the struct is also shown in the "Display" view, with a value of `Unsupported`, since it's a structure.

There seems to be severe lack of support for building out complex objects using `specDescriptors`, or displaying these fields / objects in the instance overview.

**Comment by spadgett** [comment]
cc @tlwu2013 @TheRealJon

**Comment by TheRealJon** [comment]
@aharbis The fieldGroup descriptor is not supported in Display Views, as noted in the [fieldGroup descriptor reference](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#15-fieldgroup). Your best bet would probably be to prefix your descriptor displayNames with 'User' so that they can be differentiated in Display View. They will be rendered in the same order that they are in the csv descriptors array, so they can be grouped together in that way.

**Comment by aharbis** [comment]
Appreciate the response @TheRealJon.

Long term, what are the plans to support structs like this (as well as nested structs) natively without the need to "hack" the `fieldGroup` or `displayNames`?

The above `UserSpec` is an example of a custom, but flat, struct. We have plenty of other structs in our CRD that are far more complex, and include arrays of nested structs, etc. Are there plans in future releases (such as 4.5) to support this type of object representation in the UI?

**Comment by aharbis** [comment]
I would also add that in practice, the above example `UserSpec` is allowed in array form, so in the CR YAML you would see something like:

```yaml
spec:
  users:
    - name: "john"
      passwordSecret: "secret-john"
      accessLevel: "privileged"
    - name: "bob"
      passwordSecret: "secret-bob"

**Comment by TheRealJon** [comment]
@aharbis In 4.5, the creation form will have more robust support for rendering schema objects and arrays, including nested structures. This only applies to the creation view though. @tlwu2013 might have more insight on future plans for the display/modify views.

**Comment by tlwu2013** [comment]
Hey @aharbis, as @TheRealJon mentioned, the creation view is our first step to have more robust support for rendering schema.

The team is actively improving both the UX/features of managing Operands in the console, and the modify/display views are definitely on our radar. Thanks for being engaged and providing feedback!

**Comment by abkieling** [comment]
I miss more documentation about specDescriptors in the Openshift docs. Are there any plans to improve that?
