### ISSUE TITLE
Change the default access mode when creating PVCs

### ISSUE THREAD

**Issue by cajosc** [openshift/console#5455]
When creating a PVC, the default access mode is hard-coded to _ReadWriteOnce_ [here](https://github.com/openshift/console/blob/master/frontend/public/components/storage/create-pvc.tsx#L52). We're using NFS-backed storage and would like to change the default to _ReadWriteMany_. Would it be possible to make this a configuration setting?

**Comment by spadgett** [comment]
That's only the default value. There should be a radio button. Are you using a storage class with`kubernetes.io/no-provisioner`?

https://github.com/openshift/console/blob/master/frontend/public/components/storage/create-pvc.tsx#L26

cc @gnehapk

**Comment by cajosc** [comment]
Yes, there is a radio button, but the default selected option is _Single User (RWO)_. I'd like to change the default selected option to _Shared Access (RWX)_ to make it easier for our users to select the correct option.

![image](https://user-images.githubusercontent.com/783983/82251583-bc5d8b00-994d-11ea-8b73-39fb51bbcbff.png)

**Comment by spadgett** [comment]
Oh, sorry I misread. You're asking for an option to change the default.

We default to RWO since it's supported by pretty much every provider. We can look at making it configurable.

cc @alimobrem
