### ISSUE TITLE
Show the developer perspective by default?

### ISSUE THREAD

**Issue by cajosc** [openshift/console#5488]
Is it possible to show the developer perspective by default, preferably with an option to show the administrator console for certain users/groups?

**Comment by spadgett** [comment]
It's not possible at the moment, but it's something we can consider. Note that we remember the last selected perspective, so this would only apply the very first time you loaded console.

@christianvogt @serenamarie125 @sspeiche

**Comment by christianvogt** [comment]
Automatically launching into the developer perspective something we're looking at in the 4.6 release. However this item is focused on determining if there's some heuristics we can apply to determine this per user. 
I really do not know if this will be possible without some admin configuration as suggested in the original post.

**Comment by rohitkrai03** [comment]
https://github.com/openshift/console/pull/5911 fixed this.
