### ISSUE TITLE
Edit form view by default

### ISSUE THREAD

**Issue by sethpeterson** [openshift/console#5519]
Is there a setting that I can specify in my CSV to show the "Edit Form" view as the default view instead of the yaml creation view when creating an instance of a CR from my operator?

**Comment by spadgett** [comment]
Hi, this is the default in OpenShift console now. I believe we made the switch in #4944, which will be in the 4.5 release. For earlier versions, there's unfortunately no way to change it.

cc @TheRealJon @itsptk 
/close
