### ISSUE TITLE
Browser refresh is required to see new catalog entries from brokers

### ISSUE THREAD

**Issue by rthallisey** [openshift/console#555]
If you create any new serviceclasses in the catalog the UI requires a browser refresh to pick them up.  Is there any way to make it more dynamic so a browser refresh isn't required?

**Comment by rthallisey** [comment]
cc @spadgett

**Comment by spadgett** [comment]
This is no longer a limitation in the converged console in 4.0. (Note that service catalog does have a relist delay unless you manually sync.)

**Comment by spadgett** [comment]
Closing since this is addressed in master. Let me know if you have concerns.

**Comment by rthallisey** [comment]
@spadgett thanks for the info.  I thought so given what I was seeing with operators being listed dynamically, but wanted to see if it was only on the operator side.
