### ISSUE TITLE
Show the OpenShift version to normal users in the About page

### ISSUE THREAD

**Issue by omajid** [openshift/console#5606]
As someone who is just getting started with OpenShift, one of the first questions I generally want an answer to when I am looking at an OpenShift console is to find out the version.

The "About" dialog shows the Kubernetes version. I have to read through the OpenShift release notes to figure out what version of OpenShift that maps to.

Can you include the OpenShift version the about dialog as well?

**Comment by andybraren** [comment]
Hi @omajid

The Details card in the top-left corner of the Cluster Overview landing page and the About dialog should both include the OpenShift version. I believe it was added to the Overview in 4.2-ish, and it may have been in the About dialog before then (not sure).

Are those the places you'd expect to see the OpenShift version?

![image](https://user-images.githubusercontent.com/9122899/83050349-71610900-a01a-11ea-9594-fe4a615fc938.png)

![image](https://user-images.githubusercontent.com/9122899/83050425-8e95d780-a01a-11ea-834b-8217b685fc5f.png)

**Comment by omajid** [comment]
Oh, that's great to see!

I think I must be using an older version of OpenShift. I don't see the "Cluster Overview" page in my instance. The About dialog only shows the Kubernetes version (1.16.2), which makes me suspect I am running 4.3?

**Comment by jmtd** [comment]
Thanks @omajid for filing. I'm glad this is addressed in 4.4 in some respect. I'd also expect ot see it in the output of `oc version`. (Just firing up a 4.4 cluster to check the output of that)

**Comment by omajid** [comment]
I start up a local instance using Code Ready Containers.

![image](https://user-images.githubusercontent.com/174451/83421936-cf189b00-a3f6-11ea-88db-f5d1a898bcd5.png)


```
$ oc version
Client Version: 4.3.19-202005020952-4fb2d4d
Kubernetes Version: v1.17.1
```
Is this something CRC is doing? Or something more general to OpenShift

**Comment by spadgett** [comment]
You currently need authority to see the `ClusterVersion` resource to get the OpenShift version. This is not a console limitation per se. It's true across the platform.

I agree normal users should be able to see the version.

**Comment by spadgett** [comment]
I opened this Bugzilla against the OpenShift API server since there's currently no API the console can use:

https://bugzilla.redhat.com/show_bug.cgi?id=1850656

**Comment by omajid** [comment]
This seems to be fixed now? I am not running as admin and I see version 4.8 in Help > About:

![image](https://user-images.githubusercontent.com/174451/158401458-c6688c86-27ca-41ad-b93c-027e846a6e94.png)

**Comment by vlskrbek** [comment]
Maybe I am not on the right version but it does not work. I use Openshift in company as a normal user and do not see openshift version. 
At leas I can run "oc command and see this:
---
oc version
Client Version: 4.8.0-202111041632.p0.git.88e7eba.assembly.stream-88e7eba
Kubernetes Version: v1.23.5+012e945
---
So it looks that we have already version 4.8 but on the "About" I see still the old information:
---
Red Hat OpenShift Container Platform
OpenShift is Red Hat's container application platform that allows developers to quickly develop, host, and scale applications in a cloud environment.

Kubernetes version v1.23.5+012e945
API server https://api.ocpazrp04.cloud.internal:6443
---
![image](https://user-images.githubusercontent.com/44057715/191945401-4d97625b-5ca4-488b-94e9-9b211dfe0e77.png)

Is this really fixed?

Thanks.

**Comment by TheRealJon** [comment]
Migrated to Jira: https://issues.redhat.com/browse/OCPBUGS-8783
