### ISSUE TITLE
Project drop-down menu for Workloads view may include projects that regular user has no access to in OCP 4.4 console

### ISSUE THREAD

**Issue by redmikhail** [openshift/console#5719]
For non cluster-admin users Administrator OCP UI Console **Project** drop-down menu on top of main pane may include projects ( projects that appear may be different , users observed “default”, “kube-system”) that user does not have access to when any of the options in Workloads section are selected. While a user does not have ability to make changes or list objects from corresponding project it may create confusion and non-optimal user experience. 
![image](https://user-images.githubusercontent.com/54419922/84342111-ba64a180-ab72-11ea-9d06-b2337cfccfa5.png)
To reproduce : 

1. Create new regular user using htpasswd or any available authentication providers
2. Login to Administrator console
3. Select any of the **Workloads** views,for example **Deployment Configs**
4. Click on _Project_ drop-down menu, random project will appear in the list
5. Create new project 
6. Navigate back to **Deployment Configs** , select _Project_ menu - only one project (new) will be present
7. Logout/Login back to console 
8. Navigate back to **Deployment Configs** , select _Project_ menu - two projects are present in the drop down list, one that was created by user and original one that user has no access to .

Issue has been observed in console of OCP cluster version 4.4.5

**Comment by spadgett** [comment]
Console remembers the last project you selected. I suspect this is where the project is coming from. If you have `default` selected, then log in as a different user, `default` will be still be selected regardless of access. We should consider making the last selected project a per-user value.

There are some other edge cases where this can happen if you favorite or pin a project that gets deleted.

Note we have to be mindful of some edge cases. With k8s RBAC, it's possible to have access to resources in a project without the project appearing in your projects list. For instance, all users can see templates in the `openshift` namespace, but it won't be in the project list. We don't want to break deep-linking to these pages.

@christianvogt fyi
