### ISSUE TITLE
Tell the user not to use IE when the user browses using IE

### ISSUE THREAD

**Issue by cynthia-rempel** [openshift/console#5863]
Hi,
How are you doing today?
Our organization has several users that attempt to browse to everything using IE.  Would it be possible to make it so that when the user browses to the openshift console, it tells the user IE is not supported, and to try one of the supported browsers?
It would be really helpful :)
Thanks!

**Comment by christianvogt** [comment]
@spadgett does console have / need a ticket tracking this?

**Comment by spadgett** [comment]
Hi, @cynthia-rempel. Sorry for the delay triaging this. I've migrated it to a Bugzilla bug. It's tracked here: https://bugzilla.redhat.com/show_bug.cgi?id=1905627. Please subscribe to the bug for updates. Thanks!

/close
