### ISSUE TITLE
Upgrade Yaml Language Server to 0.9.0

### ISSUE THREAD

**Issue by apupier** [openshift/console#6084]
currently in 0.5.4 version. https://github.com/openshift/console/blob/77856f48439612c4b577f601a1bb0c40c65cd2bc/frontend/package.json#L156

it would be nice to upgrade it to latest version. it contains a lot of improvements and bugfixes.

**Comment by spadgett** [comment]
Hi @apupier, we are already working on this as part of https://bugzilla.redhat.com/show_bug.cgi?id=1849101. Closing this issue to avoid tracking it twice.

cc @rebeccaalpert
