### ISSUE TITLE
Provide tests for Yaml editor component

### ISSUE THREAD

**Issue by apupier** [openshift/console#6091]
I found no test checking that the Yaml Editor is working. It would be nice to add one. it will avoid potential regression and ease upgrades.

**Comment by apupier** [comment]
found a test part of the integration-tests:
https://github.com/openshift/console/blob/e4a25f3c713ba36aa7aab14792941ba151246434/frontend/integration-tests/tests/crud.scenario.ts#L104-L119

would remain interesting to have one for the component itself

**Comment by spadgett** [comment]
Hi @apupier. The YAML editor is used extensively throughout our integration tests. If it's not working, we'll definitely catch it.
