### ISSUE TITLE
[Question]Why Yaml editor is registering providers to Monaco Editor although there is a Language Server a,d the monaco-languageclient?

### ISSUE THREAD

**Issue by apupier** [openshift/console#6093]
I noticed that several providers are registered to the Monaco Editor:

https://github.com/openshift/console/blob/e4a25f3c713ba36aa7aab14792941ba151246434/frontend/packages/console-shared/src/components/editor/yaml-editor-utils.ts#L90-L195

although the goal of using the a Language Server and a Language client is to not have to do that. The Language Server should be registered one time using the language client and all completion/diagnostic/outline/and more are registered automatically. 

https://github.com/TypeFox/monaco-languageclient/blob/fb587b3ff258d48194c8667a6ade2d0fd87d06bd/example/src/client.ts#L51-L70

Was there some bugs in the monaco-languageclient forbidding that? any other reasons? Am i missing something?

**Comment by spadgett** [comment]
/assign @JPinkney 
who worked on this

**Comment by JPinkney** [comment]
I technically didn't do the original/first setup with the monaco and yaml language server integration, that stuff was done here: https://github.com/gorkem/yaml-server-browser-example/blob/master/src/client.ts#L71 and then I just ported the code all over.

I don't think there's anything forbidding it off the top of my head, we were just on a tight deadline so I just ported that code, made it work, and then shipped it.
