### ISSUE TITLE
Custom Resource form view doesn't consider mutating webhook for validation.

### ISSUE THREAD

**Issue by Chengxuan** [openshift/console#6175]
In Kubernetes design, the mutating admission webhook is invoked before any validation:
> Mutating admission webhooks are invoked first, and can modify objects sent to the API server to enforce custom defaults. After all object modifications are complete, and after the incoming object is validated by the API server, validating admission webhooks are invoked and can reject requests to enforce custom policies.

from [here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks)

A flow chart view:
![image](https://user-images.githubusercontent.com/5425125/89029171-bd377380-d325-11ea-89eb-12745325aef3.png)

Therefore, when a user is creating a Custom Object, they can provide an object that doesn't conform to the CRD schema and relies on the mutating webhook to convert it into an object compliant to the CRD schema.

However, the openshift console is built based on the CRD schema so that a user won't be able to create an object that doesn't conform to the CRD schema.

**Comment by spadgett** [comment]
cc @TheRealJon @tlwu2013 

We might need a CSV annotation to disable validating the form against the schema.

**Comment by Chengxuan** [comment]
@spadgett With some test on the spec descriptor https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#specDescriptors-1


it's possible to tell the console to ignore the schema validation. (we overrode an enum field with text and the enum constraint went away) This issue might be invalid.

**Comment by spadgett** [comment]
Thanks for the feedback. Closing since this can be addressed with descriptors.
