### ISSUE TITLE
Replace react-lightweight-tooltip with a more robust tooltip component

### ISSUE THREAD

**Issue by jhadvig** [openshift/console#62]
Currently for tooltips we are using https://github.com/mcumpl/react-lightweight-tooltip component. Unfortunately it's really lightweight since it doesn't supports some crucial settings OOTB :
- tooltip placement
- event triggering
- callbacks
- ...

For that reason I would propose to switch to https://github.com/wwayne/react-tooltip component instead of the current one.

**Comment by kyoto** [comment]
Actually, we were previously using `react-tooltip` and it was switched to `react-lightweight-tooltip` for performance reasons (see https://github.com/openshift/console/commit/6440f4cca2cbfe8484ac3019226d3fb381ca7d97).

cc @kans

**Comment by kans** [comment]
@jhadvig We are working on fully implementing [react-virtualized](https://github.com/bvaughn/react-virtualized) for all heavy weight components.  Hopefully this work will be wrapped up within the next week or two.  I'd be potentially OK switching to a more featureful implementation afterwards (assuming it has sane Deps) as long as you profile the difference.  I wish I put the numbers in my PR...

**Comment by spadgett** [comment]
Since we've had performance problems with react-tooltip in the past and we've solved the positioning problem for the copy to clipboard button in #177, I think we should leave well-enough alone. We can revisit if needed later.

/close
