### ISSUE TITLE
ImageStreamTag display won't work quite like expected

### ISSUE THREAD

**Issue by smarterclayton** [openshift/console#621]
Image stream overview displays a list of tags, which are clickable.  However, that takes me to image stream tags view.  On that view, I don't see historical tags (you need the image stream for that).  But another problem is that you can have spec or status tags, and both need to be viewable (i.e. the following states)

1. You only have a status tag on the image stream called `foo` (can have history, image stream tag will return something)
2. You only have a spec tag on the image stream called `foo` (no history, image stream tag api returns 404)
3. You have both spec and status tag called `foo` (can have history, can have spec, and need to show image metadata).

At some point we will release a v2 image stream tag api that corrects the gaps in the current v1 image stream tag.  Until then, you'll need to do the following:

1. Fetch image stream
2. Fetch image stream image if the latest status tag has an image definition
3. Show the history from status, the spec (if it exists), and the image metadata from image stream image.

**Comment by spadgett** [comment]
/assign @jhadvig 

@jhadvig We have a few details pages in OLM that watch multiple resources. I would look at those when you start work on this.

**Comment by spadgett** [comment]
Also tracked by CONSOLE-1450

**Comment by jhadvig** [comment]
Following PRs have been merged to address the issue:
https://github.com/openshift/console/pull/1491
https://github.com/openshift/console/pull/1699
https://github.com/openshift/console/pull/1712
https://github.com/openshift/console/pull/1762 

@spadgett can this issue be closed ?

**Comment by spadgett** [comment]
History added in #1762 and tag linking fixed by #1712

/close
