### ISSUE TITLE
Annotations on ImageStream overview are hard to view

### ISSUE THREAD

**Issue by smarterclayton** [openshift/console#622]
The annotations link on ImageStream overview pops up a modal dialog that only shows 1 row and 30 columns for both name and value, which isn't enough to really convey annotations.  It needs to be possible to view annotations easily, and those annotations can be up to hundreds of characters.  A modal dialog really doesn't allow that to happen.

**Comment by spadgett** [comment]
@openshift/team-ux-review

**Comment by beanh66** [comment]
Thanks @smarterclayton and @spadgett, I just created a design story for this. FYI @serenamarie125

**Comment by bmignano** [comment]
@smarterclayton @spadgett I brainstormed some ideas for this issue in this [google doc](https://docs.google.com/document/d/1DTqnyE-V5TufM_ZESA8razKuEEURPGAsG5WXcUsm7ls/edit?usp=sharing). I included mocks of some potential design solutions and short descriptions of each. Would love to get your feedback on these!

**Comment by spadgett** [comment]
This is tracked by story https://issues.redhat.com/browse/CONSOLE-2235.
