### ISSUE TITLE
Route Labels request

### ISSUE THREAD

**Issue by emamihe** [openshift/console#6251]
Hi,
In openshift 3.x there was label option in console which seems to be removed in openshift console 4.5. This feature is really useful in terms of openshift ingress routers selection for use cases like routers sharding.
It would be awesome if you guys have integration with openshift-ingress-operator to pick up the router name in routes page that the user could easily select it and appropriate labels automatically set.
Currently I fixed my problem with MutatingWebhookConfiguration, but it seems dashboard is buggy and whenever I try to change the labels after 3 times items (like route link) in dashboard won't be updated anymore, however when I take a look to yaml section, it's updated.
I would be so grateful if you have workaround for these.
Thanks for your efforts and stay safe

**Comment by spadgett** [comment]
cc @alimobrem
