### ISSUE TITLE
Bug in openshift console routes page

### ISSUE THREAD

**Issue by emamihe** [openshift/console#6291]
Hi all,

There's a bug in Openshift console which it shows itself whenever you create a pod let's say listening on port tcp/8080 by the running application and then you expose it via clusterIP service on port tcp/80. once the service created when you go for creating route for it surprisingly the wizard page for creating route will pickup port 80 as target-port instead of the port 8080. that's why the tcp connection between Openshift router and pod will broken and then you need to change it manually through yaml.
We pulled your latest code base and rebuilt it and we saw the issue is still remain.
It would be great if you buddies have a look into that. I think wrong field picks up in route page when it wants to send the manifest to openshift api server.

**Comment by emamihe** [comment]
@spadgett Do you have any idea regarding this?

**Comment by spadgett** [comment]
This is fixed by #6284 which was opened at around the same time as this issue. The fix was backported to 4.5.z and 4.4.z as well. Can you try the latest? If this is still an issue, please reopen. Thanks!
