### ISSUE TITLE
Logs out when an image is building

### ISSUE THREAD

**Issue by Bilal-io** [openshift/console#6333]
I have been facing an issue where I get logged out during an image build.

Errors seem related to these calls, I am listing them in the order they were called:

1. 
```
Request URL: https://console-openshift-console.apps.ocp4.domain.com/api/kubernetes/apis/config.openshift.io/v1/clusterversions/version
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 10.11.8.60:443
Referrer Policy: strict-origin-when-cross-origin
```
2.
```
Request URL: https://console-openshift-console.apps.ocp4.domain.com/api/kubernetes/apis/build.openshift.io/v1/namespaces/bk/builds/bk-strapi-10
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 10.11.8.60:443
Referrer Policy: strict-origin-when-cross-origin
```
And then logout gets called
```
Request URL: https://console-openshift-console.apps.ocp4.domain.com/auth/logout
Request Method: POST
Status Code: 204 No Content
Remote Address: 10.11.8.60:443
Referrer Policy: strict-origin-when-cross-origin
```

Let me know if there is more info I can provide to help debug the issue.

**Comment by spadgett** [comment]
If console receives a 401 HTTP response, it will redirect to login. I would expect 403 forbidden if you don't have authority to get the resource. I'm a little suspicious about the 500 error as well on the `ClusterVersion` request. You should get 403 if you don't have authority.

@Bilal-io Is there any chance your session expired? Do you consistently get logged out only on this page?

**Comment by Bilal-io** [comment]
@spadgett I don't believe it was because the session expired, because sometimes I am interacting with the page and it happens. 
Could it be because the leader changed? Does that usually make the session expire? Because I do sometimes get warnings that the leader has changed.

I believe I get logged out at other times, but I always linked it to the fact an image is being built. I'll monitor that.

I'd be happy to run more tests, and provide any additional info about my setup. Just let me know what's needed.
