### ISSUE TITLE
Compatibility issue with Safari in openshift-console 4.7

### ISSUE THREAD

**Issue by emamihe** [openshift/console#6421]
Hi all,

There's an issue in openshift-console which seems that the assset files are not compatible with Safari browser. but it's fine with Google Chrome and Firefox.
This is the page it shows me when I open it in Safari:

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/33328203/91094028-76f8da00-e66f-11ea-82d0-9aaf1551f855.png">

**Comment by andrewballantyne** [comment]
cc @spadgett

**Comment by spadgett** [comment]
Thanks for the report. Fixed by #6252. See https://github.com/openshift/console/pull/6252#issuecomment-675027938. Let us know if you still see the issue.

/close
