### ISSUE TITLE
Alerting dashboard issue in openshift console 4.7

### ISSUE THREAD

**Issue by emamihe** [openshift/console#6476]
Hi all,

It seems there is issue in Openshift Console 4.7, when I try to open up the alerting dashboard under monitoring section it shows me 404 not found message:
![image](https://user-images.githubusercontent.com/33328203/91645939-39c18d00-ea5f-11ea-9068-a69518133c05.png)

the url goes to /api/prometheus/api/v1/rules but responded with 404
I would be grateful if you can have look into this.

Thanks in advance,
Hamid

**Comment by spadgett** [comment]
@dtaylor113 @kyoto We've seen this before... Do you know if we have a Bugzilla bug tracking?

**Comment by dtaylor113** [comment]
> @dtaylor113 @kyoto We've seen this before... Do you know if we have a Bugzilla bug tracking?

@spadgett, possibly related:  https://bugzilla.redhat.com/show_bug.cgi?id=1866200

**Comment by kyoto** [comment]
@dtaylor113 I don't think that issue would explain a 404 error

@emamihe Do you also get a 404 error on the Silences tab?

**Comment by emamihe** [comment]
Yes @kyoto jan
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/33328203/92143581-b7541700-ee2a-11ea-9829-9a6f4aa75b75.png">

**Comment by kyoto** [comment]
Thanks @emamihe. Actually that "Not Found" message is different from a 404 and simply means that there are no silences yet. So it looks like your connection to Alertmanager is fine, but the Prometheus `/rules` call is failing.

I wonder if it's just `/rules` or all Prometheus API calls 🤔 If you go to the "Monitoring > Dashboards" page (which uses different Prometheus API endpoints), does it load correctly, or do you get 404s there too?

**Comment by emamihe** [comment]
You're welcome Kyoto jan,
Yes monitoring dashboard page is working and there's no issue there.

**Comment by kyoto** [comment]
Intermittent failures when accessing the `/rules` API were identified. See issue https://bugzilla.redhat.com/show_bug.cgi?id=1897252.

**Comment by kyoto** [comment]
Issue https://bugzilla.redhat.com/show_bug.cgi?id=1897252 was fixed and I have not been able to recreate this problem, so I think this is now resolved.

/close
