### ISSUE TITLE
Categorizing feature request for Developer Catalog

### ISSUE THREAD

**Issue by emamihe** [openshift/console#6491]
Hello back,

One of the features I really enjoy in Openshift is Developer Catalog which is highly customizable through "openshift" namespace and templates manifests. 
But there is just one problem there regarding categorization for the items in left pane:
<img width="1654" alt="Screen Shot 2020-09-02 at 03 07 45" src="https://user-images.githubusercontent.com/33328203/91913477-f79c8380-ecca-11ea-87f2-7836682035ce.png"> 
It seems categories listed there are hard coded in this file:
https://github.com/openshift/console/blob/de042e5aa06e83cbddece9aab362d30cc82b93fc/frontend/public/components/catalog/catalog-items.tsx

And matching items in categories are happening based on tags mentioned in template manifest:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/33328203/91913792-bc4e8480-eccb-11ea-9d8b-2a350414d22d.png">
It could be amazing if a workaround can be made by adding a Category field in templates CRD that user can place his/her own developed items under arbitrary categories rather than the fixed ones currently exists in code.

Thanks in advance,
Hamid

**Comment by spadgett** [comment]
cc @christianvogt @serenamarie125

**Comment by serenamarie125** [comment]
We have an Epic around this very request!  https://issues.redhat.com/browse/ODC-3671

**Comment by emamihe** [comment]
Yes I know Serena jan, This is not a thing that just limited for changes in openshift-console. It definitely needs changes in Kubernetes layer probably some new CRDs, changes in controller manager and finally integration with Console. Anyway, can't wait to see it :)

**Comment by spadgett** [comment]
We've added custom categories in #7196. These are configured through the console operator config.

/close
