### ISSUE TITLE
When comparing an object on the console and on the terminal I get different output.

### ISSUE THREAD

**Issue by oiricaud** [openshift/console#6619]
If you look at the images... I have a `yaml` file and I have different outputs. The console image has a `>` instead of a `|` and creates more lines than necessary and messes up the parsing 

`ocp 4.3.5`
<img width="823" alt="Screen Shot 2020-09-14 at 1 06 18 PM" src="https://user-images.githubusercontent.com/11867058/93121809-14ea2e00-f68b-11ea-9091-6ef6f37bbd9a.png">

<img width="812" alt="Screen Shot 2020-09-14 at 1 06 28 PM" src="https://user-images.githubusercontent.com/11867058/93121827-1ae00f00-f68b-11ea-9550-dfc933865003.png">

**Comment by spadgett** [comment]
These YAML documents are equivalent. One is using folded style and the other literal style, but the content is the same. See https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-over-multiple-lines

We don't have a ton of control over what scalars are used in the js-yaml library we have, and it's hard to have a simple rule for every case.

/close

**Comment by oiricaud** [comment]
@spadgett Gotcha, my pipeline breaks when I use `>` as opposed to use `|`. I had a pipeline in cluster `a` and wanted to move this pipeline to cluster `b` so I copied and pasta and noticed when I use `>` my pipeline concatenates my bash scripts and breaks the pipeline, but thanks for the information.

**Comment by spadgett** [comment]
This seems odd. It shouldn't as long as you leave a blank line whenever you want a newline. Did you also use `>` in the YAML in the other cluster?
