### ISSUE TITLE
Issue in session verification in openshift-console 4.7

### ISSUE THREAD

**Issue by emamihe** [openshift/console#6656]
Hi all,

It seems there's an issue in openshift console session verification that when I login into openshift console it shows me the message below and then it logout, this usually happens when my session expires and then I re-authenticate and login back this issue pops out.
It gets fine when I login into dashboard by removing whole path after the subdomain part
<img width="956" alt="image" src="https://user-images.githubusercontent.com/33328203/93394170-08cbbf80-f889-11ea-8c40-61e13e51ef44.png">
Could you please have look into it?
Thanks in advance

Regards,
Hamid

**Comment by spadgett** [comment]
@emamihe Is it possible you have multiple tabs open when this happened? There are some known issues around logging in with multiple tabs, which can happen after session expiration.

**Comment by emamihe** [comment]
Hi Sam,
No. it's not possible

**Comment by spadgett** [comment]
This could be related to one of the following Bugzilla bugs:

https://bugzilla.redhat.com/show_bug.cgi?id=1765259
https://bugzilla.redhat.com/show_bug.cgi?id=1859746
