### ISSUE TITLE
OLM dashboard show operator version from all channels

### ISSUE THREAD

**Issue by NissesSenap** [openshift/console#6695]
### Is your feature request related to a problem? Please describe.
I would like to see which versions is available on all the channels when I'm choosing to install a operator.

### Describe the solution you'd like
Ether show the different operator versions available when first clicking the operator.

![image](https://user-images.githubusercontent.com/14774899/93777151-aece4f80-fc24-11ea-8bfc-59d54f98d19f.png)

**Or show which version you get when picking which channel.**

![image](https://user-images.githubusercontent.com/14774899/93777196-bbeb3e80-fc24-11ea-8b97-dd1fdd70d891.png)

See original issue in https://github.com/operator-framework/operator-lifecycle-manager/issues/1744

**Comment by spadgett** [comment]
cc @tlwu2013 @TheRealJon

**Comment by TheRealJon** [comment]
Closing. This feature is being tracked in [Jira](https://issues.redhat.com/browse/CONSOLE-2492)
