### ISSUE TITLE
test cluster console api

### ISSUE THREAD

**Issue by fenggolang** [openshift/console#679]
I want to test the okd3.11 cluster console api, but I don't know which one the header uses, it seems that the token is not used？
![image](https://user-images.githubusercontent.com/16982786/47282586-6827e300-d612-11e8-9105-c9c3bd8748ba.png)

**Comment by spadgett** [comment]
No, it doesn't use an Authorization header. It uses a cookie and a CSRF token header.

I'm not sure what you're testing, but if you just want to use the OpenShift API, I'd recommend talking directly to it. The console endpoint is only a proxy.

/kind question
/close
