### ISSUE TITLE
Support multiple YAML documents in a single file when importing YAML

### ISSUE THREAD

**Issue by linqingping** [openshift/console#6950]
An error occurred
Error parsing YAML: YAMLException: expected a single document in the stream, but found more

**Comment by spadgett** [comment]
We currently don't support multiple YAML documents in a single file when importing YAML. We're tracking this as a feature. You'll need to create each resource separately or use the CLI for now.

cc @alimobrem

**Comment by spadgett** [comment]
This feature is being tracked by JIRA https://issues.redhat.com/browse/CONSOLE-1338. Closing the issue to avoid duplication.

/close
