### ISSUE TITLE
Drag and drop icon present in read/only view on single env values and not envFrom

### ISSUE THREAD

**Issue by jcaianirh** [openshift/console#697]
For the read-only pages (pods / builds) without vars set, the drag and drop icons shouldn't be present in either env types in the editor.

**Comment by jcaianirh** [comment]
![screen shot 2018-10-25 at 10 53 33 am](https://user-images.githubusercontent.com/35978579/47509557-575eb380-d844-11e8-8bf8-de4c7a20394d.png)

**Comment by rebeccaalpert** [comment]
See https://github.com/openshift/console/pull/699.
