### ISSUE TITLE
Consider adding Jobs to topology view

### ISSUE THREAD

**Issue by christophd** [openshift/console#7202]
AFAIK topology view displays Deployments and DeploymentConfigs but Job items are not handled. What is the rationale behind this?

I'd find it useful to also see the Job state and its details as part of the topology view. Also grouping and connecting with other items on the topology view would be very useful as Jobs may be a significant part of a deployment.

**Comment by spadgett** [comment]
I believe this is now been added. @christianvogt, can you confirm?

**Comment by christianvogt** [comment]
Cron Jobs and jobs were added to the topology view.

/close

**Comment by christophd** [comment]
Thanks so much!
