### ISSUE TITLE
Ctrl-W closes browser running the console/terminal window

### ISSUE THREAD

**Issue by dpkshetty** [openshift/console#7247]
When I am in the terminal (of a Pod) ... on a bash shell, Ctrl-W ideally should delete a word (backwords) but it closes the browser window. It would be good to fix Ctrl-W binding such that it is consumed by the terminal window and not by the browser!

**Comment by spadgett** [comment]
It looks like a similar request was closed in xterm.js, which is the terminal we use: https://github.com/xtermjs/xterm.js/issues/2812

We can evaluate if this is possible to do.
