### ISSUE TITLE
Displaying Build duration in the UI

### ISSUE THREAD

**Issue by jchraibi** [openshift/console#7521]
It would be great to display build durations in the UI (as it was the case in OpenShift 3) 
![image](https://user-images.githubusercontent.com/19349382/101883952-44c8a500-3b98-11eb-8ccd-941989b2be2a.png)

**Comment by bysnupy** [comment]
@spadgett Currently, the build "duration" column is not provided at the page in contrast with OCPv3 console. Workaround is manual calculation from the status.duration(nanoseconds) of the build yaml tab, but it's not smart... Let me know that if there is any RFE on this matter. Thanks.
