### ISSUE TITLE
[ocs plugin] capacity breakdown by pod should be grouped when multiple pvc attached in one pod

### ISSUE THREAD

**Issue by shdn-ibm** [openshift/console#7800]
Component: ceph-storage-plugin

Description:
When multiple pvcs are attached in one pod, the capacity breakdown will show the same pod several times in console.

Root cause:
After checking the code, the query item [StorageDashboardQuery.PODS_BY_USED] should add sum() by (pod) in src/constant/queries.ts

**Comment by spadgett** [comment]
cc @bipuladh @cloudbehl

**Comment by cloudbehl** [comment]
@anmolsachan can you look fix the query.

**Comment by cloudbehl** [comment]
@shdn-ibm can you send a patch for this and @anmolsachan can review it.

**Comment by anmolsachan** [comment]
This issue will be fixed as part of https://github.com/openshift/console/issues/7800.
