### ISSUE TITLE
proxy: incorrect usage of write mutex for websockets

### ISSUE THREAD

**Issue by robherley** [openshift/console#7862]
In the following lines for the proxy:

https://github.com/openshift/console/blob/bd1811e3883d163a55bfd232f93f7a28cdfd3643/pkg/proxy/proxy.go#L254-L255

The params for copyMsg are `copyMsg(mutex, dest, src)`, since the write mutex is used to protect the frontend ws, shouldn't  line 254 have the mutex, not 255?

https://github.com/openshift/console/blob/bd1811e3883d163a55bfd232f93f7a28cdfd3643/pkg/proxy/proxy.go#L281-L287

**Comment by spadgett** [comment]
/assign @jhadvig 

@jhadvig Can you take a look?

**Comment by spadgett** [comment]
Reopening. This looks like a legitimate problem to me that we should address.

/reopen
/remove-lifecycle rotten
