### ISSUE TITLE
add a copy button in the API token page

### ISSUE THREAD

**Issue by wzhanw** [openshift/console#7991]
This should be a usability enhancement, not a feature bug.
On the API token copy page, every time I need to select all the text, right-click and copy, I think we'd better add a copy button on the page. The text will be automatically added to the clickboard after the user clicked the button.
![image](https://user-images.githubusercontent.com/53284088/106410544-0788e100-647e-11eb-92c6-0c2db03c625d.png)

**Comment by spadgett** [comment]
Thanks, I agree this would be better. That page is actually part of the OAuth server, not console itself, so it's maintained by a different team. Having said that, we are looking at moving this logic into console itself to avoid so many clicks to get the token.

/kind feature

**Comment by nate-duke** [comment]
:(
