### ISSUE TITLE
"Form View" UI in OLM supports multiple Tab

### ISSUE THREAD

**Issue by wondersong** [openshift/console#7994]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I have an issue when (...)"
```
When we deploy our operator in OLM, but we have so many required input values result that all was chaos and confusion.
Although all values could be classified by different sections, all on one page, it is not very friendly from the perspective of UX.
```
**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.
```
If OLM "Form View" UI supports Tab like a tab in the Web browser, we could allocate those similar kinds of CR values order by same components or feature in one Tab. It will make it more clear.
```

Thank you

**Comment by spadgett** [comment]
/kind feature
cc @tlwu2013 @TheRealJon

**Comment by TheRealJon** [comment]
Tracking in https://issues.redhat.com/browse/RFE-1696
