### ISSUE TITLE
source ./contrib/oc-environment.sh can be failed in CI because of `openshift-pipelines-app-delivery` not exist

### ISSUE THREAD

**Issue by gouyang** [openshift/console#8044]
I try to execute below commands in CI and it failed because `openshift-pipelines-app-delivery` not exist in my cluster environment, propose adding `ignore-not-found` to `oc -n openshift-pipelines-app-delivery get route cluster -o 'jsonpath={.spec.host}'`.
```
oc login -u kubeadmin -p $(cat /path/to/install-dir/auth/kubeadmin-password)
source ./contrib/oc-environment.sh
./bin/bridge
```

```+ source contrib/oc-environment.sh
++ BRIDGE_USER_AUTH=disabled
++ export BRIDGE_USER_AUTH
++ BRIDGE_K8S_MODE=off-cluster
++ export BRIDGE_K8S_MODE
+++ oc whoami --show-server
++ BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT=https://api.uit01.cnv-qe.rhcloud.com:6443
++ export BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
++ BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS=true
++ export BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
+++ oc -n openshift-config-managed get configmap monitoring-shared-config -o 'jsonpath={.data.thanosPublicURL}'
++ BRIDGE_K8S_MODE_OFF_CLUSTER_THANOS=https://thanos-querier-openshift-monitoring.apps.uit01.cnv-qe.rhcloud.com
++ export BRIDGE_K8S_MODE_OFF_CLUSTER_THANOS
+++ oc -n openshift-config-managed get configmap monitoring-shared-config -o 'jsonpath={.data.alertmanagerPublicURL}'
++ BRIDGE_K8S_MODE_OFF_CLUSTER_ALERTMANAGER=https://alertmanager-main-openshift-monitoring.apps.uit01.cnv-qe.rhcloud.com
++ export BRIDGE_K8S_MODE_OFF_CLUSTER_ALERTMANAGER
+++ oc -n openshift-pipelines-app-delivery get route cluster -o 'jsonpath={.spec.host}'
++ GITOPS_HOSTNAME=
[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // dir
```

**Comment by spadgett** [comment]
Hi, @gouyang. I don't see an error sourcing the script... Looking at the script, I'm not sure why it would fail. I'd expect `GITOPS_HOSTNAME` to simple be empty?

cc @chetan-rns

**Comment by gouyang** [comment]
@spadgett There isn't error showing because it redirect stderr to /dev/null. However, it clearly shows it doesn't continue and exits. 
The error happens because `openshift-pipelines-app-delivery` is not existing in our cluster.

`oc -n openshift-gitops get route cluster -o jsonpath='{.spec.host}' 2> /dev/null`

**Comment by spadgett** [comment]
> @spadgett There isn't error showing because it redirect stderr to /dev/null.

Right, that's what's supposed to happen.

> However, it clearly shows it doesn't continue and exits.

But it doesn't? It prints "Using *api-server-url*" at the end, so it can't be exiting.

**Comment by gouyang** [comment]
> > @spadgett There isn't error showing because it redirect stderr to /dev/null.
> 
> Right, that's what's supposed to happen.

> 
> > However, it clearly shows it doesn't continue and exits.
> 
> But it doesn't? It prints "Using _api-server-url_" at the end, so it can't be exiting.

I didn't see it print  "Using _api-server-url_", where do you see it?

By default, Jenkins exit with failure if any of the commands in the script failed, it's clear that `oc -n openshift-gitops get route cluster -o jsonpath='{.spec.host}' 2> /dev/null` will fail on a cluster which does not have namespace `openshift-gitops` exists.

**Comment by spadgett** [comment]
Oh, you're running this in Jenkins? What is the Jenkins job for? We should be testing the in-cluster console in any CI, not running a local console.

**Comment by gouyang** [comment]
The Jenkins job is to verify test patches. eg: https://github.com/openshift/console/pull/8065

**Comment by spadgett** [comment]
Why not test the in-cluster console?

**Comment by gouyang** [comment]
> Why not test the in-cluster console?

I also have tests for in-cluster console, it is because the cluster console is always over weeks behind the latest, so test with local console is quite necessary.
