### ISSUE TITLE
OLM Form View "fieldDependency" only allows with sibling fields

### ISSUE THREAD

**Issue by lpchitta** [openshift/console#8120]
During our first OLM Form View implementation ,we came across the requirement of using `fieldDependency` where this only works with sibling field . This created number of issues where we need to change existing custom resource parameters .

We would like to report this for a improvement where `fieldDependency` should work for between any custom resource parameter.

**Comment by spadgett** [comment]
cc @TheRealJon @tlwu2013

**Comment by TheRealJon** [comment]
@lpchitta This is fixed in 4.7

**Comment by spadgett** [comment]
@TheRealJon Looks like our reference doc needs to be updated:

https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#20-fielddependency

> "Field dependency" only exists between sibling fields in CRD's schema.

**Comment by TheRealJon** [comment]
Updated in #8278
