### ISSUE TITLE
Form View does not validate all required fields.

### ISSUE THREAD

**Issue by lpchitta** [openshift/console#8123]
We have a CRD parameter called `license` which is required in CRD but when we did not select this parameter technically it should prevent from applying CR. But currently the same does not work for license parameter but the same works for other parameter

**Comment by spadgett** [comment]
cc @TheRealJon @tlwu2013

**Comment by TheRealJon** [comment]
We don't do any form validation on the front end after v4.4, so it seems likely this is either a schema issue or an OLM issue.

**Comment by lpchitta** [comment]
@TheRealJon Hmm... Is there any way we can open an issue with front end ?

**Comment by TheRealJon** [comment]
@lpchitta This issue is already against the front end. If it's not too much trouble, could you provide a snippet of yaml that reproduces the issue you're having? I can help troubleshoot to see if this is an issue we need to raise with the OLM team.

**Comment by lpchitta** [comment]
@TheRealJon I believe we found the issue on our side. Thank you.
