### ISSUE TITLE
View selector icon cuts off at certain screen sizes

### ISSUE THREAD

**Issue by bmignano** [openshift/console#817]
Minor issue I found on the project status page where the page view selector icon (dashboard) gets cut off at certain screen sizes. See screenshot below. @spadgett 

<img width="1161" alt="screen shot 2018-11-15 at 11 25 57 am" src="https://user-images.githubusercontent.com/40238481/48566747-9030fc00-e8c9-11e8-9e4a-91020eefdd7a.png">

**Comment by spadgett** [comment]
/assign @sg00dwin 

#810 does make the label shorter, so this might be fixed by that

**Comment by sg00dwin** [comment]
Fixed in https://github.com/openshift/console/pull/810
updated to button in https://github.com/openshift/console/pull/1013
