### ISSUE TITLE
Developers should be able to see Operators but not install

### ISSUE THREAD

**Issue by mandibuswell** [openshift/console#8282]
Currently if you are a developer, you can only see Installed Operators available for you to use.
I suggest that it would be a better user experience fi the developers could search the catalog and see available operators. They cannot install, but perhaps they can make a 'request for install'  or at least they can email the system administrator offline and request and operator.

At a very minimum a link to external documentation that is clickable would be help.

**Desired Experience:**
As a developer I would like to be able to navigate the the Operator Hub on the OpenShift console and browse the available operators for OpenShift.

**Added bonus experience.**
As a developer I would like to request the installation of an operator from the cluster administrator via the Operator Hub interface.

**Comment by TheRealJon** [comment]
cc @tlwu2013

**Comment by TheRealJon** [comment]
Tracked by https://issues.redhat.com/browse/RFE-1879
