### ISSUE TITLE
Upgrade of a `Helm` Chart with dependencies results in an error

### ISSUE THREAD

**Issue by mic4ael** [openshift/console#8377]
OKD cluster version: `4.6.0-0.okd-2021-02-14-205305`

I am using [Sentry Helm Chart](https://github.com/sentry-kubernetes/charts) to deploy Sentry on my OKD4 cluster. I have added a `HelmChartRepository` and I am able to install `Helm Chart` without any issues. The following error

> Failed to upgrade helm release: found in Chart.yaml, but missing in charts/ directory: redis, kafka, clickhouse, rabbitmq, postgresql, nginx

occurs when I am trying to upgrade the release to the same version but with different values.yaml. I am not sure but probably the problem lies in [`this if`](https://github.com/openshift/console/blob/master/pkg/helm/actions/upgrade_release.go#L31) and the fact we are calling `loader.Load` only `if url == ""`. Maybe `rel.Chart` is missing the information about chart's dependencies?

**Comment by spadgett** [comment]
cc @pedjak  @sbose78 

/kind bug

**Comment by sbose78** [comment]
Ack @spadgett

**Comment by dperaza4dustbit** [comment]
I can recreate this issue CRC Openshift Version 4.7.5

Just upgrading to do a password rotation:

![image](https://user-images.githubusercontent.com/10506309/116104855-cb30df80-a67e-11eb-9e45-d36b15bf5787.png)

**Comment by dperaza4dustbit** [comment]
from helm cli rotation goes through fine:

dperaza@dperaza-mac charts % helm upgrade davp-postgresql bitnami/postgresql --set "postgresqlPassword=quebola2"                               
Release "davp-postgresql" has been upgraded. Happy Helming!
NAME: davp-postgresql
LAST DEPLOYED: Mon Apr 26 10:42:41 2021
NAMESPACE: default
STATUS: deployed
REVISION: 3
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

PostgreSQL can be accessed via port 5432 on the following DNS name from within your cluster:

    davp-postgresql.default.svc.cluster.local - Read/Write connection

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default davp-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run davp-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:11.11.0-debian-10-r62 --env="PGPASSWORD=$POSTGRES_PASSWORD" --command -- psql --host davp-postgresql -U postgres -d postgres -p 5432



To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/davp-postgresql 5432:5432 &
    PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U postgres -d postgres -p 5432

**Comment by pedjak** [comment]
the issue is already reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1933101

**Comment by spadgett** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1933101 has been fixed and verified by QE in 4.8.0.

/close
