### ISSUE TITLE
Actions on Project Status wraps early and dropdown misaligned

### ISSUE THREAD

**Issue by bmignano** [openshift/console#847]
Issues with the actions dropdown on the project status page.

- The actions button wraps when there is still room in line with the page title
- The dropdown does not line up with the button

See screenshot below for reference.

@spadgett

<img width="941" alt="screen shot 2018-11-16 at 2 24 14 pm" src="https://user-images.githubusercontent.com/40238481/48789078-36aa4200-ecba-11e8-8b07-b2d7fb17b6b8.png">

**Comment by spadgett** [comment]
Thanks, yeah. @sg00dwin is already investigating.

/assign @sg00dwin
