### ISSUE TITLE
Implement externalLink option for the org.w3 alm x-descriptor

### ISSUE THREAD

**Issue by dmvolod** [openshift/console#8477]
It would be prefer to open link configured with following OLM descriptor in new window/tab as users always lives Console application in case of click on the provide link
However, changing default behavior for the standard configuration, i.e. `x-descriptors:urn:alm:descriptor:org.w3:link` could have an impact on other applications and configurations
As discussed in #8349 it would be nice to implement this functionality like `x-descriptors:urn:alm:descriptor:org.w3:externalLink`

**Comment by spadgett** [comment]
cc @TheRealJon @tlwu2013

**Comment by tlwu2013** [comment]
I like the approach that "keeps the existing behavior as-is yet provides another option for folks to opt-in".
UX-wise that sounds good to me!

@TheRealJon could you help weigh in from the implementation perspective? Thanks!
