### ISSUE TITLE
<dynamic-plugin-sdk> webpack version confliction of console-shared modules

### ISSUE THREAD

**Issue by shdn-ibm** [openshift/console#8545]
Hi, 
I am using dynamic-plugin-sdk to develop plugin for console. When I import console-shared modules in my plugin, there will be many building errors, as below. I noticed that it may be a webpack version issue, as the `shared` module known as `@console/shared` is built with webpack-4.44, while dynamic plugin is built with webpack-5.0.

```
ERROR in /home/ningding/ocs-console/frontend/packages/console-shared/src/hooks/document-listener.ts
[tsl] ERROR in /home/ningding/ocs-console/frontend/packages/console-shared/src/hooks/document-listener.ts(50,11)
      TS2531: Object is possibly 'null'.
```

**Comment by spadgett** [comment]
@shdn-ibm Just a warning that dynamic plugins are under heavy development and are not yet ready to be used.

**Comment by shdn-ibm** [comment]
Thanks for the update. Will keep monitoring the progress.

**Comment by tetchel** [comment]
+1 would like to see the SDK migrated from the beta to a stable 5.x version (looks like 5.37.0 is latest)

**Comment by spadgett** [comment]
> +1. Additionally I would like to see the SDK migrated from the current webpack 5 beta to a stable 5.x version (looks like 5.37.0 is latest)

Yes, this is on our roadmap.

> TS2531: Object is possibly 'null'.

@shdn-ibm Are you using strict null checks? I suspect that's the problem here rather than webpack versions. We're exploring updating the SDK to be built with strict null checks.

cc @rawagner 

/remove-lifecycle stale

**Comment by shdn-ibm** [comment]
It works for me now, as I am using the latest sdk package built from Bipul.

**Comment by tetchel** [comment]
The strict null checks problem goes away if the SDK is shipped as compiled javascript rather than typescript, so the end user doesn't have to compile it. I don't know if that's planned / if there's an issue tracking that.

**Comment by rawagner** [comment]
> The strict null checks problem goes away if the SDK is shipped as compiled javascript rather than typescript, so the end user doesn't have to compile it. I don't know if that's planned / if there's an issue tracking that.

SDK is shipped as js with ts declaration files. There is no additional compilation needed on end user side, it only needs to be bundled by webpack.

We need to turn on strict null checks to make the consumer app which is also using strict null checks happy.

**Comment by rawagner** [comment]
> 
> @shdn-ibm Are you using strict null checks? I suspect that's the problem here rather than webpack versions. We're exploring updating the SDK to be built with strict null checks.
> 

+1
Im wondering how are you importing console/shared code ? We do not expose that via SDK.
we're planning to turn the strict mode on for sdk, not for other packages yet (like console/shared)

**Comment by shdn-ibm** [comment]
yes

**Comment by bipuladh** [comment]
This was an initial confusion as we had not exposed packages as part of the SDK yet. I guess this issue is resolved as of now. @shdn-ibm is it oaky to close this issue?

**Comment by shdn-ibm** [comment]
yes, it can be closed.
