### ISSUE TITLE
Need multi-line editor widget in operator creation form UI

### ISSUE THREAD

**Issue by jwalcorn** [openshift/console#8548]
Not sure if this is the right place/forum for such a feature request, but I've created an operator (https://github.com/IBMStockTrader/stocktrader-operator) with a fairly complex form UI, and I have a field where the user can specify an SSL certificate (with the -----BEGIN CERTIFICATE-----, etc.), but it all appears on one line when I use the `urn:alm:descriptor:com.tectonic.ui:text` x-descriptor in my CSV.  Looking at https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#6-text, I just see a single-line text editor widget.  Having one that preserves line breaks and supports scrolling would be much preferable in such a case.  Am I missing something and there is some way to do this?  Thanks!

**Comment by jwalcorn** [comment]
Example CR yaml showing the `global.certs` field:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/28963246/113491050-835dd480-9493-11eb-95e0-06104f18e793.png">

**Comment by jwalcorn** [comment]
How it renders:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/28963246/113491087-b3a57300-9493-11eb-9dfb-0c5d5f8391fc.png">

**Comment by jwalcorn** [comment]
Relevant snippet of my CSV: https://github.com/IBMStockTrader/stocktrader-operator/blob/master/config/manifests/bases/stocktrader-operator.clusterserviceversion.yaml#L323-L328

**Comment by TheRealJon** [comment]
Migrated to RFE: https://issues.redhat.com/browse/RFE-1987
