### ISSUE TITLE
Leverage Custom Resource Definition Structural Schemas in Yaml editor

### ISSUE THREAD

**Issue by apupier** [openshift/console#8716]
Similarly to the feature provided by [VS Code Kubernetes](https://code.visualstudio.com/docs/azure/kubernetes), it would be nice to leverage Custom Resource Definition Structural Schemas in Yaml editor so that completion, validation and hover benefits from it.

There is already the Yaml language Server used. A custom schema provider will need to be provided.

some references:
- [initial feature development in VS Code](https://github.com/Azure/vscode-kubernetes-tools/issues/447)
- [improvements/questions for VS Code feature with latest Kubernetes versions](https://github.com/Azure/vscode-kubernetes-tools/issues/917)

cc @lstocchi which worked on it recently on VS Code side

**Comment by spadgett** [comment]
Hi, @apupier. This should already be working for CRDs with a structural schema. Is there a reason where it wasn't working for you?

cc @JPinkney

**Comment by apupier** [comment]
It was for this kind of resource:

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: bitcoin-to-kafka
spec:
```

I would expect an "integration" completion based on https://github.com/apache/camel-k/blob/9e384110be106b4970af2e967e28e0877fa78359/config/crd/bases/camel.apache.org_kameletbindings.yaml#L66

Personally, it was long ago that i tried but noticed a demo where it wasn't working recently (can be not correct/recent enough CRDs/dev console installed?)
Today, I tried to reproduce but I cannot manage to install the Camel K Operator in an OpenShift instance for now. (usually I do it on Kubernetes but it doesn't have the dev console then)

**Comment by apupier** [comment]
I just tried right now and I do not have the support for Kamelet Binding, see the error:

![Screenshot from 2021-04-26 18-18-57](https://user-images.githubusercontent.com/1105127/116116891-f38aff00-a6bb-11eb-9f47-4052b103f7e8.png)

or is ti available only in some yaml editors?

**Comment by spadgett** [comment]
Can you check the conditions on the CRD to verify there isn't a problem with the structured schema? Otherwise we might need @JPinkney's help.

**Comment by JPinkney** [comment]
I tried it on Friday but forgot to report back. It seems like _some_ values are added to the schema when an operator is installed and the yaml language server picks them up but for some reason not everything from the crd is available. My guess is that whatever is adding parts of the crd to the open-api schema isn't adding everything. I'd have to go and manually grab the schema though to test out that theory though

**Comment by apupier** [comment]
still a relevant feature

**Comment by apupier** [comment]
still a relevant feature
