### ISSUE TITLE
can't open terminal for pods that have more than one container running

### ISSUE THREAD

**Issue by christianaranda** [openshift/console#8762]
Hello,

We are running Openshift console on native kubernetes.  When we try to open a terminal to a pod that has more than one container, we can get to a terminal for the default container but when we switch containers we receive the following error:

> Oh no! Something went wrong.
> Description:
> This API only accepts integers

The details box has the following stack trace:

```
vendors~main-chunk-08b0abf6231b0b9835e1.min.js:163997 Error: This API only accepts integers
    at e._verifyIntegers (vendors~main-chunk-08b0abf6231b0b9835e1.min.js:100807)
    at e.refresh (vendors~main-chunk-08b0abf6231b0b9835e1.min.js:100807)
    at Object.onConnectionClosed (303-chunk-8193ff095b2a5fbf4a73.min.js:1)
    at Object.connect_ (303-chunk-8193ff095b2a5fbf4a73.min.js:1)
    at Object.<anonymous> (303-chunk-8193ff095b2a5fbf4a73.min.js:1)
    at Ni (vendors~main-chunk-08b0abf6231b0b9835e1.min.js:163997)
    at Li (vendors~main-chunk-08b0abf6231b0b9835e1.min.js:163997)
    at vendors~main-chunk-08b0abf6231b0b9835e1.min.js:163997
    at t.unstable_runWithPriority (vendors~main-chunk-08b0abf6231b0b9835e1.min.js:164291)
    at li (vendors~main-chunk-08b0abf6231b0b9835e1.min.js:163997)
```

Can anyone suggest a solution?  I'm surprised no one has reported this yet, so it makes me wonder if we're missing something in our setup.  Everything else is working great.  The only issue is opening a terminal to a pod and switching containers.

**Comment by agquick** [comment]
Hi, I'm actually having this same issue in my cluster. Is there any configuration change we can make to fix this. I'm currently unable to access terminals for any containers in the multi-container pods?

**Comment by spadgett** [comment]
Hi, @christianaranda what Kubernetes version are you using?

@agquick Is your cluster an OpenShift cluster? What version?

**Comment by spadgett** [comment]
I'm not able to reproduce on OpenShift 4.8.0-0.nightly-2021-04-25-231500. This might be specific to a particular k8s version or native k8s vs OpenShift.

**Comment by christianaranda** [comment]
> Hi, @christianaranda what Kubernetes version are you using?
> 
> @agquick Is your cluster an OpenShift cluster? What version?

Thanks for the quick response.  This is Kubernetes version v1.19.6-eks-49a6c0.

In looking at the Chrome developer console, there are a fair amount of 404 errors for various resources, for example:

> http://localhost:9000/api/kubernetes/api/v1/namespaces/openshift-console-user-settings/configmaps/user-settings-kubeadmin
> http://localhost:9000/api/console/user-settings
> http://localhost:9000/api/kubernetes/apis/ocs.openshift.io/v1/namespaces/openshift-storage/storageclusters?
> http://localhost:9000/api/kubernetes/apis/operators.coreos.com/v1alpha1/namespaces/ignitio-staging/clusterserviceversions?

Let me know if you'd like any additional info.  I don't know that those 404's are abnormal or not.  I just followed the steps in the Native Kubernetes section of the docs.

Thanks again!

**Comment by agquick** [comment]
I’m also on native K8s v1.19 hosted by AWS EKS. What’s strange is the terminal loads fine for a pod with a single container. It seems like it’s just not passing the right params to the terminal widget for that specific container.

I do believe that the kubectl exec command requires the “-c” to specify container for pods with multiple containers, maybe that’s the issue?

**Comment by spadgett** [comment]
We do set the container in the query parameters:

https://github.com/spadgett/console/blob/02d9dcdc3c8de5d6d4749c9c07f0ddfa87e17aa7/frontend/public/components/pod-exec.jsx#L70

The runtime error appears to be in our error handling when the terminal connection fails. It looks related to https://github.com/xtermjs/xterm.js/issues/3118. If we're able to fix that, the "On no!" error would go away, but the terminal still wouldn't work. We need to figure out the root cause.

Can you confirm it works fine with kubectl?

**Comment by agquick** [comment]
Yes, I can confirm that I can view the terminal for a single container within a pod via kubectl, it's what I'm doing right now until this is resolved.

**Comment by christianaranda** [comment]
Thanks again @spadgett for looking into this.  I'm moving from OpenShift to Kubernetes but really like OC and want to keep using it.  I think this bug is going to keep me from using OC in production, unfortunately (unless it's a quick fix).

Please let me know if I can help or provide additional information.

**Comment by christianaranda** [comment]
Hello @spadgett.  My team and I were able to track down and fix the issue.  I submitted a pull request.

https://github.com/openshift/console/pull/8853
