### ISSUE TITLE
Not cluster-admin users can't see 'TaskRuns' page

### ISSUE THREAD

**Issue by dbazhal** [openshift/console#8796]
Hi.
We are using okd 4.7, and we give our users permissions to admin only their own namespaces.
We make some clusterroles like
```
- apiGroups: ["tekton.dev"]
  resources: ["tasks", "pipelines", "taskruns", "pipelineruns"]
  verbs: ["*"]
```
and we add it to default edit/admin roles with 
```rbac.authorization.k8s.io/aggregate-to-admin: "true"```

So our user opens a page like
```https://{cluster_url}/k8s/ns/{ns}/tekton.dev~v1beta1~PipelineRun/xx-bhtur/task-runs```
in developer view, and console makes request like
```wss://{cluster_url}/api/kubernetes/apis/tekton.dev/v1beta1/taskruns?watch=true&labelSelector=tekton.dev%2FpipelineRun%3Dyyy-bhtur&resourceVersion=69522921```

And user gets an error like 'taskruns.tekton.dev is forbidden: User "yyy" cannot list resource "taskruns" in API group "tekton.dev" at the cluster scope'.

Can that page please make request at namespaced scope?

**Comment by andrewballantyne** [comment]
I was able to reproduce the issue and I wrote steps for the scenario in a Bugzilla. It appears not tied to access driven change you made (fwiw). Please feel free to follow the Bugzilla for status updates: https://bugzilla.redhat.com/show_bug.cgi?id=1954105

Apologizes for the inconvenience of this bug. We'll fix this as soon as possible and backport it to a 4.7.z-stream release. 

In the meantime, I think this work around for the Developer Perspective will work, if you need one.

* Go to the Search page
* Search for TaskRuns and use the "pin to navigation" (right side of the page)
* From the bottom of the developer perspective navigation, you can access that page
* From there you can filter down TaskRuns via the label (at the top select `Name:` and flip it to `Label:`)
* The label key in question is: `tekton.dev/pipelineRun`; set it against the name of your PipelineRun (eg: `tekton.dev/pipelineRun=<name-of-your-pipelineRun>`)

That page state there is essentially what we are doing on the TaskRun. It's a little out of the way, but at least you can get access to the information in the meantime.

**Comment by spadgett** [comment]
Closing this issue as we have https://bugzilla.redhat.com/show_bug.cgi?id=1954105 tracking the problem. Please follow Bugzilla for updates. Thanks!
