### ISSUE TITLE
OpenShift 4.7.0 web console 404s static resources due to en-US language

### ISSUE THREAD

**Issue by andyfeller** [openshift/console#8850]
Since we upgraded to OpenShift 4.7.0, I've noticed a large number of 404s in browser console that seems to be due to the language setting of `en-US` when the assets are housed under `en` _(see attached screenshot below)_.  I'm not sure if this is a configuration issue or one where the language is being taken from the underlying system, so would appreciate some direction as I don't believe we've customized anything around this.

<img width="1680" alt="Screen Shot 2021-05-03 at 1 44 39 PM" src="https://user-images.githubusercontent.com/2089743/116912159-d7d0ad00-ac15-11eb-941e-69d480671567.png">

**Comment by spadgett** [comment]
Hi, thank you for the report. This has been fixed by #8100 and backported to 4.7.5. See https://bugzilla.redhat.com/show_bug.cgi?id=1927311.

/kind bug
/kind i18n
/close

**Comment by andyfeller** [comment]
Thanks for the confirmation and apologies for not realizing this sooner!
