### ISSUE TITLE
Source secret not used by pipeline (tekton) when creating a pipeline from the developer console "deploy from git" form

### ISSUE THREAD

**Issue by jchraibi** [openshift/console#8999]
When creating an app from the console and selecting to create a (tekton) pipeline, using the a private git repo as a source, and declaring a "source secret" to use, the secret isn't picked up by the serviceaccount and the "fetch source" is unable to access the private repo. Manually linking the source secret to the "pipeline" serviceaccount seems to solve that for further runs.

**Comment by serenamarie125** [comment]
@jchraibi this has previously been reported here: https://issues.redhat.com/browse/ODC-4927

**Comment by spadgett** [comment]
Closing as this is tracked in JIRA. Please follow the JIRA bug for updates.
