### ISSUE TITLE
Annotation app.openshift.io/vcs-ref is not working for BitBucket repositories

### ISSUE THREAD

**Issue by beloyar777** [openshift/console#9047]
Can be repoduced in console of OpenShift 4.6.20.

Having the following annotations:
```
app.openshift.io/vcs-uri: https://company.com/projects/XYZ/repos/foo-project/browse 
app.openshift.io/vcs-ref: feature/x-111
```
Topology view shows/generates the following link:
`https://company.com/projects/XYZ/repos/foo-project/browse/tree/feature/x-111`

But the expected/correct BitBucket link is: 
`https://company.com/projects/XYZ/repos/foo-project/browse?at=refs%2Fheads%2Ffeature%2Fx-111`

I have tried the following annotations:
```
app.openshift.io/vcs-uri: https://company.com/projects/XYZ/repos/foo-project/browse 
app.openshift.io/vcs-ref: "?at=refs%2Fheads%2Ffeature%2Fx-111"
```
Topology view still appends '/tree' to the link:
`https://company.com/projects/XYZ/repos/foo-project/browse/tree?at=refs%2Fheads%2Ffeature%2Fx-111`

Please, provide annotation type for **BitBucket** repository.

**Comment by spadgett** [comment]
cc @christianvogt @andrewballantyne

**Comment by christianvogt** [comment]
Note there is a long outstanding issue with bitbucket URLs with branch names containing forward slash: https://jira.atlassian.com/browse/BCLOUD-9969

**Comment by christianvogt** [comment]
@beloyar777 please have a look at this PR https://github.com/openshift/console/pull/9111

It seems that in order to create a valid branch link in your case, we need the commit sha as well. This is because the branch name contains a `/`. Using the base url along with the branch is not sufficient to create a valid branch repo url.

**Comment by beloyar777** [comment]
@christianvogt as far as I can see there is one more issue to handle: 
how do you know, that you have to deal with BitBucket URI if 
`app.openshift.io/vcs-uri: https://company.com/projects/XYZ/repos/foo-project/browse`
doesn't contain any occurance of `bitbucket`?

Just parsing `app.openshift.io/vcs-uri` value for `bitbucket` is not sufficient in my case:
```
if (gitUrl.resource.includes('bitbucket') && !branch.includes('/')) {
    return `${baseUrl}/src/${branch}`; 
 }
```
 
Currently the topology view appends unexpected '/tree' to the link:
`https://company.com/projects/XYZ/repos/foo-project/browse`**/tree**`?at=refs%2Fheads%2Ffeature%2Fx-111`

And if `app.openshift.io/vcs-uri` would contain an occurence of 'bitbucket' topology view it would append '/src' to the URI (as if it would be a master branch), but this is again wrong in my case. The expected/correct BitBucket link for a non-master branch is:
https://company.com/projects/XYZ/repos/foo-project/browse?at=refs%2Fheads%2Ffeature%2Fx-111

It seems, that BitBucket has some differences in the link schema for master and non-master branches which should be correctly addressed by the topology view. 

Also you said, that a commit sha should be provided. Could you please explain how?

**Comment by rottencandy** [comment]
Hi @beloyar777,
#9111 is one half of the fix, please also see https://github.com/openshift/console/pull/9088/files#diff-cce7ec36a6079ecd87e2fc89043657f9b9538b26df0f717ae48557bff91a39d7

We currently default to not using `vcs-ref` in the URL if the domain does not have github/bitbucket/gitlab.

The URL is formatted to bitbucket's documentation: https://support.atlassian.com/bitbucket-cloud/docs/hyperlink-to-source-code-in-bitbucket/

**Comment by christianvogt** [comment]
The topology editor decorator can also be overridden by supplying a custom edit URL using annotation: `app.openshift.io/edit-url`

If you have Code Ready Workspace installed and want the edit URL in topology to open your workspace, then you do want to use `app.openshift.io/vcs-uri` along with `app.openshift.io/vcs-ref`. However in your case with a custom domain we cannot detect the git provide and therefore will default to omitting the branch details. That being said you can set `app.openshift.io/vcs-uri` to be the specific branch URL you want without using `vcs-ref`.

You say that the correct url you need is `https://company.com/projects/XYZ/repos/foo-project/browse?at=refs%2Fheads%2Ffeature%2Fx-111` however in testing it seems like you need to include the branch hash value as follows.
eg. `https://company.com/<org-name>/<project-name>/src/<hash value>/?at=<branch name containing />
I couldn't reach a page on BitBucket for a branch which contains a `/` without including the hash.

**Comment by christianvogt** [comment]
@beloyar777 we could consider supporting your suggested annotation `app.openshift.io/vcs-type` because otherwise we cannot do any detection with a custom domain.
It's been a while since I've looked at this issue but IIRC there's still a problem with constructing a bitbucket URL for your project without having the hash value.

Is this issue still a concern for you?
