### ISSUE TITLE
Error running ./examples/run-bridge.sh 

### ISSUE THREAD

**Issue by kim-tsao** [openshift/console#9148]
I was trying to set up a local console and followed the instructions in the README.  I ran  `./examples/run-bridge.sh ` and got the following error: `index.html not found in configured public-dir path: open frontend/public/dist/index.html`.  I noticed there is no `dist` folder under `public` but there is an `index.html` under `public`, so I modified the script and was able to get past the error.  I think this script should be updated.

**Comment by tetchel** [comment]
I encountered this error if I had not yet run `./build.sh` or `yarn dev` so the frontend hadn't been built yet (hence, no `dist/`).

**Comment by kim-tsao** [comment]
ok, so it's a generated folder.  There must've been a problem when I ran `./build.sh` because that folder was not created.  If I have time, I'll try to set this up again and verify.  Thanks.
