### ISSUE TITLE
webconsole displays a message to set up identity provider w/no instructions on how

### ISSUE THREAD

**Issue by RobertKrawitz** [openshift/console#916]
With installer v0.5.0-master-36-gb4f5ceb6bfde8d3dc0e29f708e0494488ea37ee0 and ostree
ostree 47.194 on AWS, the console displays a banner message:

```You are logged in as temporary administrative user. Set up an identity provider to allow others to log in.
```

Unfortunately, it displays no instructions or guidance about how one might go about doing so.

**Comment by spadgett** [comment]
Will be fixed by #1010
