### ISSUE TITLE
[dynamic-plugin-sdk] Plugin fails to load if "eval-source-map" webpack devtool is used

### ISSUE THREAD

**Issue by tetchel** [openshift/console#9198]
My plugin stopped working when I changed my webpack dev tool to `eval-source-map` (among a bunch of other things, so it was a lot of effort to debug :smile: )

It is because if you use the `eval-source-map` devtool (probably others too, this is just the one I happened to be using), webpack inserts a warning comment at the top of the file:

![source-map-bug](https://user-images.githubusercontent.com/8888438/121377864-b21f7d80-c910-11eb-99f6-65809b8d938d.png)

but the dynamic-plugin-sdk assumes that `window.loadPluginEntry` is the first line of the file [here](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/src/webpack/ConsoleRemotePlugin.ts#L72).

so this results in the plugin ID being inserted at the wrong place (inside the comment, as highlighted in the screenshot above)

The error in the console is `Received callback for unknown plugin [object Object]`, 
followed by `Entry script for plugin <plugin id> loaded without callback`:
![image](https://user-images.githubusercontent.com/8888438/121378990-a1233c00-c911-11eb-8f2a-b7c666a95de9.png)

To compare, here it what it looks like when I switched to the `inline-source-map` devtool, you can see now the plugin ID is correctly passed as the first argument to `loadPluginEntry`.

![source-map-working](https://user-images.githubusercontent.com/8888438/121378109-e5faa300-c910-11eb-819a-54e2587fdbb2.png)

**Comment by spadgett** [comment]
cc @vojtechszocs @christianvogt

**Comment by vojtechszocs** [comment]
This should be fixed by #10433
