### ISSUE TITLE
Machine Sets doesn't show a lack of machines correctly

### ISSUE THREAD

**Issue by crawford** [openshift/console#920]
Looking at https://console-openshift-console.apps.crawford.coreservices.team.coreos.systems/k8s/all-namespaces/cluster.k8s.io~v1alpha1~MachineSet, I see the following:

![image](https://user-images.githubusercontent.com/368848/49676357-40f46c00-fa2e-11e8-8c96-487e1b403c85.png)

" of 0 machines" should probably read "0 of 0 machines" (or maybe something similar).

**Comment by spadgett** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1656719
