### ISSUE TITLE
No feedback in the console when failed to delete a custom object.

### ISSUE THREAD

**Issue by Chengxuan** [openshift/console#9222]
`Configuration` is a customer resource. When deleting a Configuration object, we have an admission webhook to prevent its deletion if it's used by another custom object.

There is no feedback in the openshift console to indicate the deletion has failed and display the error message.

![image](https://user-images.githubusercontent.com/5425125/121695286-d6bb5700-cac2-11eb-8f6c-4d9737e992c3.png)

Version information:
![image](https://user-images.githubusercontent.com/5425125/121695695-3580d080-cac3-11eb-9b66-782d7f08dee8.png)

**Comment by spadgett** [comment]
Looks like this is the same as https://bugzilla.redhat.com/show_bug.cgi?id=1939753. We will need to backport to 4.7.

cc @rebeccaalpert

**Comment by rebeccaalpert** [comment]
Looks like the cherry-pick on the original PR failed. I'll see if I can do a manual cherry-pick.

**Comment by spadgett** [comment]
We're tracking the backport in Bugzilla bug https://bugzilla.redhat.com/show_bug.cgi?id=1971667. Please follow that bug for updates. Thanks!

Closing the GitHub issue so we're not tracking this twice.

/close
