### ISSUE TITLE
OLM descriptor references for map[string]string are not displayed

### ISSUE THREAD

**Issue by SimonBaeumer** [openshift/console#9538]
Hey Console-Team,

we are currently using the OLM descriptors to define a UI for our operator.
While developing it we faced issues with the `map[string]string` type in our API structs to be displayed in the UI.

For example a field described like this is not displayed in the UI:

```
//+operator-sdk:csv:customresourcedefinitions:type=spec,displayName="Cluster Labels",order=11
ClusterLabels map[string]string `json:"clusterLabels,omitempty"`
```

In the related [documentation](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md) [1] I did not find anything which could solve this problem.

Am I maybe missing something or doing wrong here?

Thanks in advance!

Best,
Simon

[1] https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md

**Comment by spadgett** [comment]
cc @TheRealJon @tlwu2013

**Comment by TheRealJon** [comment]
@SimonBaeumer What version of OpenShift are you running and can you provide a snippet of the CSV  `spec.customresourcedefinitions.owned` entry for the CRD you are having issues with?
