### ISSUE TITLE
Project scope changes unexpectedly when installing operator cluster-wide

### ISSUE THREAD

**Issue by chrisbygrave** [openshift/console#9554]
When I choose a cluster-wide install, the project scope in the UI changes from wherever I was to `openshift-operators`. This UX issue leads people to accidentally install operands (the logical next step to installing an operator) into the `openshift-operators` namespace, which is rarely what the user intended to do.

It would be better not to switch context, but if that is difficult to achieve it should be called out and made clear to the user.

**Comment by spadgett** [comment]
I agree there is a usability issue here.

cc @itsptk @tlwu2013

**Comment by itsptk** [comment]
Thanks for filing this issue, this is a notable case where the project selector behavior can be not intuitive to the user. I spoke with the OpenShift UX team at large and we are generally thinking that it is probably time to reconsider the project selector in general, and see if there are other (more intuitive) UI mechanisms we could use to accomplish the same thing. I have opened [a design story](https://issues.redhat.com/browse/PD-1082) to track this.

In the meantime for this particular issue though, I will talk with @tlwu2013 and see if not changing the project selector on a global install is a viable solution, or if there is something else we could do. Thanks.

**Comment by itsptk** [comment]
I have spoken with Tony and we agreed this was a usability issue. We are hoping that we can make a small change to the interaction of installing an operator globally so that the namespace is not changed, so the user doesn't get disoriented. I have opened a design story to track this: https://issues.redhat.com/browse/PD-1093
