### ISSUE TITLE
[OLM] Image list in CSV disappears after creating subscription

### ISSUE THREAD

**Issue by lpchitta** [openshift/console#9574]
As part of OLM CSV , we have included operand images . After we create subscription when we check the deployed CSV under installed operators , we don't see those images list. 
Is there any way to see list of images after creating subscription ?

**Comment by TheRealJon** [comment]
@lpchitta I you are referring to the `spec.relatedImages` field on the CSV, we don't currently display that data on the details page. I've added a story to our backlog to track this. See https://issues.redhat.com/browse/CONSOLE-2955
