### ISSUE TITLE
We can't display/access the Web Terminal of a container

### ISSUE THREAD

**Issue by cmoulliard** [openshift/console#962]
## Info

Openshift Console: master branch
Cloud platform : k8s - 1.13

## Description

Issue : No terminal console is displayed as you can see here when we try to access a pod' terminal

![screenshot 2018-12-18 09 51 00](https://user-images.githubusercontent.com/463790/50142448-79a40900-02aa-11e9-8d37-53363f4fbd95.png)

Console has been launched using these commands

```
2018/12/18 09:46:06 cmd/main: cookies are not secure because base-address is not https!
2018/12/18 09:46:06 cmd/main: running with AUTHENTICATION DISABLED!
2018/12/18 09:46:06 cmd/main: Binding to 0.0.0.0:9000...
2018/12/18 09:46:06 cmd/main: not using TLS
2018/12/18 09:46:07 CheckOrigin: Proxy has no configured Origin. Allowing origin [http://localhost:9000] to ws://192.168.65.42:8080/api/v1/namespaces/my-spring-app/pods?watch=true&fieldSelector=metadata.name%3Dfruit-backend-sb-66ff974cd-2lwjl
2018/12/18 09:46:08 CheckOrigin: Proxy has no configured Origin. Allowing origin [http://localhost:9000] to ws://192.168.65.42:8080/api/v1/namespaces/component-operator/pods?watch=true&fieldSelector=metadata.name%3Dcomponent-operator-59c97d5cb7-h8c8z
2018/12/18 09:46:13 http: proxy error: context canceled
2018/12/18 09:46:14 CheckOrigin: Proxy has no configured Origin. Allowing origin [http://localhost:9000] to ws://192.168.65.42:8080/api/v1/namespaces?watch=true&resourceVersion=22021
2
...
```

I can access remotely a pod using the kubectl command

```
 kubectl exec -it fruit-backend-sb-66ff974cd-2lwjl -n my-spring-app -- /bin/bash
/usr/bin/id: cannot find name for user ID 1001
[I have no name!@fruit-backend-sb-66ff974cd-2lwjl ~]$ ls -la
total 28
drwxrwx--- 4 1001 root 4096 Dec 18 08:11 .
drwxr-xr-x 6 root root 4096 Dec 18 08:11 ..
-rw------- 1 1001 root   16 Dec 18 08:11 .bash_history
-rw-rw-r-- 1 1001 root   18 Sep 26  2017 .bash_logout
-rw-rw-r-- 1 1001 root  193 Sep 26  2017 .bash_profile
-rw-rw-r-- 1 1001 root  231 Sep 26  2017 .bashrc
drwxrwxr-x 2 1001 root 4096 Jul 16 09:30 .m2
```

**Comment by spadgett** [comment]
This is strange. I wouldn't expect any JS to have a syntax errors since it's run through both the TypeScript compiler and eslint. I haven't been able to reproduce (at least on OpenShift, I haven't tried Kubernetes 1.13).

Can you check the network tab to see if the response for 52-chunk... looks like JavaScript?

You might try current master as well to see if it's still an issue.

**Comment by cmoulliard** [comment]
I have updated and **recompiled** the project from master branch and the error is not longer there

<img width="1415" alt="screenshot 2018-12-19 07 46 05" src="https://user-images.githubusercontent.com/463790/50204687-0069ec00-0366-11e9-9458-b582408d5c5a.png">
