### ISSUE TITLE
localization does not work for dynamic plugin

### ISSUE THREAD

**Issue by shdn-ibm** [openshift/console#9748]
Follow the guide to enable the localization of my dynamic plugin, then I find it does not work. 
https://github.com/jhadvig/enhancements/blob/3d22f331d99a7ec4ff0d9ce5b4f4e006d159d5a0/enhancements/console/dynamic-plugins.md#localization

After investigation, function `HandleI18nResources` does not receive the request to process dynamic plugin url. It only receives static plugin related requests.
Further investigation shows similar function `HandlePluginAssets`  works well with dynamic plugin.

**Comment by spadgett** [comment]
Thank you for the report. We're looking at this and tracking the bug under https://bugzilla.redhat.com/show_bug.cgi?id=1992730. Please follow the Bugzilla bug for updates.

**Comment by spadgett** [comment]
This was fixed by #9791
