### ISSUE TITLE
iOS/PF4: Some pages have scrollbars where it's not needed

### ISSUE THREAD

**Issue by spadgett** [openshift/console#976]
All pages seem to have a scrollbar, even pages that don't fill the height of the screen.

**Comment by spadgett** [comment]
Low severity, but it would be nice to fix.

/assign @rhamilto

**Comment by rhamilto** [comment]
This is an [upstream bug](https://github.com/patternfly/patternfly-next/issues/1174).

**Comment by spadgett** [comment]
This has since been fixed.

/close
