### ISSUE TITLE
Unresolved placeholder in Add User to group screen

### ISSUE THREAD

**Issue by jawnsy** [openshift/console#9798]
I'm not sure if this is the right place to file things, please direct me to the correct repository if not!

## Summary

There seems to be a placeholder that isn't getting resolved for some reason:

![image](https://user-images.githubusercontent.com/52710/129217631-0a3acc4a-76fb-431a-96f8-36741ab4569a.png)

## Steps to reproduce

1. Go to the Admin view
2. Under User Management, select Groups
3. View details about a group
4. Under the Actions dropdown, go to Add User

A window appears that shows the text "Add new Users to Group {name}" but doesn't resolve the placeholder

## Hints

The code appears to be here: https://github.com/openshift/console/blob/b9d27de8a52c0b6f52b0a71da322b941953c5182/frontend/public/components/modals/add-users-modal.tsx#L33

Perhaps the `''` string should be a backtick \`\` string?

## Version

Latest from the OKD stable channel: 4.7.0-0.okd-2021-08-07-063045

**Comment by spadgett** [comment]
Thank you for the report. This was fixed in 4.8 by #8786.
