### ISSUE TITLE
Cypress other-routes tests failing on a cluster with no existing resources on certain pages

### ISSUE THREAD

**Issue by miyamotoh** [openshift/console#9903]
The Machines and MachineSets pages are reported failing with Cypress because the clusters that IBM Power CI/QE build out typically have those pages empty. 

Manually testing in my browser, I found that all I needed to do is just create a `Machine` or a `MachineSet` with the Create button provided there. Once created, the tests start passing. 

My suggestion: add logic to `other-routes.spec.ts` so it'll inject "fixture" to alleviate the situation, just for the duration of the test execution, remove it at the end of the tests.

**Comment by spadgett** [comment]
It's possible to mock the HTTP response to avoid this, although the way the tests are structured, that could be tricky. We might simply pull these two pages into separate tests.

/assign @dtaylor113

**Comment by dtaylor113** [comment]
Hi @miyamotoh, I am ok with your fix:  https://github.com/openshift/console/pull/9904.
As I indicated in your PR, in the past we have set enviornmental variables to skip tests which do not work on certain platforms.  For example, see how [storage/clone.spec.ts](https://github.com/openshift/console/blob/68f58f20c2ad43b0cab33d5a4719900ff17caf44/frontend/packages/integration-tests-cypress/tests/storage/clone.spec.ts#L12) uses enviornmental variable `BRIDGE_AWS` to only run the storage tests on AWS systems.
I've added this [comment](https://github.com/openshift/console/pull/9904#issuecomment-907213819) which provides an example of how this could work in your tests.
Adding an example `Machine` or a `MachineSet`also resolves this issue.
