### ISSUE TITLE
Build is not visible in the Status

### ISSUE THREAD

**Issue by siamaksade** [openshift/console#997]
When creating an app via the Developer Catalog, in the Status there are no signs of the build running. The UI appears as if the pod cannot deploy for some reason for a long time:

<img width="1055" alt="screenshot 2019-01-03 at 09 56 47" src="https://user-images.githubusercontent.com/1174934/50629702-fa673400-0f3d-11e9-8213-6de407f2598e.png">

User has to be curious enough and click around on *0 of 1 pods* and then *Resources* to find out a build is running and that's why the pod is not deployed yet:

<img width="1051" alt="screenshot 2019-01-03 at 09 57 11" src="https://user-images.githubusercontent.com/1174934/50629730-1ec31080-0f3e-11e9-813d-4d178dc61842.png">

The build info should be already visible on the Status page.

**Comment by spadgett** [comment]
Yeah, known issue: https://jira.coreos.com/browse/CONSOLE-1024
